- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
To support simplifying the accessions dashboard, remove some values from the
summary API that we're no longer going to be showing and thus don't need to spend
time calculating:
* The number of families. We're now only showing species counts.
* The "last week" statistics for active accessions and species. We're not going to
show percentage changes any more.
The latter change isn't backward-compatible; it lifts the value from a child
object up into the top-level `SummaryResponse` payload.
> SW-1339 Remove unused fields from seed summary API

- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
To allow the web app to show a breakdown of active accessions by current state,
add a field to the `/api/v1/seedbank/summary` response that includes the count
for each state that's considered active. All active states are always included
whether or not there are any accessions in that state.
> SW-1341 Add accession counts by state to summary API

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V109__ViabilityTestSelections.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
Add a `selected` field to the viability test objects in the accession API
payloads. Selecting a viability test doesn't actually do anything yet; this is
just the implementation of the ability to select and deselect tests. Subsequent
changes will add logic to use the results of the selected test as the accession's
overall viability.
At most one test may be marked as selected for a particular accession. It is
completely valid for none of an accession's tests to be selected.
> SW-1322 Add viability test selection

- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/field/ExistsField.kt
- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
Add a boolean search field that acts the same as the `selected` field on viability
test API payloads.
Under the covers, this is a new kind of search field that wraps an `EXISTS()` SQL
expression, since field selection is actually stored in a separate table rather
than as a simple boolean column on `viability_tests`. From the client's point of
view, though, it acts like any other boolean search field.
> SW-1322 Add viability test selection as a search field

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V110__AccessionCollectors.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
We're getting rid of the distinction between primary and secondary collectors,
replacing them with a simple ordered list of collectors for each accession.
We'll migrate collector names to a single unified table. The migration will
happen in four steps:
1. Introduce the new table and start writing to it. Continue writing the old
column/table as well, and continue reading from the old column/table.
(This PR.)
2. Copy existing data to the new table. Start reading the new table.
3. Stop writing the old column/table.
4. Drop the old column/table.
This sequence eliminates any time windows when requests come in during the
middle of code deployment and we end up with data inconsistencies.
The API will be updated as well, but that'll happen after the data migration.
> SW-1350 Migrate to accession_collectors table 1/4

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/V111__AccessionCollectorsBackfill.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
This is step 2 of a sequence of changes to move the collector names from
`accessions.primary_collector_name` and `accession_secondary_collectors` to a
new `accession_collectors` table.
In this step, we backfill `accession_collectors` from the existing data and
update the code to read from it instead of from the old locations. We continue
to write both locations so there isn't data inconsistency while this is in the
middle of being deployed and there are still requests being handled by the
previous code version.
Step 3 will stop writing to the old column and table, and step 4 will drop them.
> SW-1350 Migrate to accession_collectors table 2/4

- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/R__Indexes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
To support showing the total seeds remaining on the accessions dashboard, add a
child object to the `/api/v1/seedbank/summary` response payload that has:
* The total number of seeds remaining in active count-based accessions
* The estimated total number of seeds remaining in active weight-based accessions
that have subset weight/count
* The estimated total number of seeds remaining across all active accessions
(this is just the sum of the first two numbers)
* The number of weight-based accessions that don't have subset weight/count and
thus can't be included in the seed count estimate
The web app can use those four numbers to show a total seed count with indicators
to tell the user that the count is an estimate (`subtotalByWeightEstimate` is
nonzero) and that there are more seeds than …
> SW-1331 Add seed counts to summary API

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/V114__AccessionStateHistoryUser.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
We already keep track of the history of accession state changes; this was needed
to support the "changes since last week" summary statistics. Those statistics are
gone in the new version of the web app, but we're going to need to start showing
the history of changes to an accession, including which user made each change.
Add a user ID column to `accession_state_history` and start populating it.
The second change in this series will backfill the existing history entries and
make the column non-nullable. These changes need to be deployed in sequence to
maintain bidirectional compatibility during code deployment.
> SW-1398 Track user ID in accession state history 1/2

- src/main/resources/db/migration/V115__AccessionStateHistoryBackfill.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
Backfill user IDs into the existing state history rows as best we can, and make
the user ID mandatory.
Unfortunately, there's no way to accurately attribute past state changes to
specific users, especially since the system can automatically change accessions'
states based on scheduled events. So we attribute all state changes to the system
user, aside from the initial ones which we know will always have been caused by
the user who created the accession.
> SW-1398 Track user ID in accession state history 2/2

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/resources/db/migration/V115__AccessionStateHistoryBackfill.sql
- src/main/resources/db/migration/V116__AccessionsCascadeDeletes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
The initial version of the app didn't allow deleting accessions, so I erred on the
side of safety and didn't put `ON DELETE CASCADE` clauses on the foreign-key
constraints on the various child tables.
Now we support deleting accessions, though, so it makes sense to modify the
constraints to auto-delete rows in tables that exist purely to hold lists of
values in accessions. There is never a situation where, e.g., we'll want the
existence of a viability test on an accession to cause us to be unable to delete
the accession.
However, we _do_ want that behavior for accession photos: if we haven't deleted
an accession's photos from the file store yet, we shouldn't be able to delete the
accession since it would cause the files to be orphaned.
> Enable cascading deletes on accession child tables

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionHistoryModel.kt
- src/main/resources/db/migration/V115__AccessionStateHistoryBackfill.sql
- src/main/resources/db/migration/V116__AccessionsCascadeDeletes.sql
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
In the new version of the web app, we need to show a tab with the history of
certain kinds of changes to the accession. Add an endpoint that returns a
time-ordered list of items to show in that UI.
This initial implementation only includes accession creation and state change
events, but those should be enough to start building the UI. Additional types
of history will be added later, but the same API endpoint will return them.
> SW-1228 Add endpoint to fetch accession history

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStore.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
Include withdrawal events in the `/api/v1/seedbank/accessions/{id}/history` API.
Currently these events are attributed to the person whose name is entered into the
"staff responsible" field in the app, which may or may not be a Terraware user's
name. In the near future we'll be constraining that field to the list of
organization members, but with the current data model, we have to treat it as an
optional text value.
> SW-1228 Add withdrawals to accession history

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/V118__CollectionSiteNotesBackfill.sql
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
This is an internal change so we can roll out the new fields without data loss.
In this change, we stop reading and writing `accessions.environmental_notes`
and start reading `accessions.collection_site_notes`. Notes for existing
accessions are copied to the new column here.
> SW-1390 More detailed collection site data 2/3

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/db/migration/V120__CollectionSources.sql
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
The upcoming version of the web app is replacing the "source plant origin"
accession field with "collection source." Add the new field.
The list of allowed values is different; it's possible to losslessly map the
old values to the new ones but not the other way around. So we can't do this as
a purely server-side data model change that supports both fields interchangeably.
Once clients have been updated to use the new field, existing accessions that have
source plant origin values will be backfilled and the old field will be removed.
> SW-1406 Add collection source field to API

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/db/migration/V120__CollectionSources.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
We have a handful of source files that have lists of tables or methods that aren't
trivially short but make sense to keep grouped together. They weren't ordered in a
way that made them easy to navigate or that made it obvious exactly where to add
new entries. Update them to sort the relevant parts alphabetically.
No functional changes here, just shuffling of names.
> Alphabetize entries in some source files

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/db/migration/V120__CollectionSources.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
As a first step in transitioning to a simplified set of withdrawal purposes, add
the new purposes to the API. A subsequent change will update all the existing
withdrawals and remove the purposes we're no longer going to support, but that
can't happen until after the client has been updated to recognize the new ones.
> SW-1410 Add new withdrawal purposes to API

- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionSummaryStatistics.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
We will need to generate some of the same summary statistics for search results
that we do on the accessions dashboard page. Rework the statistics computation
so we'll be able to pass it a query generated by `SearchService`.
As part of this change, we now calculate all the statistics in a single query
rather than using a separate query for each one. This makes the query a little
ugly but will improve performance when we're calculating the stats over a complex
user-defined query.
> SW-1388 Query summary statistics all at once

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
The new version of the app is going to switch to a simplified list of accession
states. Some of them are the same as existing states, but there are also a few
brand-new ones. Add them to the list of states.
No accessions should ever be in these states at the moment, but with this change,
they'll be included in the OpenAPI schema and will also be returned by API
endpoints that list all the values of enums.
> SW-1426 Add new accession states

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
Commit eabb60b9 added the ability to include additional columns in the enum
classes that are generated from the database. Use it to expose the `active`
column on `accession_states`, and then map that to `AccessionActive` values
rather than using an exhaustive `when` statement.
> Simplify mapping of AccessionState to AccessionActive

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/resources/db/migration/V123__AccessionsManualState.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
The new version of the app will allow users to manually edit accession states.
There will still be some automatic state transitions but far fewer than before,
and they will follow a different set of rules.
Add support for manual state management in the data model, including the rules
for automatic transitions. This is tracked on a per-accession basis and an
accession can be moved back and forth between manual and automatic state
management, though the conversion is a bit lossy since the list of valid states
isn't the same in the two worlds.
This only changes the data model and the transition rules; the API behavior
remains the same as before. If you `GET` an accession whose state was manually
set to one of the newly-introduced states, it will be automatically converted
to one of the …
> SW-1425 Add manual state flag to accessions

- src/main/kotlin/com/terraformation/backend/search/NestedQueryBuilder.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
The search code generates `ORDER BY` clauses that use field positions to refer to
fields that are also in the `SELECT` clause, e.g., `SELECT a, b FROM c ORDER BY 2`
to sort by the `b` column. It thus keeps track of what order the fields are added
to the `SELECT` clause so it can use the correct position numbers.
Unfortunately, the code that was actually generating the `SELECT` clause would
always put all the scalar fields first in the list, before all the sublist fields,
even if the caller had specified that the sublist fields should come first. Thus
the `ORDER BY` clause would sometimes use the wrong positions, causing the results
to be incorrectly sorted.
Modify the code to put the fields in the positions the `ORDER BY` construction
code expects them to be, and add a test case that …
> Fix bug in sort order generation in search queries

- src/main/kotlin/com/terraformation/backend/email/WebAppUrls.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
The v2 API will represent cut tests as a third type of viability test rather than
as one-off accession attributes. But for v1 clients, we want to pretend there are
still only two valid test types. Update the data model to add the `Cut` type, and
add a shim to the v1 API to hide it as a valid type.
No behavior change here since there's currently no way to actually create a cut
test in the new style.
> Add a viability test type for cut tests

- scripts/client.py
- scripts/edit_accession.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
To support the different behaviors of accessions in the upcoming version of the
seed management web app, introduce an alternate set of API endpoints. The new
endpoints will behave according to the specifications for the new version, even
for existing accessions. They omit fields that are being removed, and rename some
fields whose names no longer reflect user-facing terminology.
This initial change just covers a portion of the top-level accession payloads and
provides the ability for the client to explicitly change the state of an
accession. It does not change any of the child objects such as viability tests or
withdrawals, and it doesn't change the top-level accession fields related to
how we track changes to seed quantities or how we track overall viability levels.
Those changes will …
> SW-1425 Introduce v2 accession API endpoints

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
In order to display a warning to the user when a change in the date of a
withdrawal would affect the remaining quantity of an accession, the frontend
code needs to know the time of the most recent user-observed accession
quantity. That timestamp won't be shown to users, just used by the frontend code.
Add `latestObservedQuantity` and `latestObservedTime` fields to the v2
accession response payloads. These are computed values, so they're not included
in the request payloads.
The v2 API doesn't support directly updating the remaining quantity yet, so for
now, these two new fields are always calculated from the v1 quantity, similarly
to the way we do an on-the-fly mapping of v1 accession states to v2 ones.
Subsequent changes will start to introduce the write path for v2-style
quantities.
> SW-1357 Add latest observed quantity/time to v2 API

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
We want the v2 accessions API to be more fine-grained than the v1 one. Start
moving in that direction by introducing a separate set of endpoints for reading
and writing withdrawals.
`PUT /api/v2/accessions/{id}` will no longer create, delete, or update
withdrawals.
**The POST and PUT endpoints don't work yet!** They can't be implemented until
the broader updates to quantity tracking are in place. This change just defines
the URL paths and payload formats so client developers can see what they look
like.
The GET and DELETE endpoints don't depend on the new quantity tracking logic, so
they're implemented here, though the quantity values are copied verbatim from
the v1 data and may not be consistent with v2 semantics.
The payloads defined here differ from the ones that are included as …
> SW-1537 Define v2 withdrawals endpoints

- src/main/kotlin/com/terraformation/backend/seedbank/model/SeedQuantity.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/SeedQuantityModelTest.kt
We're going to start allowing count-based withdrawals from weight-based accessions
and vice versa, provided there's a subset weight/count available to convert
between the two.
Enhance `SeedQuantityModel.toUnits()` to support these conversions.
This also fixes imperial unit conversions; previously they worked by converting to
and from metric units, but since metric-to-imperial conversion is approximate, the
end result was incorrect. For example, if you converted 16 ounces to pounds, the
value would be 0.999997995 instead of 1.
> Support weight/count conversions in SeedQuantityModel

- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
The web and mobile apps have been updated to use the unified `collectors`
accession field rather than primary/secondary collectors, so there's no more need
to keep the old fields around for backward compatibility.
> SW-1353 Remove primary/secondary collectors from API

- .github/workflows/docs.yaml
- .github/workflows/main.yml
Currently, GitHub will launch a new build for each new commit on a branch.
This is wasteful of CPU resources in the case of updates to PRs (the results of
the previous build are irrelevant once a new build starts) and occasionally
causes deployment failures in staging if two commits hit `main` in rapid
succession and they boh try to deploy code at the same time.
Fix both problems using the built-in concurrency management feature of GitHub
Actions.
Builds on `main` will be queued up to run one at a time, since we sometimes
need to make sure a sequence of related changes are fully deployed in order.
Builds on branches other than `main` (in practice: builds for PRs) will cause
earlier builds on the same branch to be cancelled so we don't waste CPU cycles.
> Manage CI build concurrency

- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
Add implementations for the withdrawals POST (create) and PUT (update) operations.
Because updating withdrawals causes accession-level information to change, make
the write operations return the entire accession rather than just the information
about the updated withdrawal. In practice, we expect clients will always want the
latest accession details after updating a withdrawal, so no point sending back a
useless response payload and forcing the client to GET the one it actually wants.
Move the endpoints under `/api/v1/seedbank/accessions/{id}` to make it less
surprising that they now return accession payloads.
The new endpoints currently only work for count-based accessions; support for
weight-based accessions will be added as part of a larger change to quantity
management.
> SW-1537 Implement withdrawals POST, PUT endpoints

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
The web app needs to be able to set the accession's storage location at creation
time, and no longer has a concept of "storage conditions." Update the API
accordingly.
> SW-1559 Update storage location handling in v2 API

- src/main/kotlin/com/terraformation/backend/search/SearchService.kt
- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionCollectorsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/BagsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/CountriesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/CountrySubdivisionsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/GeolocationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationUsersTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/SpeciesProblemsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/SpeciesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/StorageLocationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/UsersTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestResultsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/WithdrawalsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/api/ValuesControllerTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
`/api/v1/seedbank/values/all` has a concept of a "search scope" where we limit
results to the ones relevant to a particular organization or facility. The scope
was being honored for searches on the accessions table, but not for searches on
other tables. So if you asked for, e.g., all the values of `bags_number` for a
given facility ID, you'd actually get all the bag numbers across all the
facilities you had access to.
Eventually we're going to want to revamp how that endpoint works (SW-552) but
in the meantime, the API ought to work as advertised.
> SW-1561 Honor search scopes on all tables

- scripts/client.py
- scripts/create_accessions.py
Update the test script that creates random accessions so it can optionally do so
using the v2 API endpoints. This allows a limited form of fuzz testing of the v2
API: it doesn't check for correctness but can detect if the request handler bombs
out on what ought to be valid input.
> Update create_accessions.py to send v2 requests

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Don't bomb out when converting a v1 weight-based accession without subset
weight/count but with a viability test that specifies the withdrawal quantity
as a seed count.
> SW-1537 Compute v2 viability test quantities

- src/main/kotlin/com/terraformation/backend/seedbank/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Check that a newly-added withdrawal wouldn't cause the accession's remaining
quantity to drop below zero.
> SW-1537 Detect v2 withdrawals of too many seeds

- scripts/client.py
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Add a set of endpoints under `/api/v1/seedbank/accessions/{id}/viabilityTests` to
read and write viability tests. These work the same way as the withdrawals
endpoints: they return the entire accession.
Remove the `viabilityTests` field from the v2 accession PUT payload; the new
endpoints are the only way to write viability tests in the v2 API.
The v2 accession GET response payload no longer has the fields related to the
v1-style viability percentage calculations, since they don't make sense in the
context of v2-style tests:
* `latestViabilityPercent`
* `latestViabilityTestDate`
* `totalViabilityPercent`
A future change will add a new field to hold the user-supplied viability
percentage.
> SW-1566 Add viability test endpoints

- .github/workflows/scripts.yml
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Add a read/write field for the accession's viability percentage. This may be
edited by the user or autofilled on the client side based on test results.
v1 interoperability note: This is a calculated field (`totalViabilityPercent`)
in the v1 API.  If you do a v1 PUT, any user-edited value from a previous v2
PUT will be overwritten. A v1 GET will always return the calculated value.
> SW-1574 Add viability percent to v2 accession API

- .github/workflows/scripts.yml
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
We use PUT, not POST, as the verb for updating objects; the update endpoint for
viability tests incorrectly used POST.
> SW-1566 Update viability tests with PUT, not POST

- .github/workflows/scripts.yml
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/PhotoMetadata.kt
- src/main/resources/db/migration/V126__PhotosMetadataNullable.sql
- src/test/kotlin/com/terraformation/backend/file/ThumbnailStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
We're not using or displaying the captured times or GPS coordinates of individual
photos, so there is no need to make clients include them in upload requests.
This change stops reading and writing the database columns that hold those values;
part 2 will drop them.
> SW-1575 Remove photo metadata from API 1/2

- .github/workflows/scripts.yml
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/PhotoMetadata.kt
- src/main/resources/db/migration/V126__PhotosMetadataNullable.sql
- src/main/resources/db/migration/V127__DropPhotosMetadata.sql
- src/test/kotlin/com/terraformation/backend/file/ThumbnailStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Drop a bunch of metadata columns from the photos table, both the ones that were
removed from the API in part 1 of this series and some others that were part of
our original data model design but never ended up being used.
> SW-1575 Remove photo metadata from API 2/2

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
In the v1 logic for count-based accessions, the remaining quantity is derived from
the initial (total) quantity and the quantities of all the withdrawals, and it has
to add up to zero or more. In the v2 logic, since the user can reset the remaining
quantity at will, the withdrawal quantities can add up to more than the initial
quantity. Previously, that situation would cause an `IllegalArgumentException`
in v2->v1 conversion because the calculated remaining quantity would be negative.
Fix it by recalculating the "initial" quantity in v2->v1 conversion so the numbers
all match up.
Weight-based accessions don't need this fix because the remaining quantity is user
input rather than a calculated value in v1.
> SW-1571 v2->v1: Recalculate "initial" quantity

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/SeedQuantity.kt
- src/main/resources/db/migration/V128__AccessionsEstimatedWeight.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
In the v2 web app, we need to be able to show the estimated seed count for
weight-based accessions as well as the estimated weight for count-based ones,
assuming the user has entered subset measurements.
We already calculate the estimated seed count in v1, but it's based on the initial
quantity, which is going away as a concept in v2.
Add estimated weight to the v2 accession GET payload and the search API, and
update the estimated count calculation to use the remaining quantity on v2.
For consistency with the subset count and weight values, rename
`estimatedSeedCount` to `estimatedCount` in the accession payload, and make
`estimatedCount` available as a search field; the existing search field is called
`estimatedSeedsIncoming` which will no longer be true in v2 once the estimate is
based …
> SW-1537 Calculate estimated weight of accession

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/SeedQuantity.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/main/resources/db/migration/V128__AccessionsEstimatedWeight.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
The `initialQuantity` and `processingMethod` fields are meaningless in v2 and
shouldn't be included in the v2 accession payload.
> Remove v1-only fields from v2 accession payload

- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
The v2 viability test POST and PUT endpoints didn't implicitly upgrade an
accesssion to the v2 quantity-tracking model, which caused them to fail with a
validation error if you tried to create a viability test on a weight-based
accession that was most recently written with the v1 API.
> Fix v1 compatibility in viability test API

- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
The v2 viability test POST and PUT endpoints still used the v1 name `seedsSown`
rather than the v2 name `seedsTested` for the field containing the number of seeds
tested.
> Fix field name in viability test API

- scripts/client.py
If an HTTP request fails, the server usually returns an error message. Use it as
the exception message rather than the default one from the requests library, which
just says what the HTTP response code was.
Before:
$ echo '{"state":"xxxxx"}' | ./edit_accession.py -V 2 --bearer $BEARER 120
[... stack trace ...]
requests.exceptions.HTTPError: 400 Client Error:  for url: http://localhost:8080/api/v2/seedbank/accessions/120
After:
$ echo '{"state":"xxxxx"}' | ./edit_accession.py -V 2 --bearer $BEARER 120
[... stack trace ...]
requests.exceptions.HTTPError: Field value invalid: state
> Test client: Pull error message from server response

- scripts/client.py
- scripts/create_accessions.py
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
In v2, we are expanding the list of viability test treatments and changing the
substrates so that there are different lists of valid values depending on test
type. Most of the existing substrate values are also being renamed, e.g., "Agar
Petri Dish" is now "Agar."
Update the underlying data model so it uses the v2 values. Continue to accept
and return the existing values from the v1 accessions endpoints.
In cases where there is no unambiguous mapping between v1 and v2 treatments,
we remove the value rather than defaulting to a possibly-incorrect default.
The search API returns the v2 values; this doesn't break the existing search
frontend code since it already asks the server for the list of possible values.
But it does potentially cause search results to be different than before.
> SW-1596 Substrates and treatments for v2 viability tests

- src/main/kotlin/com/terraformation/backend/auth/SecurityConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/VersionsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/AppVersionStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/resources/db/migration/R__AppVersions.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V129__AppVersions.sql
- src/main/resources/templates/admin/appVersions.html
- src/main/resources/templates/admin/index.html
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
To support forced updates of mobile apps if we make breaking API changes, as
well as notifying users when there significant new versions of mobile apps are
released, add an API endpoint that returns a list of our apps with a minimum
and recommended version number for each.
The list of app versions is maintained in a new repeatable database migration
so we can ensure it matches the server code as we update the API. But having to
update server-side database migrations would be annoying during mobile app
development, so the list is also editable in the admin UI for super-admin users.
Edits made in the admin UI are overwritten when the migration script is updated.
> SW-1600 Keep track of minimum mobile app versions

- src/main/kotlin/com/terraformation/backend/auth/SecurityConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/VersionsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/AppVersionStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/R__AppVersions.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V129__AppVersions.sql
- src/main/resources/templates/admin/appVersions.html
- src/main/resources/templates/admin/index.html
- src/test/kotlin/com/terraformation/backend/MockUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
Previously, there were two places in the code where we concatenated users'
first and last names to construct full names. Move the logic to a single place
which should make it easier to update when it comes time to add localization.
> Move full name concatenation to IndividualUser

- src/main/kotlin/com/terraformation/backend/customer/OrganizationService.kt
- src/main/kotlin/com/terraformation/backend/customer/db/NotificationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/event/UserDeletedEvent.kt
- src/main/kotlin/com/terraformation/backend/customer/event/UserDeletionStartedEvent.kt
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/NotificationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
The event class name implies the user has already been deleted, but the
event really means we're _about to start_ deleting the user. Rename it
to make this more self-evident.
> Rename UserDeletedEvent for clarity

- src/main/kotlin/com/terraformation/backend/customer/OrganizationService.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/event/OrganizationDeletionStartedEvent.kt
- src/main/kotlin/com/terraformation/backend/file/UploadService.kt
- src/main/kotlin/com/terraformation/backend/file/UploadStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/main/resources/db/migration/V132__OrganizationsCascadeDeletes.sql
- src/main/resources/db/migration/V133__ValidateTimeseriesValues.sql
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/file/UploadServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
When the last user is removed from an organization, delete its data.
Currently, a connected device manager counts as a user; if the organization has a
facility with a connected device manager, its data will not be removed from the
system when the last human user is removed.
Deployment note: The second database migration may take a while to run on the
production database, which may cause the deploy to look like it has gotten stuck.
> SW-931 Purge data when organization is deleted

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/api/ValuesControllerTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
Reduce uninteresting boilerplate in tests by introducing a helper method to insert
accessions with reasonable defaults, similar to the other insert-a-value helpers.
> Add test helper method to insert accession

- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
To handle the case where a user is entering details about a test that has
already happened, allow test results to be included when initially creating
a viability test in the v2 API.
> SW-1694 Accept viability test results when creating test

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
Keep the fields in alphabetical order so it's easier to know where to add new
ones.
No behavior change here, just a change in argument order and adding argument
names, both of which were done using IntelliJ refactoring commands.
> Alphabetize withdrawal and viability test models

- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
With the addition of cut tests, not all viability tests involve seeds germinating.
Rename the field that holds the viability percentage accordingly.
The v1 API is unchanged here, but the field is renamed in the v2 API. This is a
server-calculated field, so only the response payloads are affected. A new search
field with the revised name is also added.
> Rename totalPercentGerminated to viabilityPercent

- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/db/migration/V134__ViabilityTestsCut.sql
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
Change the internal representation of cut test results to the v2 style, where they
are represented as another kind of viability test. This new representation is used
even when accessions are written using the v1 API, but the v1 API continues to
present cut test results as a set of accession-level fields.
Existing cut test results are converted to viability tests by a database migration.
Clients can switch back and forth between the v1 and v2 APIs, but if an accession
has multiple cut tests (which is allowed in v2) they will be collapsed to a single
aggregate test when the accession is written using the v1 API.
The interaction between cut test results and accession quantity is a little
different than before: previously, we would only subtract seeds from the accession
if all three fields …
> SW-1577 Add cut test support to v2 API

- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
In v2, we don't allow users to create viability tests without saying how many
seeds they're testing. Enforce that requirement in the API.
The generated OpenAPI schema was not including the list of required fields in
the viability test payloads; this seems to be due to a bug in the OpenAPI library
that causes it to ignore the `required` attribute on write-only fields. Remove
the annotation that marked the POST and PUT payloads as write-only; it's more
important to have fields correctly marked as required.
> Make "seeds tested" required in v2 viability tests

- src/main/kotlin/com/terraformation/backend/file/UploadStore.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesImporterTest.kt
Accession CSV import also implicitly imports species, and we want to have the same
semantics (following renames, undeleting deleted species) we do with species list
CSV importing.
Move the "import a row from the CSV" function out of `SpeciesImporter` and into
`SpeciesStore` where the accession importer can call it.
Similarly, the accession importer will need to update the status of the uploaded
file and sanity-check its current status; move those helper functions out of
`SpeciesImporter` and into `UploadStore`.
No behavior changes here, just code shuffling. Existing tests continue to pass
as-is aside from needing to pass in a different set of dependencies.
> Refactor species CSV import code

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
`AccessionModel.latestObservedQuantity` is supposed to reflect the most recent
remaining quantity that was specifically entered by the user. But because our
API is based on a CRUD model where the client always submits a "remaining
quantity" value whenever any accession field is updated, and the field can also
be updated by withdrawals and viability tests without the user explicitly editing
it, we need to infer manual edits by checking whether the value matches the one
that was previously written to the database.
This inference can fail if the following sequence happens:
1. Read the existing model from the database.
2. Make a change that should affect the remaining quantity, such as adding or
removing a withdrawal.
3. Call `withCalculatedValues` to compare the newly-modified model against …
> SW-1723 Fix v2 withdrawal double-counting bug

- src/main/kotlin/com/terraformation/backend/seedbank/api/ViabilityTestsController.kt
Since different kinds of viability tests can have wildly varying behavior,
it doesn't make sense to update the type of an existing test. Turn test type
into a create-only field.
> SW-1729 Don't allow editing viability test types

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
Record changes to accessions' remaining quantities, both observed and calculated,
in the `accession_quantity_history` table, and include the observed changes in
the list of history entries returned by `/api/v1/accessions/{id}/history`.
> SW-1715 Include quantity observations in accession history

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
The wording of the notification didn't match the product spec.
> Update body of drying notification

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/FacilityModel.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
Allow clients to create (and edit) nursery facilities using the existing
`/api/v1/facilities` endpoints.
Disallow creating accessions at a nursery facility.
> SW-1731 Add Nursery as a facility type

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/WithdrawalModelTest.kt
In v1, viability tests and withdrawals have a "Staff Responsible" field which is
an arbitrary text value. In v2, we've replaced that field with a Terraware user
ID. But we don't want to lose any text the users entered into the field in v1,
so add it to the "Notes" field.
If the "Notes" field already contains the text of the "Staff Responsible" field,
we don't modify it; this prevents us from adding it multiple times if an accession
repeatedly flips between v1 and v2 writes.
> SW-1732 Preserve staff responsible in v2 API

- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
Some of the test cases in `AccessionModelTest` were testing behavior of
`ViabilityTestModel` that didn't depend on any data in the accession. Move them to
`ViabilityTestModelTest`.
> Move unit tests to ViabilityTestModelTest

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/AccessionModelTest.kt
The user is supposed to be able to change an accession from Used Up to some other
state if they set the remaining quantity at the same time, but the server wasn't
accepting the state change.
> SW-1797 Allow moving out of Used Up if remaining quantity is set

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionCsvValidator.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/resources/seedbank/accession/HappyPath.csv
- src/test/resources/seedbank/accession/HeaderRows.csv
The CSV importer was based on an early draft of the CSV template where the
instructions were on a separate row from the column names, but the final template
includes the instructions and column names in a single row, followed by a blank
row. Users might fill in values in the blank row, or they might not; handle either
situation by only skipping the first (header) row and ignoring blank rows
elsewhere in the file.
> SW-1803 Parse updated accession CSV template

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionCsvValidator.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
In the template CSV we don't specify that the user has to feed us valid ISO
country codes in upper case, and requiring users to do that would be needlessly
annoying. Update the CSV importer to accept country names and lower-case country
codes, and add a validation check to detect unrecognized countries.
> SW-1803 Map accession CSV country names to codes

- src/main/kotlin/com/terraformation/backend/Application.kt
By default, when Spring registers a class as a bean due to the presence of an
annotation, it uses the unqualified class name as the bean name. We don't refer
to beans by name in our code, just by class, but internally Spring requires
each bean to have a unique name.
The default naming strategy is going to cause collisions once we have multiple
database tables with the same name in different schemas, because each table gets
a DAO class that is annotated as a Spring bean, e.g., we'll have two separate
`WithdrawalsDao` classes in different packages.
Tell Spring to base its default bean names on fully-qualified class names instead.
> Use fully qualified class names for Spring beans

- src/main/kotlin/com/terraformation/backend/db/IdentifierGenerator.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
We're going to need to allocate user-facing identifiers from the same pool of
values for accessions and seedling batches, as well as change them so they're
scoped per organization rather than globally.
This first step is to decouple the generation of these identifiers from the
seedbank code.
No change in functionality here, just moving the logic out of `AccessionStore`.
> SW-1845 Refactor accession number generation

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchStoreTest.kt
Add the `GET /api/v1/nursery/batches/{id}` endpoint to retrieve a batch's data.
> SW-1895 Add endpoint to read seedling batches

- .github/workflows/docs.yaml
- .github/workflows/main.yml
- .gitignore
- docker/docker-compose.yml
- gradle.properties
The postgis version specified for tests and github is inconsistent.
It should be `postgis:13-3.0` to match what is used for staging/prod
deployment in RDS. Also add `.DS_Store` files to `.gitignore`.
> Use a Consistent Postgis Version

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/BatchesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/FacilitiesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationsTable.kt
- src/main/resources/db/migration/V141__NurseryBatchSummaries.sql
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
Allow clients to include the total quantity withdrawn as a search field when
searching for seedling batches. This is needed for the list of batches on the
Inventory Details page in the nursery UI.
> SW-1946 Add total withdrawals to batch search table

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
If a withdrawal's quantity is larger than the accession's remaining quantity,
return the exact error message for that situation from the product requirements
rather than a less-precise one about negative quantities.
> SW-1962 More precise error message for withdrawals

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
- src/main/kotlin/com/terraformation/backend/api/ControllerExceptionHandler.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchStoreTest.kt
`PUT /api/v1/nursery/batches/{id}/quantities` will update the seedling quantities
of an existing batch.
This endpoint introduces a new pattern to the API: optimistic locking using
versions. This will help us manage data consistency when multiple users are
working with the same batch. The client must pass in a version number and the
version number must match the current version of the batch. If the versions
don't match, it means some other client updated the batch already, and the
server returns HTTP 412.
Example flow to demonstrate how it works:
1. Batch 123 has a version number of 9
2. Client A: `GET /api/v1/nursery/batches/123` (returns version 9)
3. Client B: `GET /api/v1/nursery/batches/123` (returns version 9)
4. Client A: `PUT /api/v1/nursery/batches/123/quantities` with version=9 …
> SW-1966 Add endpoint to update batch quantities

- src/main/resources/db/migration/R__Comments.sql
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
Configure our schema docs generator to cover the nursery tables.
Document all the columns of all the nursery tables (aside from enums) so we can
use the generated documentation as the source of truth rather than using a
possibly-out-of-date Confluence page.
> Add schema documentation for nursery tables

- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- Modify the canUpdateAccession method to deny for Contributor
- Note that canDeleteAccession is the same as canUpdateAccession
- Modify PermissionTest to reflect new permissions
> SW-1163 Remove Update and Delete Permission from Contributor

- src/main/resources/csv/accessions-template.csv
- src/test/resources/seedbank/accession/HappyPath.csv
- src/test/resources/seedbank/accession/HeaderRows.csv
The previous version of the template incorrectly told users to use `Count`
rather than `Seeds` as the unit name for non-weight-based accessions.
> SW-1969 Fix unit name in accession CSV template

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V142__NurseryBatchDeletion.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreDeleteBatchTest.kt
`DELETE /api/v1/nursery/batches/{id}` will delete a batch from the system.
The ability to delete a batch means we have to relax some of our constraints.
For example, it becomes possible for there to be a nursery transfer withdrawal
where the destination batch no longer exists; we still want the withdrawal to
exist on the originating side.
> SW-1970 Add endpoint to delete seedling batches

- buildSrc/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/WithdrawalModel.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V142__NurseryBatchDeletion.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreDeleteBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
`POST /api/v1/nursery/withdrawals` will withdraw from one or more batches at a
facility. If the withdrawal date is on or after the date (in UTC time zone) the
user most recently edited the batch's remaining quantities, the withdrawal
quantities will be subtracted from the batch.
Withdrawals that change batches' quantities will cause quantity history records
to be created. There is currently no API to query the history of a batch.
This initial version does not support nursery transfer withdrawals; those will
come in a followup revision.
> SW-1967 Add endpoint to withdraw from seedling batches

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
Add support for the `Nursery Transfer` withdrawal purpose, which will cause the
system to create new batches at a destination nursery facility.
> SW-1968 Implement nursery transfer withdrawals

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceGramsSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNullValueTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRangeSearchTest.kt
In preparation for removing the requirement that accession numbers be globally
unique, update various tests that use accession numbers as unique lookup keys.
No application behavior change here. Replaces `AccessionsDao.fetchOneByNumber`
calls with `AccessionsDao.fetchOneById`.
> SW-1845 Stop fetching accessions by number in tests

- src/main/kotlin/com/terraformation/backend/db/IdentifierGenerator.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V144__IdentifierSequences.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/IdentifierGeneratorTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
Previously, accession numbers were globally unique, which was fine because we were
generating them on the server side. But now we allow users to upload CSV files
with their own arbitrary accession numbers, and we don't want one organization to
be able to make an accession number unavailable to another one.
Change the database constraint so that accession numbers are only required to be
unique per facility, and change the number generation so that we generate numbers
per organization rather than globally. Note the difference between the constraint
(per-facility uniqueness) and the default (per-organization uniqueness) -- we
think the latter is a good idea, but if people are uploading their own inventory
spreadsheets, they might use the same numbering scheme at two seed banks and we
don't …
> SW-1845 Revamp accession and batch number generation

- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/TransfersController.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
`POST /api/v2/seedbank/accessions/{id}/transfers/nursery` will withdraw seeds from
an accession and create a new seedling batch.
> SW-1971 Add endpoint to transfer seeds to nursery

- src/main/kotlin/com/terraformation/backend/db/IdentifierGenerator.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/V145__IdentifierSequencesPerPrefix.sql
- src/test/kotlin/com/terraformation/backend/db/IdentifierGeneratorTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreCreateBatchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
After getting feedback about the previous accession/batch numbering scheme,
we want to change two things: make the identifiers shorter and allow people
to visually differentiate between accession numbers and batch numbers.
This new format is 3 characters shorter and treats accessions and batches
as separate sequential number spaces: an accession number in the old format
looked like `20221012888` and in the new scheme it would be `22-1-888` where
the `1` indicates that it's an accession number.
> SW-1986 Generate shorter accession/batch numbers

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
The Kotlin code generator in jOOQ 3.17 added a new way to do implicit joins.
Previously, implicit joins were done using method calls. But now they can also
be done using property references.
It only saves two characters, but may as well use the more compact syntax.
> SW-1488 Use property accessors for jOOQ implicit joins

- src/main/kotlin/com/terraformation/backend/daily/JobRunrRecoveryThread.kt
If there's a database problem, JobRunr shuts down its background worker thread to
cut down on log spew. But it doesn't restart the thread when the database comes
back. This causes the server's health check to report unhealthy status even though
request handling is working fine.
Add a watchdog thread to start JobRunr back up again after the database becomes
available.
> SW-2006 Restart JobRunr after database recovery

- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
If species 1 and 2 exist, and species 2 has an incorrect name (misspelled or
synonym) that should be changed to the same name as species 1, return HTTP 409
(Conflict) with a descriptive error message rather than an internal server error
when the user tries to accept the suggested edit.
Eventually we'll most likely want to add logic to merge the two species, but
until then, we should at least show a meaningful error message.
> SW-1603 Detect collision of suggested species name

- src/main/resources/db/migration/V146__BackfillEstimatedWeight.sql
The v2 accessions code introduced an "estimated weight" value. This value is
calculated in both the v1 and v2 code paths, but we never backfilled it for
existing weight-based v1 accessions. These accessions are thus showing up without
estimated weights in the accession search UI.
> SW-2019 Backfill estimated accession weights

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCheckInTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelConversionsTest.kt
With the removal of the v1 API endpoints, there is no longer any way for a client
to ask the server to convert a v2-style accession to v1-style. Remove the
conversion code and its associated tests.
The v1->v2 conversion code is unaffected here; we'll continue to need it until all
existing accessions have been converted to v2.
> SW-1939 Remove accession v2->v1 conversion code

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/resources/db/migration/V147__BackfillEstimatedQuantity.sql
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/resources/seedbank/accession/HappyPath.csv
In cases where an accession's quantity was known at creation time, e.g., when
importing from a CSV file, we weren't populating the estimated count/weight.
This was a holdover from the v1 world where quantity could only be set as a
processing step after the accession was initially created.
Start populating the missing values, and update the CSV importer test to
verify the desired behavior. Backfill the values where they're currently missing.
> SW-2019 Populate estimated quantities at creation time

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
In v1, we didn't allow users to edit the collected or received dates of accessions
that were created by the seed collector mobile app, but now we want those dates to
be editable.
> SW-1990 Allow editing collected and received dates

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCheckInTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
In v1, checking an accession in created a state history entry with a reason of,
"Accession has been checked in." But that was lost in v2 and instead the message
was, "Accession has been edited."
Add a rule to the v2 state transition calculation, analogous to the one in the v1
code, that uses a different message in the specific case of the state changing
from Awaiting Check-In to Awaiting Processing, which is the transition that's
generated when you click the "Check In" button in the web app.
> Record correct reason when checking in v2 accession

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/device/api/TimeseriesController.kt
- src/main/kotlin/com/terraformation/backend/search/api/SearchController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/TransfersController.kt
Our OpenAPI customization class has code to work around a limitation of the
Swagger core library's annotation processing that causes it to throw away payload
field descriptions if the fields are references to other payload classes.
Previously, the workaround required keeping an explicit list of all the payload
classes that needed to be fixed up. The list was, inevitably, out of date and
missing several classes that ought to have been included.
Switch to a classpath-scanning approach where we probe the code base using
reflection and find all the payload classes. This is slower but it's a one-time
operation that only happens the first time someone requests the OpenAPI schema
from a server instance.
In addition, we were using the wrong annotations on some of the payload fields
whose values …
> Add missing descriptions to OpenAPI schema fields

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreMultiFacilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStorePermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreSummaryTest.kt
In the older version of the web app, we used to show the total number of active
accessions in a facility or organization, but now we break the counts down by
status. Remove the code that calculated the old total. It was only referenced by
tests; the endpoint that used to call it was removed in a previous change.
> SW-1939 Remove unused accession summary calculation

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
In some cases, the remaining quantity on weight-based accessions was not being
updated after withdrawals were added or viability tests were edited. Add test
cases for the specific examples we've encountered, and change the code to fix
them.
> SW-2026 Update remaining weight after withdrawal

- src/main/kotlin/com/terraformation/backend/search/table/BatchesTable.kt
- src/main/resources/db/migration/V149__NurseryBatchSummariesVersion.sql
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
The search API was missing the seedling batch `version` field; add it.
> SW-1875 Add batch version to search API

- src/main/kotlin/com/terraformation/backend/search/table/BatchesTable.kt
- src/main/resources/db/migration/V149__NurseryBatchSummariesVersion.sql
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/device/balena/LiveBalenaClientTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServicePermissionTest.kt
In a few places in the test suite, we were using qualified names for the various
assertion methods rather than statically importing them. That is, we sometimes
had `Assertions.assertEquals` instead of `assertEquals`.
> Add imports for JUnit assertion methods

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
When doing a nursery transfer, the user needs to be able to set the estimated
ready-by date on the newly-created batches, but there wasn't a way to pass it in.
> SW-1885 Add readyByDate to nursery withdrawals

- scripts/client.py
- scripts/requirements.txt
Previously, to run the test scripts, you had to manually get a valid session
cookie or access token and pass it as an argument. Add support for refresh
tokens: you can set a refresh token in an environment variable or pass it as
a command-line argument and the scripts will use it to fetch a new access
token as needed.
This is mostly useful for manual ad-hoc testing at the moment, but moves us a
little closer to being able to use these test scripts for end-to-end automated
tests.
> SW-673 Add refresh token support to test scripts

- src/main/kotlin/com/terraformation/backend/search/SearchFilter.kt
- src/main/kotlin/com/terraformation/backend/search/SearchService.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNullValueTest.kt
We want users to be able to type nonexistent accession numbers into the accession
list UI and get back close matches. But we also want users to be able to paste
exact accession numbers into the same search field and not have the results
cluttered with accessions they didn't search for.
Try to thread this needle by making the fuzzy search code start off by trying an
exact search. If that finds matches, then we're probably in the "user entered an
exact value" situation; return those results. Otherwise do the fuzzy search and
return approximate matches.
This change means there is no way for a user to do a fuzzy search for a value that
also happens to be an exact match; we believe that will still be an improvement
over the current behavior.
> SW-1842 Only do fuzzy matching if there are no exact matches

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/species/SpeciesService.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreManualStateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/species/SpeciesServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
In the v1 accessions API, clients could pass in a species name as part of the
accession data and the system would automatically add the species to the
organization's species list if it didn't already exist. In v2, clients have to
pass in the ID of an existing species.
Remove the code that supported species auto-creation.
> SW-1939 Remove implicit species creation

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/kotlin/com/terraformation/backend/species/SpeciesService.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreManualStateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/species/SpeciesServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
In v1, we calculated an overall viability percentage by aggregating the results of
all the viability tests, but in v2 the viability percentage is user-selectable.
Remove the code that calculates the v1 values, and the `AccessionModel` fields
that held the v1-only values.
> SW-1939 Remove accession-level viability calculations

- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionSummaryStatistics.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/AccessionServiceSearchSummaryTest.kt
Commit ee97dd57 updated the search code so that if you do a fuzzy search, it first
looks for exact matches and returns those if there are any. This had the desired
effect of letting people type exact accession numbers into the accession search
UI, but the summary statistics were still based on the fuzzy matches.
Update the summary endpoint so it uses the same "try an exact search first, and
fall back to fuzzy if that doesn't return results" logic so the summary stats will
match the detailed search results.
> SW-1842 Exact-then-fuzzy logic for search summaries

- src/main/kotlin/com/terraformation/backend/importer/CsvImporter.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchImporter.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
Commit 508c1f9f refactored the CSV upload code to extract common logic into a
superclass. Unfortunately, the refactor caused JobRunr to be unable to detect
which importer was enqueuing the asynchronous jobs to validate and import the
files.
Fix it by enqueuing the jobs explicitly from each subclass.
> SW-1951 Fix CSV upload job scheduling

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
In v1, the results of cut tests were accession-level values. In v2, cut tests are
represented as a kind of viability test that can exist alongside other tests.
Remove the accession-level fields from `AccessionModel` along with the code that
operated on them.
> SW-1939 Remove support for v1 cut test results

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelValidationRulesTest.kt
In v1, we had a validation rule to ensure that the user-supplied total accession
quantity wasn't negative or zero.
In v2, we want to allow the user-supplied remaining quantity to be zero, but it
should never be negative. Add a validation check in the `AccessionModel`
constructor to ensure we can never have a model with a negative remaining quantity.
> Add missing valdation rule for negative quantities

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelValidationRulesTest.kt
Since there are no more v1 accessions, there is no more need to validate them.
This change continues to check the `isManualState` flag to control whether or not
the v2 validation logic is executed. That's to support some unit tests that
haven't been converted to v2 yet and would fail the v2 validation checks. A
subsequent change will update those tests and remove the `isManualState` check.
Most of the tests of v1-only validation logic were removed in PR #728.
> SW-1939 Remove v1 model validation logic

- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/db/migration/V150__DropViabilityTestsRemaining.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/api/ValuesControllerTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/ViabilityTestModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelCalculationsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelValidationRulesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchAllValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
In v1, we required users to enter the remaining quantity when they were
creating a viability test for a weight-based accession. Since it was user input,
we had to persist it to the database.
In v2, we require subset weight/count to be specified for weight-based accessions
in order to create viability tests, so we're always able to compute the remaining
quantity.
Drop the database columns and model field that held the v1-style value.
> SW-1939 Remove viability test remaining quantity

- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelCalculationsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelValidationRulesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
Most of the tests for `AccessionModel` use a helper method to construct a model
object. Previously, the method returned a v1 model and the tests had to explicitly
copy it to convert it to v2. Update the helper to return a v2 model, and remove
a few test methods that aren't meaningful with v2 models.
> SW-1939 Remove v1 support from AccessionModel tests

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceAgeFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
Stop treating v1-only accession states as valid values in the accessions API.
We can't delete the v1-only states from the `accession_states` table because
they are referenced in `accession_state_history` and those historical records
are still valid. But we no longer want them to be available as possible values
for the current state of an accession.
> SW-1939 Remove v1-only accession states from API

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Define permissions for access to planting site data. This follows the same
model as facilities: readable by everyone in the organization, modifiable by
admins and owners.
> Add permissions for planting sites

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
- src/main/kotlin/com/terraformation/backend/db/GeometryUtil.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/TrackingSearchTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Allow clients to read and write planting site information. Client-created planting
sites may not include planting zones or plots, and clients can't edit planting zones
or plots that were created via shapefile upload.
The planting site boundary is always returned from the GET endpoints for planting
sites created via shapefile upload. The list of planting zones and plots is always
included when querying a single planting site, but may be turned on or off when
listing the planting sites for an organization.
All the information available via the GET endpoints here is also available using
the search API, but the dedicated endpoints may be more convenient.
> SW-2105 Add CRUD endpoints for planting sites

- .editorconfig
- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/MapboxController.kt
- src/main/kotlin/com/terraformation/backend/tracking/mapbox/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/mapbox/MapboxService.kt
- src/main/kotlin/com/terraformation/backend/util/HttpClientConfig.kt
The `GET /api/v1/tracking/mapbox/token` endpoint will return a temporary Mapbox
API token that has permission to read map data.
It requires the server to be configured with a Mapbox API token that has the
`token:write` scope, e.g., in an `application.yaml` file:
```
terraware:
mapbox:
api-token: "YOUR_MAPBOX_API_TOKEN"
```
The implementation introduces the Ktor HTTP client library to the code base.
It is a Kotlin-native HTTP client that is a lot more convenient to use than the
Java 11 standard library HTTP client we've used previously. Existing code that
uses the Java client is left untouched here; it can be converted later.
> SW-2179 Add endpoint to get Mapbox API token

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/PlantingSitesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/PlantingZonesTable.kt
- src/main/resources/db/migration/V154__PlantingSiteSummaries.sql
- src/test/kotlin/com/terraformation/backend/tracking/TrackingSearchTest.kt
The UI needs to show the number of planting zones and plots in each planting
site as searchable, sortable table fields. Expose the counts as numeric fields
in the search API.
> SW-2230 Add count fields for planting zones and plots

- src/main/kotlin/com/terraformation/backend/file/PhotoService.kt
- src/main/kotlin/com/terraformation/backend/file/model/PhotoMetadata.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
In preparation for adding photos of nursery withdrawals, extract all the logic
from `PhotoRepository` that isn't specific to accession photos into a new
`PhotoService` class.
No change in functionality here; the existing test cases in `PhotoRepositoryTest`
continue to pass.
> SW-2228 Refactor PhotoRepository

- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/file/PhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
Create a new `PhotoServiceTest` to test the non-accession-related behavior that
has recently been extracted to a new `PhotoService` class.
This allows us to remove some of the test cases from `PhotoRepositoryTest`, though
many of them remain in place because `PhotoRepository` uses filenames rather than
photo IDs and we need to continue to verify its behavior.
But this change should make testing the upcoming nursery withdrawal photo code,
which will use photo IDs natively, significantly simpler.
> SW-2228 Split up PhotoRepositoryTest

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/file/PhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
Reduce the amount of repetition in `IndividualUser` by turning most of the
permission checks into calls to helper methods.
No change in functionality here (existing tests continue to pass as-is).
> Refactor IndividualUser

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
In preparation for adding API endpoints to upload and retrieve photos of nursery
withdrawals, add a couple new permission checks. Nothing actually uses these in
the application code yet.
> SW-2228 Add permissions for withdrawal photos

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoService.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V155__NurseryWithdrawalPhotos.sql
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoServiceTest.kt
Add endpoints to upload, fetch, and list photos of nursery withdrawals:
`POST /api/v1/nursery/withdrawals/{withdrawalId}/photos` uploads a photo,
which is expected to be in a file upload form field called `file`, same as
the existing accession photo upload endpoint. Unlike the accession photo
upload API, though, this endpoint returns a photo ID rather than relying on
the client-supplied filename.
`GET /api/v1/nursery/withdrawals/{withdrawalId}/photos` returns a list of
the photos for the withdrawal. Currently, this is just their photo IDs,
though it's structured to allow for additional data to be added later.
`GET /api/v1/nursery/withdrawals/{withdrawalId}/photos/{photoId}` fetches
a photo. Like the accession photo download endpoint, you can pass optional
`maxWidth` and/or `maxHeight` …
> SW-2228 Support uploading photos of nursery withdrawals

- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/db/migration/V156__SeedbankWithdrawalPurposes.sql
Migrate existing seedbank withdrawals to use the currently-supported set of
withdrawal purposes and remove the old unsupported ones from the data model.
> SW-1415 Replace obsolete withdrawal purposes

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/search/field/GeometryField.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/db/migration/V156__SeedbankWithdrawalPurposes.sql
- src/main/resources/db/migration/V157__PlantingSitesSrid.sql
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
The default coordinate reference system (CRS) for GeoJSON objects is EPSG:4326,
which uses degrees of latitude and longitude. ArcGIS uses a spherical Mercator
coordinate system (EPSG:3857) by default, and we were returning geometry values
in that system which isn't usually what clients need.
Make two changes to the way we handle coordinates:
* Store coordinates in whatever coordinate reference system was used in the
shapefiles we're importing.
* At read time, transform to EPSG:4326. (In the future, we might allow the client
to ask for a different CRS.)
> SW-2239 Use consistent CRS for planting sites

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
This was a backward-compatibility alias for `collectionSiteNotes`. The client has
been updated to use the new name, so the old one is no longer needed.
> SW-1405 Remove collectionNotes accession search field

- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/SeedQuantity.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/SeedQuantityModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelCalculationsTest.kt
When the user creates a nursery transfer or a viability test, the withdrawal
quantity is always denominated in seeds even if the accession is weight-based.
We estimate the withdrawal weight using the subset count and weight, and
subtract that estimated weight from the accession's remaining weight.
This is normally fine, but when the user is trying to withdraw all the
remaining seeds from the accession, the withdrawal ends up either failing (if
the estimated weight ended up being slightly greater than the accession's
remaining weight) or leaving the accession active even though there are no more
seeds in reality (if the estimated weight was slightly less than the
accession's remaining weight).
Add logic to handle this case: if the most recent withdrawal from a
weight-based accession is …
> SW-2225 Ignore fractional remaining seeds after withdrawal

- src/main/kotlin/com/terraformation/backend/seedbank/db/QuantityRepairer.kt
- src/main/resources/db/migration/V158__WithdrawalPurposeFix.sql
Thanks to a combination of bugs in the v1 accession code and problems with the
v1->v2 migration, a handful of accessions ended up with withdrawals whose
quantities add up to more than the latest observed quantity. It's thus impossible
to do anything with the accessions because the quantity recalculation logic always
catches the problem and bails out.
Fix up the existing accessions in three ways:
* Set the correct withdrawal purpose for viability test withdrawals and add a
database constraint to make sure it's always properly set going forward.
* Remove withdrawals that were created after the most recent quantity observation
but don't have associated quantity history entries. These are all duplicates
of withdrawals that _do_ have history entries, and they are causing withdrawal
quantities …
> SW-2225 Clean up inconsistent accession quantities

- .github/workflows/main.yml
Use yaml folded style which is supported by github actions to break long command across multiple lines.
> SW-2288 Fix multiline command in github action yaml

- src/main/kotlin/com/terraformation/backend/file/PhotoService.kt
- src/main/kotlin/com/terraformation/backend/file/SizedInputStream.kt
- src/main/kotlin/com/terraformation/backend/file/ThumbnailStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/file/PhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/file/ThumbnailStoreTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoServiceTest.kt
Add PNG as a supported image format for accession and nursery withdrawal photos.
Thumbnails are still always generated in JPEG format regardless of the format
of the original image.
> SW-2297 Support PNG photo uploads

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Commit ed832885 removed an important part of `PermissionTest`: it no longer tests
that users don't have access to objects in organizations other than their own.
Update the test to start covering those cases again, and fix some bugs in the
tests that were revealed by the new cases.
> SW-2176 Restore coverage to PermissionTest

- src/main/kotlin/com/terraformation/backend/device/api/DeviceController.kt
- src/main/kotlin/com/terraformation/backend/device/api/DeviceTemplatesController.kt
Device settings are arbitrary JSON objects defined by the device manager.
Previously, we were unpacking them because we needed to populate a setting for
backward compatibility with old device manager versions. Now that the device
managers in the field have been updated to not use that setting any more, we
can treat the settings as opaque values and there's no longer any need to
represent them as `Map` objects internally.
In addition to removing unnecessary logic, this is a prerequisite to changing
the JSON deserializer configuration to treat empty strings as null; in the
absence of this change, doing so would have prevented the device manager from
including empty strings as setting values, which would break the "device manager
can put whatever it wants in the settings" API contract.
This …
> SW-2003 Use ArbitraryJsonObject for device settings

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/admin/plantingSite.html
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
To support a workflow where a Terraformation employee creates a new planting site
using a shapefile, verifies it in the web app, then transfers it to the correct
organization, update the admin UI to allow moving planting sites to new
organizations.
This requires the ability to select a planting site in the admin UI; previously
it was only possible to create new sites, not view them.
> SW-2361 Allow super admins to move planting sites

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
The device manager has been updated to use `/api/v1/automations` to get information
about automations; we no longer need the older endpoints under `/api/v1/facilities`,
nor the backward-compatibility code that constructed their payloads.
> SW-1048 Remove automations endpoints from facilities

- src/main/kotlin/com/terraformation/backend/customer/db/AutomationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/AutomationModel.kt
- src/main/kotlin/com/terraformation/backend/device/api/AutomationsController.kt
In preparation for changing the JSON deserialization settings to treat empty
strings as null values, update the automation payloads' settings fields to use
`ArbitraryJsonObject` instead of `Map<String, Any?>`.
Client-visible behavior remains the same as before.
> SW-2003 Use ArbitraryJsonObject for automation settings

- src/main/kotlin/com/terraformation/backend/api/GeoJsonOpenApiSchema.kt
- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/db/AutomationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/AutomationModel.kt
- src/main/kotlin/com/terraformation/backend/device/api/AutomationsController.kt
Remove the explicit list of arbitrary-JSON-object payload fields whose
`additionalProperties` values need to be cleared, in favor of detecting them
dynamically during the scan of all the payload fields we're doing anyway.
Move the GeoJSON schema configuration to a helper function that lives alongside
the schema configuration classes.
There's no change in the intended behavior here, but this does fix the definitions
of a couple of payload fields that weren't being properly adjusted previously.
> Simplify OpenAPI customization

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/device/balena/LiveBalenaClient.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/main/kotlin/com/terraformation/backend/util/HttpClientConfig.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/device/balena/LiveBalenaClientTest.kt
Update the code that makes requests to Balena and Keycloak to use the Ktor HTTP
client instead of the Java 11 one. Remove the helper functions we used to use to
make the Java 11 client's API less cumbersome.
No change in functionality or behavior here.
> SW-2217 Switch from Java 11 HTTP client to Ktor

- src/main/kotlin/com/terraformation/backend/search/SearchFilter.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNullValueTest.kt
Commit fdd126a1 changed the behavior of the search API subtly: previously, you
could do a fuzzy search for an empty string to match all non-null values, but
now those empty strings get converted to null during payload deserialization
and the resulting searches change from matching non-null values to only matching
nulls.
The web app passes in empty-string fuzzy search values when the user hasn't
entered a value to search for. In that scenario, the previous behavior was also
wrong: we'd want to ignore the search criterion entirely and return both null
and non-null values.
Update the search implementation to ignore fuzzy search criteria if one or more
of the values is null (which, thanks to commit fdd126a1, could happen if the
client passed in an empty string).
Searching for non-null values …
> Ignore null fuzzy search values

- src/main/kotlin/com/terraformation/backend/search/SearchFilter.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNullValueTest.kt
The list of search values for a `FieldNode` is annotated `@NotEmpty` in the API
payload class, but the implementation wasn't guarding against empty lists of
field values.
> Don't allow searches with no values

- build.gradle.kts
We're using a Gradle plugin that automatically fires up PostgreSQL in a Docker
container to run our migrations so jOOQ can look at the resulting schema for code
generation. But the plugin seems to have been abandoned; I submitted a simple pull
request over a year ago to fix a compatibility problem and it hasn't been merged
or rejected yet.
Someone forked the project and has been actively maintaining it, and their version
doesn't have the problem my PR was meant to fix. Switch to the fork and update the
build config to account for some minor naming changes the fork's maintainer has
made.
> SW-215 Switch to maintained fork of jOOQ Gradle plugin

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
Nearly all the test cases in PermissionRequirementsTest check for behavior that
follows one of two patterns depending on whether they're checking a write
permission or a read permission. The only things that vary across the read
tests and across the write tests are
* The method under test
* The type of the ID of the permission's target
* The type of the exception that's thrown if the user doesn't have read access
(this is always the same for a given ID type)
* The TerrawareUser method that controls whether or not the user has permission
Use lazy evaluation and extension methods to make a mini-DSL for these tests,
collapsing the vast majority of them to one-liners.
> Reduce boilerplate in PermissionRequirementsTest

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
The generated OpenAPI docs didn't include the response payload for `GET
/api/v1/nursery/withdrawals/{withdrawalId}/photos` because the annotation was
missing on the controller method.
> Add missing response payload to OpenAPI spec

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/device/api/TimeseriesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/MapboxController.kt
- src/test/kotlin/com/terraformation/backend/api/OpenApiAnnotationTest.kt
Several endpoints were missing the necessary annotations to include their HTTP 2xx
response payloads in the generated OpenAPI schema. Add the missing annotations and
add a test that scans all the controller methods and ensures they either
explicitly declare a 2xx response or don't declare any responses at all (in which
case OpenAPI includes HTTP 200 by default).
> Add missing OpenAPI response declarations

- src/main/kotlin/com/terraformation/backend/auth/RequestResponseLoggingFilter.kt
- src/main/kotlin/com/terraformation/backend/auth/SecurityConfig.kt
- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/resources/application-default.yaml
To make it easier to troubleshoot problems we discover during QA testing, add the
ability to log request and response bodies for a subset of users.
> SW-2043 Log request and response payloads

- src/main/kotlin/com/terraformation/backend/search/api/SearchPayloads.kt
The OpenAPI schema for search criteria was incorrect in two respects:
1. It incorrectly mapped the `or` operation to the payload for the `not`
operation.
2. The payload for the `or` operation didn't include the `children` property.
The second item is due to a bug in the OpenAPI schema generator, which is
triggered when two payload classes in the same type hierarchy have an array
property of the same name with identical `@ArraySchema` annotations. Work around
it by making the annotations non-identical.
This didn't affect the web app thanks to the fact that its build process
overwrites the search payload definitions to avoid code generator bugs related to
circular references. But we should still generate correct schema definitions.
> Fix incorrect OpenAPI schema for search payloads

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/NotificationStoreTest.kt
Make enum values prettier when they contain words that start with lower-case
letters.
This only affects the symbols that are used in the code, not the display names
that are exposed to clients via the API.
> Capitalize words of database-generated enums

- .github/workflows/main.yml
- this is to resolve the deprecated Node.js version 12 usage
- use version @v1-node16 (note that there are newer Node versions but this is the only available actions version at this point)
- see note on aws-actions github page https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning
- re: testing, having trouble running `act`, i recall now having tried this a few months back. it downloads a bunch of docker images and spins up a gradle daemon and waits, i need to look into this more later
> SW-2290 Upgrade aws-actions/configure-aws-credentials to use newer Node.js version 16

- src/main/kotlin/com/terraformation/backend/db/Extensions.kt
- src/main/kotlin/com/terraformation/backend/device/api/TimeseriesController.kt
- src/main/kotlin/com/terraformation/backend/device/db/TimeseriesStore.kt
- src/test/kotlin/com/terraformation/backend/device/api/TimeseriesControllerTest.kt
- src/test/kotlin/com/terraformation/backend/device/db/TimeseriesStoreTest.kt
If an incoming timeseries values request has a lot of entries that are already in
the database, detecting the duplicates is currently pretty slow and leads to
request timeouts. Check for duplicates explicitly by querying for all of the
timestamps at once rather than relying on individual INSERT queries failing.
For a request whose values are entirely duplicates, this will result in the
server doing a single SELECT query rather than a ton of failing INSERTs.
> SW-1307 Improve performance of duplicate timeseries values

- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreFetchEstimatedReadyTest.kt
The test was assuming the results of a database query would be returned in a
specific order, but the function under test does not guarantee ordering.
Update the test to ignore what order the results are in.
> Fix failing BatchStore test

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/db/TimeZoneConverter.kt
- src/main/kotlin/com/terraformation/backend/db/TimeZonePopulator.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V165__TimeZones.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/db/TimeZonePopulatorTest.kt
Create a new table to hold the list of valid time zone names, and add code to
keep it in sync with the Java standard library's list of time zones (which is
taken from the IANA time zone database).
No API changes here, just database changes.
> SW-2602 Add time zones to database schema

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/db/TimeZoneConverter.kt
- src/main/kotlin/com/terraformation/backend/db/TimeZonePopulator.kt
- src/main/kotlin/com/terraformation/backend/file/UploadStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/ViabilityTestStore.kt
- src/main/kotlin/com/terraformation/backend/species/db/GbifStore.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/V165__TimeZones.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/db/TimeZonePopulatorTest.kt
Use the new `asNonNullable()` extension function to remove `filterNotNull()` calls
on jOOQ queries that were only there to inform Kotlin that the results were
non-nullable. This is really just for conciseness; there will be a performance
gain from not having to copy the list, but it'll be miniscule.
In a couple places we were doing `fetch().get(FIELD)`; simplify those to
`fetchOne(FIELD)`.
No behavior change here.
> Simplify non-nullable jOOQ queries

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Add `timeZone` fields to the payloads of the `/api/v1/users` endpoints to get and
set per-user time zones.
> SW-2606 Add timeZone fields to user APIs

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/FacilityModel.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/OrganizationModel.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/test/kotlin/com/terraformation/backend/MockUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/FacilityStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Allow time zones to be read and written on organizations, facilities, and planting
sites.
This does not implement any fallback logic: if you pass in a null time zone, the
time zone will be set to null on the object in question.
> SW-2606 Add timeZone fields to org-related APIs

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/FacilityModel.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/OrganizationModel.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/field/ZoneIdField.kt
- src/main/kotlin/com/terraformation/backend/search/table/FacilitiesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/PlantingSitesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/UsersTable.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/db/migration/V166__PlantingSiteSummariesTimeZone.sql
- src/test/kotlin/com/terraformation/backend/MockUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/FacilityStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Allow clients to query the time zones of organizations, facilities, planting
sites, and users.
> SW-2606 Add timeZone fields to search API

- scripts/README.md
- scripts/client.py
- scripts/timeseries.py
Commit 16cf9a08 added support for passing offline refresh tokens to the various
scripts in the `scripts` directory, replacing the old support for bearer tokens.
But `timeseries.py` wasn't updated accordingly. It had an explicit check that
tested for the bearer token command-line argument, which caused it to bomb out.
> Fix timeseries.py

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/testClock.html
When testing time zone support, it is useful to be able to advance the test clock
by increments of less than one day so as to trigger notifications in some time
zones but not others.
Add a units selector to the admin UI's test clock page.
> SW-2634 Allow advancing test clock by minutes or hours

- src/test/kotlin/com/terraformation/backend/species/db/SpeciesImporterTest.kt
`SpeciesImporterTest` had an implicit assumption that unordered database query
results would be returned in a particular order. This caused the test to fail
sporadically.
> Don't rely on result order in SpeciesImporterTest

- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Withdrawal.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreBagTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCheckInTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreHistoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreLocationTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreManualStateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreMultiFacilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStorePermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStorePhotoTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreStateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreWithdrawalTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelCalculationsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelValidationRulesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/model/accession/AccessionModelViabilityTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/AccessionServiceSearchSummaryTest.kt
If the user creates a viability test and doesn't give a start date, the test is
associated with a withdrawal on today's date. Use the seed bank's time zone to
determine what "today's date" is.
Also use the seed bank's time zone when determining whether a manual quantity
adjustment falls before or after a withdrawal date.
To implement these changes, `AccessionModel` now has a required `clock`
property, which replaces the `Clock` arguments that used to need to be passed
to all the calculation methods. The new property is populated with a clock that
uses the seed bank's time zone.
Another option would have been to keep the `Clock` arguments and make sure to
always pass in a clock with the correct time zone. But that would be easier to
screw up: there'd be no good way to ensure a caller could …
> SW-2637 Use seed bank time zone in accession logic

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
The OpenAPI schema's definitions of payload properties that allow arbitrary
JSON objects was inaccurate: it didn't include an `additionalProperties`
attribute to indicate that arbitrary keys and values were allowed.
This doesn't impact our existing client code but if we ever use the schema to
generate client code in statically-typed languages, the generated types would
be wrong.
> Properly mark arbitrary JSON objects in OpenAPI

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/db/LocaleConverter.kt
- src/main/resources/db/migration/V168__UsersLocale.sql
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
Update the `/api/v1/users` payloads to include a `locale` field.
> SW-2771 Add locale to user details

- src/main/kotlin/com/terraformation/backend/api/LocaleConfig.kt
- src/main/kotlin/com/terraformation/backend/i18n/Locales.kt
- src/main/kotlin/com/terraformation/backend/i18n/api/TimeZonesController.kt
Configure Spring's web framework so it sets the current locale based on the value
of the `Accept-Language` header.
Use that header to determine the default locale for `/api/v1/i18n/timeZones`.
> Use Accept-Language header to determine locale

- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/main/kotlin/com/terraformation/backend/i18n/TimeZones.kt
If the locale is `gx, make `/api/v1/i18n/timeZones` return gibberish time zone
names for localization testing.
> Support gibberish time zones

- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/i18n/TimeZones.kt
- src/main/resources/i18n/Messages.properties
The `Messages` class is where we render human-readable text on the server side.
The intent was always that it'd be updated to return text in the user's language.
Move the English strings into a properties file and look them up based on the
current locale. The strings should be the same as before since we only have an
English properties file.
In addition, render the numeric parts of seed quantities using the number
formatter for the user's locale. This doesn't currently support the number
formatting rules for the gibberish locale; it just uses the built-in formatting
rules from the Java standard library.
> SW-2786 Make Messages text localizable

- .github/workflows/main.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderGibberishTask.kt
Add a build step that reads the default-locale properties files from
`src/main/resources/i18n` and produces gibberish versions of them.
For now, `src/main/resources/i18n/Messages.properties` is the only message
bundle; it is transformed to `build/resources/main/i18n/Messages_gx.properties`.
This causes the `Messages` class to support the gibberish locale.
> Generate gibberish translations of English messages

- build.gradle.kts
- docker/Dockerfile
- src/main/kotlin/com/terraformation/backend/Application.kt
- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/main/kotlin/com/terraformation/backend/i18n/TimeZones.kt
- src/main/resources/META-INF/services/java.text.spi.DecimalFormatSymbolsProvider
- src/test/kotlin/com/terraformation/backend/i18n/GibberishDecimalFormatSymbolsProviderTest.kt
To test localized number formats, the spec for the gibberish locale says it should
use ampersands as thousands separators and commas as decimal separators.
Implement a number formatter that uses those characters. Register it with Java's
localization system so call sites don't have to special-case the gibberish locale;
they can just call `NumberFormat` as usual.
Unfortunately, this requires adding a command-line argument to set a system
property when launching the server. Add it to the command line in the Docker image
and to the `generateOpenApiDocs` configuration, and add a check at start time to
tell people to include it in dev environments.
> Implement gibberish number formatting

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchImporter.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionImporter.kt
- src/main/kotlin/com/terraformation/backend/species/SpeciesService.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesChecker.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/species/model/SpeciesModel.kt
- src/test/kotlin/com/terraformation/backend/species/SpeciesServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesCheckerTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
In preparation for adding a per-species list of ecosystem types, introduce a new
model class to represent the data about a species. Update internal APIs to use
these models instead of the generated jOOQ model classes.
No behavior change here; this is just groundwork for the upcoming change.
> SW-2283 Introduce SpeciesModel

- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
If a new user has selected a locale during registration, record it in their
Terraware user information.
> SW-2777 Use selected locale from Keycloak for new users

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/field/LocalizedTextField.kt
- src/main/kotlin/com/terraformation/backend/search/table/CountriesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/CountrySubdivisionsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
Make the search API return localized names for countries and country subdivisions.
The frontend uses the search API to get the list of available countries.
English country names are stored in the database, but they aren't turned into
Kotlin enums at build time, so the existing functionality for returning localized
strings for enum search fields won't work. But we still want to look up localized
names from resource bundles and generate the English and gibberish bundles from
the database, same as we do for enum tables.
To address this, introduce a new search field type, `LocalizedTextField`, that
works roughly the same way as `EnumField` but looks values up in resource bundles
explicitly rather than relying on the helper functions in
`EnumFromReferenceTable`.
> SW-2797 Localize country names

- src/main/kotlin/com/terraformation/backend/db/Extensions.kt
- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/UpperCaseTextField.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
When the user sorts search results by a text field, we need to use the locale's
collation (sorting) rules or the results will potentially be in the wrong order.
PostgreSQL has built-in collation rules for a variety of languages; update the
search code to specify which rules to use for each query.
> SW-2800 Sort text search fields using locale

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
Commit a5055833 added the ability to render enum display names in different
locales, but it erroneously changed the parsing logic such that clients had to
pass localized JSON string values for enum fields in request payloads.  This
violates the OpenAPI schema which specifies that enums are always represented
using their English display names in the API.
The practical effect of this bug is that if you switch locales in the client and
try to call a write endpoint whose payload includes an enum field, you'll get a
serialization error because the server doesn't recognize the English display name.
> Expect canonical enum names in request payloads

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
Uploading an accession photo required permission to update the accession, which
meant that contributor users couldn't upload photos as part of creating new
accessions.
Add a separate permission for accession photo upload, allowing it for everyone
who has permission to read the accession.
> SW-2854 Allow contributors to upload accession photos

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
The query to fetch the next accession ID was missing an ORDER BY clause,
causing it to skip a lot of accessions.
> Fix bug in AccessionStore.forEachAccession

- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/db/migration/R__TypeCodes.sql
Users want to indicate that a viability test didn't use a substrate. Add "None" to
the list of substrate types, valid for both lab and nursery tests.
> SW-2823 Add "None" viability test substrate type

- .editorconfig
- CONVENTIONS.md
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderGibberishTask.kt
- jooq/src/main/kotlin/com/terraformation/backend/jooq/SortedPropertiesFile.kt
- src/main/kotlin/com/terraformation/backend/api/LocaleConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/db/EnumFromReferenceTable.kt
- src/main/kotlin/com/terraformation/backend/db/Extensions.kt
- src/main/kotlin/com/terraformation/backend/email/EmailService.kt
- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/main/kotlin/com/terraformation/backend/i18n/TimeZones.kt
- src/main/kotlin/com/terraformation/backend/importer/CsvImporter.kt
- src/main/kotlin/com/terraformation/backend/search/field/AgeField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DateField.kt
- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LocalizedTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/UpperCaseTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/WeightField.kt
- src/main/kotlin/com/terraformation/backend/search/field/ZoneIdField.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionCsvValidator.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
IntelliJ uses wildcard imports for `java.util` by default, but we want to be
explicit about what we're importing. Expand those wildcard imports.
Update the Kotlin `.editorconfig` section with settings that were added to
IntelliJ after the file was most recently generated.
> SW-2789 Remove wildcard import of java.util

- src/main/kotlin/com/terraformation/backend/species/db/GbifImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/GbifStore.kt
- src/test/kotlin/com/terraformation/backend/species/db/GbifImporterTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/GbifStoreTest.kt
- src/test/resources/species/gbif/VernacularName.tsv
When looking up a species name from the GBIF database, we want to ignore
diacritics like we do for searches of text fields in our search API.
For efficiency, this includes a change to the GBIF import logic: we need to
remove diacritics from the words in the `gbif_name_words` table so they
can be looked up using exact matches on the index on that table.
> SW-1828 Ignore diacritics in species name lookup

- src/main/kotlin/com/terraformation/backend/search/SearchResults.kt
- src/main/kotlin/com/terraformation/backend/search/api/SearchController.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
Commit 07039f0e added the ability to import a species list CSV file with multiple
ecosystem types separated by line breaks.
Allow exporting the species list in the same format.
The actual change here is more general: it removes the nested-fields restriction
on CSV export of search results. Previously, only flattened fields could be
exported because there is no way to represent tree structures in a CSV file.
That's still the case, even though we now allow nested fields to be exported;
if there are multiple levels of nesting, or if the values contain line breaks,
the results will be ambiguous. But for simple "list of enumerated values" cases
like species ecosystem type, there's no ambiguity.
> SW-2904 Support CSV export of nested search fields

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionHistoryModel.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreHistoryTest.kt
Update `GET /api/v1/seedbank/accessions/{id}/history` to include user-entered
withdrawal notes when available.
> SW-2681 Include withdrawal notes in accession history

- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/test/kotlin/com/terraformation/backend/i18n/GibberishDecimalFormatSymbolsProviderTest.kt
- src/test/resources/nursery/Gibberish.csv
- src/test/resources/seedbank/accession/Gibberish.csv
Replace the custom separator characters in gibberish number formatting with the
French ones. This eases implementation on the client side, where it's harder to
define custom locales with custom formatting rules.
> SW-2933 Use French number formatting for gibberish

- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/field/AgeField.kt
- src/main/kotlin/com/terraformation/backend/search/field/AliasField.kt
- src/main/kotlin/com/terraformation/backend/search/field/BigDecimalField.kt
- src/main/kotlin/com/terraformation/backend/search/field/BooleanField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DateField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DoubleField.kt
- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
- src/main/kotlin/com/terraformation/backend/search/field/GeometryField.kt
- src/main/kotlin/com/terraformation/backend/search/field/IdWrapperField.kt
- src/main/kotlin/com/terraformation/backend/search/field/IntegerField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LocalizedTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LongField.kt
- src/main/kotlin/com/terraformation/backend/search/field/NumericSearchField.kt
- src/main/kotlin/com/terraformation/backend/search/field/SearchField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TimestampField.kt
- src/main/kotlin/com/terraformation/backend/search/field/UpperCaseTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/WeightField.kt
- src/main/kotlin/com/terraformation/backend/search/field/ZoneIdField.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionCollectorsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/BatchesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/GeolocationsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceAliasedFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceInitializationTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRawTest.kt
To allow clients to more easily parse specific values in search results, add
support for "raw" variants of fields whose values can vary based on locale.
Specify that you want to use raw values rather than localized ones by
appending the string `(raw)` to the name of a search field. You can use raw
fields both for input (search criteria) and for output (list of fields to return).
These are treated as separate search fields with separate names. It is fully
supported to include both the raw and localized versions of a field in the same
search request, and indeed, that's expected to be a common usage pattern whenever
a client needs to both display a value to a user and use it internally for
business logic.
> SW-2935 Support raw search fields

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/resources/i18n/Messages.properties
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRawTest.kt
The "Active" search field on accessions is a one-off implementation rather than a
normal enum field, so it wasn't covered when `EnumField` gained localization
support. Update it to return localized values and to support a raw variant.
> SW-2939 Localize accession active field

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/FacilityModel.kt
- src/test/kotlin/com/terraformation/backend/customer/db/FacilityStoreTest.kt
To prepare for adding more facility attributes, refactor `FacilityStore.create` to
take its parameters in an object rather than individually.
No functional change.
> SW-2951 Move FacilityStore.create params into class

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoService.kt
- src/main/kotlin/com/terraformation/backend/nursery/event/WithdrawalDeletionStartedEvent.kt
- src/test/kotlin/com/terraformation/backend/nursery/BatchServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchImporterTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreDeleteBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreTest.kt
When you delete a seedling batch that is associated with a withdrawal, and the
withdrawal isn't also associated with other batches, the withdrawal is
automatically deleted as well. This was failing if the withdrawal had photos.
Add logic to delete the photos (including the files in the file store) before
attempting to delete the withdrawal from the database.
> SW-2908 Allow deleting seedling batches with photos

- .github/workflows/docs.yaml
- build.gradle.kts
- docs/index.md
Add the Dokka plugin to generate HTML documentation from our code's
class and method doc blocks. Include the Mermaid module so we can put
diagrams in our docs as well.
> Generate code documentation

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
Always sort the lists of nurseries, seed banks, and planting sites in reports by
their IDs for consistency.
> Deterministic ordering of report facilities/sites

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
- src/main/kotlin/com/terraformation/backend/report/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/report/api/ReportsController.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/kotlin/com/terraformation/backend/report/event/ReportSubmittedEvent.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1.kt
- src/main/kotlin/com/terraformation/backend/report/model/Reports.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
- src/test/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1Test.kt
`POST /api/v1/reports/{id}/submit` will submit an in-progress report. The report
must be locked by the current user.  Submitting a report releases the lock and
prevents the report from being locked or updated in the future.
Submitted reports must include all required fields. If there are missing values,
the API request fails.
In this initial implementation, submitting a report doesn't trigger any actions
other than marking it as submitted. Subsequent changes will introduce more
behavior when a report is submitted.
> SW-2889 Add endpoint to submit reports

- build.gradle.kts
- gradle.properties
Renovate attempted to upgrade it but the resulting configuration failed to
build because a test-only transitive dependency gets overridden to an
incompatible version. Add the latest version of the dependency explicitly.
> Upgrade to geotools 28.2

- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
ReportServiceTest was relying on the report ID sequence being reset, but wasn't
actually resetting it. It was thus passing when run in isolation, but failing if
another report-related test happend to allocate a report ID first.
> Fix order dependency in ReportServiceTest

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
- src/main/kotlin/com/terraformation/backend/api/Extensions.kt
- src/main/kotlin/com/terraformation/backend/file/PhotoTypes.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
In preparation for adding photo endpoints for reports, extract some OpenAPI
annotations and helper functions from the existing accession and seedling
withdrawal controllers.
No change in functionality here, just reduced code duplication.
> Extract common photo endpoint code

- .github/workflows/main.yml
Only transition to "Released to Production" if the status is already "Done"
> SW-2994 Limit Jira transitions during prod release

- src/main/kotlin/com/terraformation/backend/report/ReportPhotoService.kt
- src/main/kotlin/com/terraformation/backend/report/api/ReportsController.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportPhotoModel.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportPhotoServiceTest.kt
Add endpoints to allow uploading and downloading report-related photos. These
endpoints follow the usual pattern for photos in our API (similar to the endpoints
for nursery withdrawal photos) including server-generated thumbnail images.
One difference from nursery withdrawal photos is that report photos need to
support captions; there is a POST endpoint to update a photo's caption, and the
captions are included in the `GET /api/v1/reports/{id}/photos` response.
> SW-2986 Add endpoints to attach photos to reports

- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/OrganizationModel.kt
- src/test/kotlin/com/terraformation/backend/customer/db/InternalTagStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
The client needs to know whether or not an organization is eligible to submit
reports so it can show or hide the reporting-related UI elements. Include a
field in the `GET /api/v1/organizations` payloads to indicate whether or not
the organization is supposed to submit reports.
> SW-2991 Include reporting ability in organization API

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/time/Extensions.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
Q4 reports should always include annual details; update the report creation
logic accordingly.
> Include annual details in Q4 reports

- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/api/PayloadsV1.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
- src/test/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1Test.kt
The report payloads and internal models were missing a couple fields: `notes` on
planting sites and `opportunities` on annual details. Add them.
> Add a couple missing report fields

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/file/model/FileMetadata.kt
- src/main/kotlin/com/terraformation/backend/report/api/ReportsController.kt
- src/main/kotlin/com/terraformation/backend/report/model/Reports.kt
- src/main/kotlin/com/terraformation/backend/report/render/ReportRenderer.kt
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/reports/v1/index.html
In preparation for exporting submitted reports to Google Drive, add logic to
render report data as simple HTML, and allow the rendered reports to be viewed
using the admin UI.
The HTML includes references to photos and files. These are assumed to live in
the same directory as the exported HTML file. The admin UI includes endpoints
that serve the correct contents for those filenames.
> SW-3000 Render reports as barebones HTML

- src/main/kotlin/com/terraformation/backend/customer/FacilityService.kt
- src/test/kotlin/com/terraformation/backend/customer/FacilityServiceTest.kt
When a report is submitted, update the build/operation dates and (for nurseries)
the capacity on the facility if they aren't already set, so they'll be prefilled
when a subsequent report is generated.
> SW-3021 Populate facility details from reports

- src/main/kotlin/com/terraformation/backend/species/db/SpeciesCsvValidator.kt
- src/main/resources/csv/species-template.csv
- src/main/resources/csv/species-template_gx.csv
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesCsvValidatorTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesImporterTest.kt
Include lists of supported enum values and other guidance in the template for
importing species list CSV files.
Previously, per the initial requirements, we were checking for exact matches of
the header column names, but this was causing problems for users, and with the
instructions included, it's now much more likely that people will upload otherwise
valid CSV files where the header row isn't byte-identical to our template. Remove
the strict checking in favor of just checking that the number of columns in the
header row is correct.
Add test cases to ensure that localized templates work as intended.
Also partially addresses SW-3071.
> SW-2388 Add instructions to species CSV template

- src/main/kotlin/com/terraformation/backend/search/SearchFilter.kt
- src/main/kotlin/com/terraformation/backend/search/SearchService.kt
- src/main/kotlin/com/terraformation/backend/search/field/AgeField.kt
- src/main/kotlin/com/terraformation/backend/search/field/BooleanField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DateField.kt
- src/main/kotlin/com/terraformation/backend/search/field/IdWrapperField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LocalizedTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/NumericSearchField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/TimestampField.kt
- src/main/kotlin/com/terraformation/backend/search/field/UpperCaseTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/WeightField.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/AccessionServiceSearchSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
Allow clients to specify whether or not they want the "try an exact search
first, then fall back to fuzzy if there were no matches" behavior introduced in
commit 64c854c. After getting user feedback, it turns out we only want that
behavior on a few specific search fields, not across the board.
Search field criteria with a type of `Fuzzy` are now always fuzzy, with no
exact-then-fuzzy fallback. The new type `ExactOrFuzzy` will return exact matches
if there are any, or fuzzy matches if there are no exact ones.
> SW-3070 Add ExactOrFuzzy search type

- src/main/kotlin/com/terraformation/backend/report/api/ReportsController.kt
- similar to [withdrawal photos response](https://github.com/terraware/terraware-server/blob/c9ebbd6e738b1e9d5ed447223d10577a0c33ee36/src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt#L261)
- this is mostly for a reusable photo upload function in the FE codebase [see](https://github.com/terraware/terraware-web/commit/43f989c7bb02e05a8b51b816bd5c2b9ade9e9649#r102961693)
> Rename reports photo upload response to 'id' from 'fileId'

- src/main/kotlin/com/terraformation/backend/report/api/PayloadsV1.kt
The payload classes for nurseries, planting sites, and seed banks in reports were
missing the `selected` field to indicate whether or not they should be included
in aggregated totals when the report is submitted.
> Add missing "selected" field to reports

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/reports/v1/index.html
Remove links and thumbnails from the HTML-rendered reports since they won't work
when we export the report to Google Docs.
Use `<span>` instead of `<div>` to wrap line items on the report; Google Docs
doesn't recognize header tags inside `<div>`.
> SW-2988 Simplify HTML for Google Docs import

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/file/GoogleDriveWriter.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/kotlin/com/terraformation/backend/report/render/ReportRenderer.kt
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/reports/v1/index.html
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
When a report is submitted, export it to Google Drive along with its supporting
files. The report itself is created as a Google Docs document. A CSV file with
the aggregated report data is also created, and all photos and files are copied.
This requires some configuration:
* The `GOOGLE_APPLICATION_CREDENTIALS` environment variable must be set to the
path of a Google client credentials configuration file. The file can be
generated using the `gcloud` tool from the Google Cloud SDK.
* `terraware.report.export-enabled` must be true.
* `terraware.report.google-drive-id` must be set to the ID of a shared drive.
* `terraware.report.google-folder-id` may optionally be set to the ID of a folder
within the shared drive; reports will be placed inside that folder.
* `terraware.report.google-email` …
> SW-2988 Upload submitted reports to Google Drive

- src/main/kotlin/com/terraformation/backend/file/ThumbnailStore.kt
Loading too many photos into memory at once to generate thumbnails exhausts the
server's heap space. Add a semaphore to limit the number of photos we can resize
at the same time on a given server instance.
This initial implementation is very naive and doesn't take into account the fact
that memory usage varies depending on the photo's dimensions, but should be
conservative enough to protect us from out-of-memory errors if a client requests
dozens of thumbnails of newly-uploaded images in rapid succession.
> SW-3203 Limit concurrent thumbnail generation

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/NotificationsController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/device/api/AutomationsController.kt
- src/main/kotlin/com/terraformation/backend/device/api/DeviceManagersController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesUploadsController.kt
- src/main/kotlin/com/terraformation/backend/report/api/ReportsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsUploadsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/StorageLocationsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesLookupController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesUploadsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
Spring uses the controller argument names as the names of query string parameters
by default, so there's no need to specify them explicitly. Spring also infers
whether or not a query string parameter is required based on the nullability of
the argument's type, so there's no need to explicitly specify that in the
annotation either.
There's no change in behavior or the OpenAPI schema here.
> Remove redundant @RequestParam arguments

- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderGibberishTask.kt
- src/main/kotlin/com/terraformation/backend/i18n/Gibberish.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/search/field/BooleanField.kt
- src/main/resources/i18n/Messages.properties
We accept a number of synonyms for "true" and "false" in boolean columns in
uploaded CSV files. Previously, each synonym was a separate translatable
string, but that's going to be confusing for translators, especially if the
number of words needs to vary between languages.
Combine the word lists into two strings and add a description to each one to tell
translators what to do.
Previously, we used the first word in the list as the canonical localized word
that was accepted by, and returned by, the search API. Add separate strings for
that purpose so we don't have to tell translators to be careful about the order
of the list of synomyms.
The "one synonym per line" format uncovered a bug in gibberish string conversion:
it wasn't preserving line breaks on multiline strings, which included …
> Combine CSV boolean values into single strings

- src/main/kotlin/com/terraformation/backend/report/api/PayloadsV1.kt
The report payload `lockedByName` field was not being populated. It turned
out to have been trying to look up the user by the `modifiedBy` user id.
Change it to look up by `lockedBy` id.
> SW-3229 Fix Locked by User Name in Report Payload

- src/main/kotlin/com/terraformation/backend/report/render/ReportRenderer.kt
- src/main/resources/templates/reports/v1/index.html
The seedbank/nursery/planting site counts rendered in the report html
document should only include those facilities that were selected for
inclusion in the report, rather than the total counts.
> SW-3245 Facility Count Only Selected

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionSummaryStatistics.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/AccessionServiceSearchSummaryTest.kt
We want the total seed count for a seedbank to include the seed quantity
withdrawn from that seedbank as well as the seeds currently stored. This
results in the total number of seeds stored in the seedbank for all time
which is the value that is required for reports. We had to add the total
withdrawn seeds to the seedbank summary statistics to get this value.
(sorry I accidentally pushed this to main but reverted it)
> SW-3183 Include Withdrawn Quantity in Seed Count

- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/resources/db/migration/V181__ReportStatusConstraint.sql
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
We want to make sure the data in the database is consistent with its
submission status. Therefore, add a database migration which makes sure that
existing reports are in the submitted state when there is a submitted_by
user. It also adds a constraint that ensures that when there is such a user
the report must be submitted. And when the it is submitted there must be
a submitted_by user.
In the lock and unlock methods of ReportService, add a condition that the
report is not submitted and throw an exception otherwise.
> SW-3360 Disallow Lock/Unlock When Submitted

- src/main/kotlin/com/terraformation/backend/tracking/mapbox/MapboxService.kt
If the test clock was set forward in time, Mapbox temporary token generation was
failing because we were exceeding the maximum expiration time on tokens.
Explicitly use the system clock for calculating requested expiration times of
Mapbox tokens.
> Use system clock for Mapbox token expiration

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/resources/i18n/Messages_en.properties
Phrase doesn't handle punctuation-only strings very well; orders that include them
never get marked as completed, and it's unclear whether or not they ever get sent
to translators. Also, Phrase's GitHub export sometimes (though not always) trims
trailing whitespace from strings.
Remove the `listDelimiter` string and hardwire it into the code. The delimiter is
the same (comma followed by space) in English and Spanish, so add a value for
gibberish (underscore followed by space) and Chinese (a punctuation mark that
doesn't exist in English, not followed by space) mostly as documentation of what
the code should do.
> Remove translatable string for list delimiter

- .github/workflows/main.yml
Currently, when Renovate opens a PR, two CI builds are kicked off, one when it
pushes to its branch and another for the PR. Update the configuration to skip the
second of those.
> Stop double-building Renovate PRs

- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportFileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
When a report is submitted, we want to save build start, build completion, operation start, and capacity for seed banks and nurseries if they are entered in a report. They should be saved after report validation, and only facilities that are selected should have those values saved.
> SW-3433 Save SeedBank and Nursery Info on Submit

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/test/kotlin/com/terraformation/backend/file/FileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
The `photoIntermediateDepth` config option used to control the structure of the
paths the server generates when it stores photo files. But we changed the paths
to be date-based, so the option is no longer used anywhere.
> Remove unused config option

- .github/workflows/docs.yaml
- .github/workflows/main.yml
- CONVENTIONS.md
- README.md
- build.gradle.kts
- buildSrc/build.gradle.kts
- docker/Dockerfile
- jooq/build.gradle.kts
- settings.gradle.kts
- src/main/kotlin/com/terraformation/backend/tracking/mapbox/MapboxService.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
Generate Docker images that run on a Java 20 JVM to take advantage of recent
performance improvements and bugfixes.
Currently, the Kotlin compiler only supports generating classfiles for JVM
versions up to 19, so configure the target classfile version separately from the
version of the JVM itself.
To make it easier to switch versions in the future, start using Gradle's Java
toolchain support to automatically install an appropriate JVM version.
A couple of Java standard library functions have been deprecated in recent
releases; update our uses of them to use the non-deprecated alternatives.
> Upgrade to Java 20

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
The `MessageFormat` class, which is used to format localized messages that contain
placeholders, requires single quote characters to be escaped. By default, Spring
only uses `MessageFormat` if there are actually placeholders. Unfortunately, that
means the escaping rule for single quote characters depends on whether or not the
string happens to have placeholders.
This was causing the added-to-organization notification to have an English title
of, `You''ve been added to a new organization!` (note the two single quote
characters).
Make the escaping behavior consistent by configuring the resource bundle to always
use `MessageFormat` even if there are no placeholders.
> SW-3493 Fix duplicate single quotes in notifications

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
For a real planting site, the list of monitoring plots will be too large to
reasonably include in its entirety when a client fetches a site's information.
Remove them from the planting site API.
Monitoring plots may still be queried using the search API.
> SW-3504 Omit plots from planting site payloads

- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/i18n/FormattingResourceBundleModel.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Commit 0e5e0dcc attempted to enforce consistent handling of single quotes in
localizable strings, but it missed a code path: the models that are used with
Freemarker templates such as email messages. We were thus still including
duplicate single quote marks in email messages.
> SW-3493 Remove duplicate single quotes from email

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/db/migration/0151/V185__MonitoringPlotPermanentCluster.sql
- src/main/resources/db/migration/0151/V185__MonitoringPlotPermanentSeq.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/templates/admin/plantingSite.html
Group monitoring plots into 2x2 clusters. If all four plots in a cluster fall
within a single subzone, that cluster is eligible to be chosen as a set of
permanent monitoring plots.
An eligible cluster is identified by the presence of a permanent monitoring plot
cluster number. All four plots in a cluster will have the same cluster number.
The cluster numbers are randomized at import time.
The admin UI is updated to demonstrate/test the selection process; currently it
is hardwired to simulate 6 clusters of permanent plots per planting zone and
highlight them on the map.
> SW-3521 Generate permanent monitoring plot clusters

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
In preparation for being able to configure the number of monitoring plots on a
per-planting-zone basis, add read and update permission logic for planting zones.
There are no create or delete permissions since planting zones are only created
via shapefile import, and are never deleted independently of the planting site.
> SW-3535 Add permissions for planting zones

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
In preparation for adding more values to planting sites, update the fetch and
update methods in `PlantingSiteStore` to be a bit more flexible:
* The `fetch` methods now take a "depth" argument to control how many levels of
hierarchy to fetch.  This replaces the boolean flags.
* The `updatePlantingSite` method now takes a function that modifies the existing
model object.
These changes are purely implementation details; client-facing API behavior is
unchanged.
> SW-3536 Improve PlantingSiteStore fetch/update

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/db/MonthConverter.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/db/migration/0151/V187__PlantingSiteDates.sql
- src/main/resources/templates/admin/plantingSite.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Add optional planting season start and end month fields to planting sites.
These will be used to determine the schedule for the site's observations.
> SW-3536 Add planting season start/end months

- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
- src/main/kotlin/com/terraformation/backend/species/model/Validation.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesCsvValidatorTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesImporterTest.kt
Update the import validator to allow dashes in scientific names. We allow for
all three types of dashes that might be encountered, hyphen, en-, and em-.
Also update the tests to account for this change.
> SW-3527 Allow Dashes in Scientific Names During Import

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Shapefile.kt
- src/main/resources/db/migration/0151/V188__PlantingSiteAreas.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/ShapefileFeatureTest.kt
Planting density is calculated as number of plants per unit of area, so we need to
know the areas of planting sites and their subdivisions. This can be calculated on
the fly from the boundaries, but it never changes, so calculate it at import time.
> SW-3548 Calculate planting site areas

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/plantingSite.html
When showing the map of a planting site in the admin UI, we highlight permanent
monitoring plots. Previously, this was done by selecting the line color, but that
meant that on the grid of plots, only the left and bottom borders were colored
because the right and top ones were overwritten by other grid cells.
Add a separate layer for permanent plots so they show up more distinctly on the
map. Restructure the way the plot types are labeled in the GeoJSON data so that
it will be possible to do the same for temporary plots later.
> Use separate map layer for permanent plots

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/plantingSite.html
- src/main/resources/templates/admin/plantingSiteMap.html
To avoid cluttering the admin UI, the inline map on the planting site page had a
fixed height, which made it awkward to view sites with tall thin shapes. Move
the map to a popup window that can be resized as the user sees fit.
> Show planting site map in popup

- src/main/kotlin/com/terraformation/backend/seedbank/api/PhotosController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/PhotoRepository.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
Initially, all the metadata about accession photos was stored in a single table
that had a unique constraint to enforce that a given accession could only have
one photo with a given filename. When the table was split up to add support for
nursery withdrawal photos, we lost that unique constraint and thus the server
started accepting uploads of accession photos with duplicate filenames.
When a client attempted to read one of those photos, the request would fail
because the server still assumed filenames were unique and a database query
that was expected to return a single row instead returned multiple rows.
Change the upload API so that uploading a photo overwrites any existing photo 
with the same filename on the same accession. To handle the duplicates that
already exist in the database, …
> SW-3509 Handle duplicate accession photo filenames

- src/main/kotlin/com/terraformation/backend/search/field/TextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/UpperCaseTextField.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
We want to have, for accession numbers and collection sites, among others, exact
search to return results with substring exact matches. This change updates the
TextField and UpperCaseTextField exact search conditions to account for this.
When exact substring matches are found, trigram (fuzzy) search should not
be in effect for exact-or-fuzzy search.
> SW-3070 Exact Search Performs Substring Search for Selected Fields

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/resources/templates/admin/plantingSite.html
Include the area in hectares and the number of reported plants in each subzone
on the admin UI's planting site page. These numbers will be used to calculate
reported planting density as well as to determine which subzones are eligible
for monitoring, so being able to view them easily is useful for sanity-checking.
> Show area and reported plants in each subzone

- src/main/resources/application.yaml
The Keycloak adapter uses an out-of-date version of the Apache HTTP client that
doesn't know how to deal with the expiration times on the cookies that are added
by the load balancer that sits in front of our Keycloak instance. It spits out
a warning log message every time the adapter talks to Keycloak, which happens
often enough to add significant log clutter.
The eventual fix will be to stop using the Keycloak adapter (which is deprecated)
but for now, configure the logger to filter out warnings from the class in
question.
> Suppress load balancer cookie warning

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/db/migration/0151/V190__DefaultVarianceAndError.sql
- src/main/resources/templates/admin/plantingSite.html
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
To avoid situations where nobody has entered the variance and error margin for a
planting zone and thus the system has no idea how many monitoring plots to assign,
make those values (and the monitoring plot counts derived from them) mandatory
with defaults rather than optional.
In addition, don't allow either the permanent or the temporary plot count to be
zero; we always want at least one permanent cluster and one temporary plot per
observation.
> SW-3600 Make monitoring plot config mandatory

- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
Since `PlantingZoneModel.chooseTemporaryPlots()` needs to know which subzones have
plants, we can make it filter out the ones that don't, rather than requiring the
caller to do so.
> Don't put temporary plots in unplanted subzones

- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreDeleteBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreGetNurseryStatsTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreSpeciesSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/TrackingSearchTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/DeliveryStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Make the insert helper functions in `DatabaseTest` remember the IDs of the rows
they've inserted, and use the most recently inserted ID as the default in places
where callers previously had to pass in IDs explicitly.
This will help us write more succinct tests, especially in cases where a complex
graph of entities has to be built.
Update the tests that construct planting sites to use this new functionality.
> Use inserted test IDs as defaults

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
The science team gave us updated parameters to use as defaults in the formula
that determines how many monitoring plots should be assigned in an observation.
> SW-3600 Update default variance and error

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Add read and update permissions for observations, plus a special "manage"
permission for privileged operations that will be performed by the system user or
by super-admins but shouldn't be available to regular users (even organization
admins).
Nothing uses these permissions yet.
> SW-3601 Add permissions for observations

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
It was a one-statement wrapper around an underlying function that callers can call
directly instead.
> Remove PlantingSiteStore.fetchPlantedSubzoneIds

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/log/LoggingExtensions.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationModel.kt
- src/main/resources/templates/admin/plantingSite.html
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Implement the logic for assigning monitoring plots to an observation. In the
finished product, this will run automatically when the observation's start date
arrives, but for now super-admin users can trigger it manually via the admin UI
if the prerequisites are met (mainly: the start date has arrived and the site
has subzones with plants).
> SW-3601 Start observations from admin UI

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/AssignedPlotDetails.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationPlotModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Add two API endpoints to support the monitoring plot selection UI in the mobile
app's pre-monitoring flow.
`GET /api/v1/tracking/observations` returns a list of observations for an
organization or for a single planting site.
`GET /api/v1/tracking/observations/{id}/plots` returns a list of the monitoring
plots assigned to a specific observation.
> SW-3608 Endpoints to get observation details

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Add two API endpoints to support the monitoring plot selection UI in the mobile
app's pre-monitoring flow.
`POST /api/v1/tracking/observations/{observationId}/plots/{plotId}/claim` claims
one of the monitoring plots that has been assigned to an observation. A monitoring
plot may only be claimed by one user at a time.
`POST /api/v1/tracking/observations/{observationId}/plots/{plotId}/release`
releases a previously-acquired claim on a monitoring plot, making it available for
other users to claim.
> SW-3605 Endpoints to claim and release plots

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
`POST /api/v1/tracking/observations/{observationId}/plots/{plotId}/photos` uploads
a photo of a monitoring plot with some relevant metadata about where the photo was
taken.
> SW-3606 Endpoint to upload observation photos

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
We originally thought we were going to use numbers to identify subzones, but
in practice we've wanted to label them with text instead, and the validation
check isn't telling us anything useful. Remove it.
> Remove "subzones have numeric names" validation

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
We are allowing monitoring plots that are partially in two or more subzones,
but they are only allowed to be assigned for monitoring as part of a permanent
cluster. Add logic to disallow them as temporary plots.
> SW-3638 Temporary plots may not straddle subzones

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Now that we allow monitoring plots to straddle subzone boundaries, it is also
possible for a permanent cluster to be made up of plots in multiple subzones.
The "only assign permanent clusters whose subzones are planted" logic thus needs
to be changed such that it requires _all_ the cluster's subzones to be planted.
> SW-3639 All subzones of permanent cluster must be planted

- src/main/kotlin/com/terraformation/backend/customer/event/PlantingSiteTimeZoneChangedEvent.kt
- src/main/kotlin/com/terraformation/backend/daily/ObservationScheduler.kt
- src/main/kotlin/com/terraformation/backend/tracking/PlantingSiteService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlantingSiteServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
When the start date for an upcoming observation arrives in the planting site's
time zone, automatically start it.
> SW-3616 Start observations on their start dates

- src/main/kotlin/com/terraformation/backend/daily/ObservationScheduler.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
When an observation's end date passes and it is still in progress, change its
state to "Overdue."
> SW-3617 Update states of overdue observations

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/db/EnumFromReferenceTable.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/ViabilityTest.kt
- src/main/resources/templates/admin/deviceTemplates.html
- src/main/resources/templates/admin/facility.html
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/reports/v1/index.html
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchAllValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRawTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceUserSearchTest.kt
JSON deserialization of our reference table enums was expecting English
display names as values, rather than the non-localized names from the
`name` columns of the reference tables.
Historically, those two were the same since we didn't have any concept of
localizing an enum name. But now that we support localization, there is
a distinction between the enum string values in the API (which uses the
names from the database) and the human-readable values that get included
in exported CSV files and the like.
We were correctly using the names from the database in responses, and listing
those names as the acceptable values in the OpenAPI schema. But the actual
JSON deserialization was expecting the localized English names.
This caused the server to reject the value `CantTell` of the …
> Accept canonical enum values in API payloads

- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
- src/main/kotlin/com/terraformation/backend/db/EnumFromReferenceTable.kt
The localized English name for `RecordedSpeciesCertainty.CantTell` was being
rendered as `Can''t Tell` because single quotes in properties files are always
escaped by Phrase and we weren't unescaping them.
Including an apostrophe in an enum's name in the reference table was generating
broken code because it isn't a valid character in a Kotlin symbol. Update the
code generator to strip non-alphanumeric characters out of enum values.
> Handle apostrophes in enum display names

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/resources/db/migration/0151/V192__PlantingZoneDensity.sql
- src/main/resources/templates/admin/plantingSite.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
Track the target planting density (in plants per hectare) for each planting zone.
The value is imported from the shapefile if present; otherwise we use a default.
It can be updated using the admin UI.
Nothing uses this value yet, but it will be an input into planting progress
calculations.
> SW-3641 Planting zone target planting densities

- scripts/client.py
- scripts/create_species.py
- scripts/observe.py
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
Add two new scripts in the `scripts` directory:
* `create_species.py` creates some example species in an organization so
that there are species IDs available to associate with recorded plants.
* `observe.py` claims then completes some or all of the outstanding monitoring
plot observations in an observation round. It generates semi-random data
that should have enough variety to be useful for testing.
The second script required a way to fetch the details of a single observation,
so there's now a GET endpoint for that. It also required a way to figure out
the organization ID starting from an observation ID; the planting site payload
now includes the site's organization ID.
> SW-3646 Scripts to create species and complete observations

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSubzonesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
When users are in the field conductng an obaservation, the mobile app needs to
show the list of species that have been planted in a particular subzone. Add
`GET /api/v1/tracking/subzones/{id}/species` to return that list.
> Add API endpoint to list species in subzone

- .github/scripts/set-environment.sh
- .github/workflows/main.yml
- src/test/kotlin/com/terraformation/backend/device/balena/LiveBalenaClientExternalTest.kt
- src/test/kotlin/com/terraformation/backend/file/S3FileStoreExternalTest.kt
By default, we skip tests like `S3FileStoreTest` in CI because we don't want our
CI builds to fail if the AWS API is having a glitch that's unrelated to the
changes we're making to our code. But that means we don't detect problems in
the code under test, or, more commonly, problems caused by upgrades of the client
libraries we use to talk to those services.
Add a build step that runs those tests (which are now required to have class names
ending in `ExternalTest` but doesn't cause the whole workflow to fail if they
don't pass. The failures will still be visible in the build log, so we can decide
on a case-by-case basis whether we care about them.
> SW-1031 Run tests that depend on external services

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/resources/db/migration/0151/V195__UnknownSpeciesTotals.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Previously, we were only calculating total observations of plants of known
species, but we need to be able to show totals for "Can't Tell" plants as well as
break the "Other" plant totals down by user-supplied species names.
Change the totals tables to include both species ID and name columns whose
nullability depends on the recorded species certainty.
Since there aren't any observations in production yet, this is done by dropping
and recreating the tables rather than altering them.
> Track "Other" and "Can't Tell" plant totals

- scripts/observe.py
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Earlier versions of the product spec used the term "Can't Tell" to describe
species that the user can't identify at observation time, but now it's using the
term "Unknown." Update the data model and API to match the official terminology.
This is a breaking API change; clients that submit observation data will need to
replace `CantTell` with `Unknown` in the species certainty payload field.
> Rename "Can't Tell" to "Unknown"

- src/test/kotlin/com/terraformation/backend/i18n/EnumsTest.kt
If `Enums_en.properties` has a key that doesn't match any enum values, but does
have keys for all the values of all the enums, `EnumsTest` should pass.
This was causing CI failures after we deleted an enum value; the old English
display name was still in Phrase's string list and Phrase added it to back to
the properties file on export.
> EnumsTest shouldn't fail on extra values

- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/resources/db/migration/0151/V196__DropTotalObservedPlants.sql
- src/main/resources/db/migration/R__Comments.sql
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
The total number of observed plants can be calculated from the live, dead, and
existing totals.
The total was included as an explicit column in order to support exposing it
via the search API, but we've decided against using the search API to fetch
observation results, so it's no longer useful.
> SW-3730 Drop total plants from observed species totals

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Constants.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationResultsPayload.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStoreTest.kt
- src/test/resources/tracking/observation/OneZoneFinished/Plants.csv
- src/test/resources/tracking/observation/OneZoneFinished/PlotStats.csv
- src/test/resources/tracking/observation/OneZoneFinished/PlotStatsPerSpecies.csv
- src/test/resources/tracking/observation/OneZoneFinished/Plots.csv
- src/test/resources/tracking/observation/OneZoneFinished/SiteStats.csv
- src/test/resources/tracking/observation/OneZoneFinished/Subzones.csv
- src/test/resources/tracking/observation/OneZoneFinished/ZoneStats.csv
- src/test/resources/tracking/observation/OneZoneFinished/ZoneStatsPerSpecies.csv
- src/test/resources/tracking/observation/OneZoneFinished/Zones.csv
Add GET endpoints to fetch observation results.
* `/api/v1/tracking/observations/results?organizationId={id}` gets the results 
of all observations across all an organization's planting sites.
* `/api/v1/tracking/observations/results?plantingSiteId={id}` gets the results 
of all observations of a single planting site.
* `/api/v1/tracking/observations/{id}/results` gets tthe results of a single
observation.
The summary calculations are tested against the numbers from a spreadsheet we're
using as part of the requirements process.
> SW-3730 Observation results API

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Shapefile.kt
- src/main/resources/templates/admin/organization.html
Testing the geolocation features of the mobile app on real devices requires
visiting a planting site. For development testing by people working remotely,
it's too time-consuming to construct a real set of shapefiles for each person's
location, so people need to be able to create test planting sites near themselves.
Add a section to the organization page in the admin UI to allow creating a
planting site by drawing the boundary on a map. Sites created this way are very
simple (one zone and one subzone) but should be sufficient for test purposes.
> SW-3717 Create ad-hoc planting sites from admin UI

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
To allow the client to show per-hectare statistics about planting sites, add
`areaHa` fields to the planting site, zone, and subzone API payloads. The
site-level field is only present if the site was created with map data (shapefile
upload or polygon-on-a-map creation in the admin UI).
> Include areas in planting site/zone/subzone data

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStoreTest.kt
To allow the plants dashboard to show statistics from the most recent
observation of a given planting site, allow the client to request a maximum
number of results and change the result order so the most recently completed
observation always comes first. The client can thus pass in a planting site ID
and a limit of 1 to fetch the latest observation results for the site.
The default is still to return results from all observations.
> Add limit parameter to observation results API

- src/main/resources/db/migration/0200/V200__BackfillPopulations.sql
Backfill the plant totals for planting sites, zones, and subzones. This overwrites
any existing values with the correct totals across all plantings.
This should be deployed as its own release so that it only runs when all the
server instances are already aware of these tables.
> SW-3731 Backfill planting site populations

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteReportedPlantTotals.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
`GET /api/v1/tracking/sites/{id}/reportedPlants` will return the total number of
plants reported to have been planted at a site, as well as a breakdown of reported
plants per planting zone if planting zones are defined for the site.
If planting zones are defined, the zones and the site will also have a progress
percentage, which is based on the target planting density, zone size, and total
plants planted.
This only looks at data from outplanting nursery withdrawals, not at observation
results.
> SW-3731 API endpoint to get plant totals for sites

- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/EmailService.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Rather than fetching a list of organization user email addresses and then fetching
the `IndividualUser` for each email address, fetch the list of `IndividualUser`s
directly. This will be more efficient when sending notifications to organizations
with large numbers of users.
> Fetch organization users with one query

- src/main/kotlin/com/terraformation/backend/email/EmailService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Some organization-wide notification email messages (e.g., device manager alerts
and report-created notifications) weren't paying attention to recipients' locales
and were always being sent in English.
> SW-3754 Localize organization-wide email messages

- .github/scripts/deploy.sh
- .github/scripts/set-environment.sh
- .github/workflows/main.yml
When deploying to the AWS hosts, connect to the VPC network using Tailscale and
ssh directly to the hosts rather than bouncing through a bastion host.
> SW-3394 Deploy using Tailscale instead of bastion

- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
Currently, the helper function that replaces square brackets with `<a>` tags in
localizable strings in email notification bodies only supports one link per
string. Update it to support arbitrary numbers of links in preparation for adding
an email notification that has two links in one sentence.
> Support strings with multiple links in email messages

- build.gradle.kts
JobRunr 6 adds support for Spring Boot 3 but still supports Spring Boot 2. Upgrade
to the latest version so we can catch any problems introduced by JobRunr 6
independently of the Spring Boot upgrade.
> SW-2710 Upgrade to Jobrunr 6.2.2

- src/main/resources/templates/admin/appVersions.html
- src/main/resources/templates/admin/deviceManager.html
- src/main/resources/templates/admin/deviceTemplates.html
- src/main/resources/templates/admin/facility.html
- src/main/resources/templates/admin/index.html
- src/main/resources/templates/admin/internalTag.html
- src/main/resources/templates/admin/listDeviceManagers.html
- src/main/resources/templates/admin/listInternalTags.html
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/admin/plantingSite.html
- src/main/resources/templates/admin/testClock.html
Upcoming versions of Thymeleaf are going to stop supporting the `th:include`
directive as well as the shorthand syntax for referencing other templates.
Update our `th:include` directives to use the syntax that will be supported
going forward.
No behavior change here.
> SW-2710 Use non-deprecated Thymeleaf includes

- .github/workflows/docs.yaml
- gradle.properties
The recent upgrade to Dokka caused it to need more memory, which caused it to run
out of memory in CI builds. Bump up the maximum heap size to give it enough room
to run successfully, and move it a bit earlier in the CI build process so we'll
get faster failures if it breaks in the future.
> Increase heap size to fix Dokka failures

- src/main/kotlin/com/terraformation/backend/i18n/Locales.kt
- src/main/resources/csv/accessions-template_gx.csv
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
Locales such as French (and thus gibberish) use whitespace as the thousands
separator, but they don't use an ASCII space; instead they use a special
non-breaking space. Users, however, don't have an easy way to enter that kind
of space when they're manually typing numbers into spreadsheets, which means
the numbers in uploaded CSV files would technically not be valid.
Work around the problem by stripping all whitespace characters from numeric
cells in uploaded CSV files before parsing them.
> Ignore whitespace in numbers in CSV files

- src/main/resources/csv/accessions-template_es.csv
- src/main/resources/csv/species-template_es.csv
Fix some problems with the Spanish CSV templates found during QA:
* The accessions template had a line of instructions that was still in English.
* The field name for "rare" in the species CSV template didn't match the field
name in the error message for validation failures on that field.
* Some of the translations were badly worded.
> SW-3797 Improve Spanish CSV templates

- src/main/resources/application-default.yaml
Flyway looks for migrations in subdirectories, so there is no point in
configuring it to look in a specific subdirectory in dev environments.
> Remove pointless Flyway configuration

- src/main/kotlin/com/terraformation/backend/api/Annotations.kt
We have custom OpenAPI annotations to document that controller methods can
return certain kinds of responses. The annotations have parameters that supply
the values of some of the parameters of the underlying OpenAPI annotations.
Future versions of Spring are going to stop automatically using parameters on
annotations like these as the values of the underlying annotations, and will
require applications to explicitly declare that they want the parameters to be
treated as aliases for the parameters of other annotations. Spring Boot 3 logs
warnings about the upcoming behavior change.
Add the appropriate declarations so our annotations won't break in future Spring
versions.
> SW-2710 Declare annotation property aliases

- src/main/resources/logback-spring.xml
Spring Boot 3 has stricter validation of the logging configuration, and complains
if the console appender is defined but not used. Move it to a conditional block.
> Only define Logback console appender if it's used

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/index.html
The admin UI allows importing GBIF species data from a zipfile. Previously, the
zipfile was uploaded by the browser using a file input. It is a huge file and
requires special treatment to avoid running into request size limits. And the
way file uploads are handled is different in Spring Boot 3, so we'd need to
implement a brand-new mechanism for dealing with the file.
Change the admin UI so it accepts a URL as input and pulls the file from there.
The common case will be in dev environments with a `file://` URL pointing to the
local filesystem. It's not quite as convenient, but GBIF import is a pretty rare
operation so the added burden should be miniscule.
> Download GBIF data instead of uploading it

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/api/Extensions.kt
- src/main/kotlin/com/terraformation/backend/api/SpringMvcConfig.kt
- src/main/resources/application.yaml
We were using an Apache library to make it easier to work with uploads of large
files. Spring Boot 3 doesn't support that library; rather than implementing new
code to support large file uploads, we've instead removed the need to upload
large files in the first place. We can thus get rid of the library and rely on
Spring's built-in file upload support.
> SW-2710 Remove Apache Commons FileUpload library

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/file/GoogleDriveWriter.kt
The credentials for the Google API, which we use to export report files to Google
Drive, have to be in JSON form. By default, the Google client library expects the
credentials to be in a file, but it also allows callers to directly supply a JSON
object.
Add a Terraware config value that lets us pass the JSON object in an environment
variable so we don't have to write it to a file on the server.
> SW-3815 Read Google credentials from environment

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
Accession states are never null (they are populated at creation time and never
cleared) so there's no reason for `AccessionModel` to be able to represent an
accession with a null state.
No behavior change here, just marginally cleaner code.
> Make AccessionModel.state non-nullable

- src/main/kotlin/com/terraformation/backend/search/table/SpeciesTable.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesLookupController.kt
- src/main/kotlin/com/terraformation/backend/species/model/GbifModels.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBooleanTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/model/GbifTaxonModelTest.kt
Stop supporting the old `endangered` field in the various species API payloads.
Clients will need to use the `conservationCategory` field instead.
This should only be deployed after all clients have been updated to use the new
field.
> SW-3127 Remove endangered field from species API

- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
In preparation for an upcoming change that causes changes to an accession's
species to be propagated to seedling batches that come from that accession,
add logic to prevent editing an accession's species if the accession's seeds
have already been sent to a nursery, and seedlings have already been withdrawn
from the nursery and delivered to a planting site.
This prevents accession species changes from causing inconsistencies between
nursery withdrawals and the species populations at planting sites. In the
future we may remove this restriction and make the species changes propagate to
planting site data too, but doing so would introduce a number of edge cases
that would require more detailed requirements definition.
The fact that seedlings from an accession's seeds have been delivered to …
> SW-3647 Accession species only editable if no deliveries

- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/event/AccessionSpeciesChangedEvent.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/Accession.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreAccessionSpeciesTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/AccessionServiceSearchSummaryTest.kt
It can be difficult to distinguish some species of seeds from others; sometimes
a definitive species ID can only happen after the seeds have sprouted and the
seedlings can be examined.
If it turns out that the initial guess at the species was wrong, we want to
update the accession to have the correct species. Currently, though, the species
of the seedling batches don't change, and there's no way to edit them manually;
they remain listed under the old incorrect species.
Update the system so that changing the species of an accession will automatically
update the species of all the seedling batches that came from that accession.
It is not currently permitted to change the species of an accession if there are
already outplanting withdrawals of its seedlings; we thus don't need to reflect …
> SW-3647 Apply accession species changes to batches

- build.gradle.kts
- buildSrc/build.gradle.kts
- gradle.properties
- settings.gradle.kts
- Use property assignment rather than `.set()` (technically still an incubating
feature but it's enabled by default in 8.2)
- Upgrade a couple plugins to newer versions that don't call newly-deprecated
Gradle APIs
- Enable "all warnings as errors" compilation mode on build scripts
- Remove a null check that is no longer necessary
> Update build scripts for Gradle 8.2

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
If a recorded plant's species is known, the server is supposed to ignore the
value of the `speciesName` field in the plot observation completion API
payload, but it doesn't; instead the request fails due to a database constraint
violation.
Update the code to conditionally ignore species ID and name like the API
documentation says it does.
> Ignore irrelevant fields in plant observation payload

- .github/workflows/main.yml
Tailscale's API-key-based authentication is now deprecated; use OAuth instead.
> Switch Tailscale authentication to OAuth

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
If you use the "draw site on map" feature of the admin UI to draw a planting site
that's only big enough for one 4-plot cluster, the server creates the planting
site but then can't start any observations because it can't allocate any temporary
plots.
Update the importer code to ensure that there are at least 5 plots available; if
not, site creation fails. Since plots are allocated in groups of 4, technically
"5 plots minimum" is really "8 plots minimum" and thus the planting site must be
at least 100x50 meters.
> Require planting sites to have at least 5 plots

- src/main/kotlin/com/terraformation/backend/api/LocaleConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/resources/db/migration/0200/V207__UserCountry.sql
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
To support variation of number formatting rules in different Spanish-speaking
countries, keep track of users' countries. If the user has selected a country,
their locale will include a country code as well as a language.
The server will automatically include the user's country code in their locale
when they update their profile information, to account for the fact that clients
have language selectors that don't include country codes. That is, if the user
sets their locale to `es` and their country to `MX`, the server will save the
locale as `es-MX`.
Number and date formatting will automatically use country-specific rules once
the user has set their country.
> SW-3868 Add country code to users, locales

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteReportedPlantTotals.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
`GET /api/v1/tracking/sites/{id}/reportedPlants` currently breaks down the plant
totals by planting zone, but we need to show per-subzone totals in the web app.
Add a level of hierarchy to that API endpoint's response that returns per-subzone
totals.
> Calculate per-subzone plant totals

- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/field/BigDecimalField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DoubleField.kt
- src/main/kotlin/com/terraformation/backend/search/field/IntegerField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LongField.kt
- src/main/kotlin/com/terraformation/backend/search/field/NumericSearchField.kt
- src/main/kotlin/com/terraformation/backend/search/table/PlantingSubzonesTable.kt
- src/main/resources/i18n/Messages_en.properties
- src/test/kotlin/com/terraformation/backend/tracking/TrackingSearchTest.kt
To allow clients to query the number of plants in each subzone across sites
in a single organization, add a search field to get the total plants of all
species in a subzone. The per-species totals continue to be available in the
`populations` sublist.
> Add per-subzone total plants to search API

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteReportedPlantTotals.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
This reverts commit 2cf2f9e84f6a028caa113a771b196e199390b0e1.
We needed to be able to retrieve the totals across planting sites, not one site at
a time, so this initial stab was the wrong approach.
> Revert "Calculate per-subzone plant totals (#1291)"

- gradle.properties
The current compiler memory limit is just barely enough on ARM systems; upcoming
changes that added more code were causing it to run out of memory. Increase its
maximum heap size.
> Increase Kotlin compiler memory

- src/main/kotlin/com/terraformation/backend/customer/api/ProjectsController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/VersionsController.kt
- src/main/kotlin/com/terraformation/backend/device/api/AutomationsController.kt
- src/main/kotlin/com/terraformation/backend/device/api/DeviceManagersController.kt
- src/main/kotlin/com/terraformation/backend/device/api/DeviceTemplatesController.kt
- src/main/kotlin/com/terraformation/backend/device/api/DevicesController.kt
- src/main/kotlin/com/terraformation/backend/i18n/api/TimeZonesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/search/api/SearchController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/LogController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/StorageLocationsController.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesAdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/DeliveriesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/MapboxController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSubzonesController.kt
- src/test/kotlin/com/terraformation/backend/api/OpenApiAnnotationTest.kt
Some of our API endpoints didn't have any documentation. Add a unit test to
detect when we add an endpoint that doesn't at least have a summary, and add
summaries (and descriptions, if needed) to the existing endpoints that didn't
have them.
> Add docs to all API endpoints

- src/main/kotlin/com/terraformation/backend/customer/ProjectService.kt
- src/main/kotlin/com/terraformation/backend/customer/api/ProjectsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/customer/ProjectServiceTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Add an API endpoint to assign multiple accessions, seedling batches, and
planting sites to a project.
> SW-3931 API to assign projects in bulk

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
Based on feedback from our carbon consultant, we only need an 80% confidence level
on observations, not 90%. Change the default Student's t value to 1.282, which
corresponds with an 80% confidence level, and reduce the default number of
permanent clusters and temporary plots based on the new value.
This only changes the default for new planting sites; existing ones can be edited
in the admin UI if needed.
> SW-3952 Reduce default confidence interval to 80%

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/resources/templates/admin/organization.html
For testing observations in the mobile app, we want to be able to create the
smallest possible planting site, with one permanent cluster and one temporary
plot. Previously, this was impossible to do in the admin UI because the required
precision of the boundary lines was greater than the precision of the map.
Add a button to place a minimal-size planting site on the map. The user can move
it around on the map and change where the temporary plot is located relative to
the permanent cluster.
This requires adding some logic to the planting site creation code to account for
the fact that the map UI does coordinate transformations differently than the
server does, meaning that the site boundary submitted by the client will always
be off by a tiny amount from the server's point of view.
> SW-3977 Admin UI to create minimal planting site

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
If a nursery withdrawal is dated earlier than the time a batch's remaining
quantity was most recently manually observed, we don't override the
manually-entered quantity.
Unfortunately, we were using UTC to figure out which date the last observation
fell on, meaning the system could erroneously think that a withdrawal happened
before the last observation instead of on the same day. This caused the system
to not update the quantities of batches when it should have.
A followup change will backfill the missing quantity updates.
> SW-4007 Use nursery time zone to check withdrawn date

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
The mortality rate graphs in the web app need to show live and dead plant totals
that only consider plants in permanent plots. We were already calculating those
totals on the server side since they are the inputs to the mortality rate
calculation; expose them in the observation results API payloads.
> SW-4041 Return permanent plot live/dead counts

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/file/ThumbnailStore.kt
- src/main/kotlin/com/terraformation/backend/util/ImageUtils.kt
- src/test/kotlin/com/terraformation/backend/file/ThumbnailStoreTest.kt
- src/test/kotlin/com/terraformation/backend/util/ImageUtilsTest.kt
- Rotate image source (if needed) when creating thumbnails
- This is a copy of funder-backend PR https://github.com/terraware/funder-backend/pull/110
- Tested locally
> SW-4028 Rotate thumbnail image source

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/FacilityInventoriesTable.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
You should be able to ask for inventories of specific facilities using the
`facilityInventories` search table, but it was only allowing searches to be
narrowed by species ID.
> SW-3993 Facility-only filtering on facilityInventories

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
The planting site progress percentage was only computed across planting zones
with recorded plants. It needs to count all of the site's zones.
> SW-4054 Count empty planting zones against progress

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Add `boundary` fields to the PUT and POST request payloads for planting sites to
allow user-editable boundaries for simple planting sites. The boundary is ignored
on PUT for detailed planting sites.
> SW-3932 APIs to write planting site boundaries

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationPlotCounts.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
The mobile app needs to display a count of the number of monitoring plots in an
observation that haven't been completed yet, whether or not they've been claimed.
Add that count to the observation API, as well as a count of the total number of
monitoring plots in the observation regardless of status.
> SW-4082 Calculate more observation plot counts

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/resources/seedbank/accession/UsedUp.csv
We were explicitly disallowing accessions from being created in Used Up state
because it doesn't make much sense for a typical interactive workflow, but it
does make sense to be able to import historical accession data that includes
accessions that have already been fully withdrawn.
> SW-4084 Allow Used Up accessions to be imported

- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
All the clients were updated to use `/api/v1/facilities` instead of
`/api/v1/facility` some time ago, and there have been no hits on the singular
name for over a month. Remove the unused name from the API.
> SW-2363 Remove /api/v1/facility alias

- buildSrc/src/main/kotlin/com/terraformation/gradle/PostgresDockerConfigTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderGibberishTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderMjmlTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/VersionFileTask.kt
Gradle plugins are supposed to use lazy evaluation when fetching the build
directory since it can change at runtime, but we were using the non-lazy
getter. It is deprecated starting in Gradle 8.3; switch to the appropriate
lazy property.
> Gradle: Use lazy property to get build directory

- src/main/kotlin/com/terraformation/backend/search/table/AccessionsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/ViabilityTestsTable.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceAliasedFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceCompoundSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceCursorTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchAllValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFetchValuesTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceInitializationTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRangeSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
We renamed a few search fields and retained the old names for backward compatibility.
The old names are no longer referenced by any of the client code, so remove them.
> Remove unused search fields

- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionCsvValidator.kt
- src/main/resources/i18n/Messages_en.properties
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
Return a validation error if someone imports an accession whose status is Used Up
but whose quantity is nonzero.
> SW-4084 Validation error for nonzero Used Up quantities

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/facility.html
- Add the field to the admin devices form
- Plumb the field through the form controller to it saves in the DB
> SW-4223 Add Parent ID to admin facility devices form

- src/main/resources/db/migration/0200/V209__TerraformationContact.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- Also add a unique index constraint on organization user with the Terraformation Contact role id
- Tested locally and observed error adding second Terraformation Contact in org
```
terraware=# insert into organization_users(user_id, organization_id, role_id, created_time, modified_time, created_by, modified_by) values(99, 1, 5, '2023-02-02 19:20:33.13388-08', '2023-02-02 19:20:33.13388-08', 2, 2);
INSERT 0 1
terraware=# insert into organization_users(user_id, organization_id, role_id, created_time, modified_time, created_by, modified_by) values(122, 1, 5, '2023-02-02 19:20:33.13388-08', '2023-02-02 19:20:33.13388-08', 2, 2);
ERROR:  duplicate key value violates unique constraint "organization_users_pkey"
DETAIL:  Key (user_id, organization_id)=(122, 1) already exists.
```
> SW-4237 Add 'Terraformation Contact' role in database schema

- src/main/kotlin/com/terraformation/backend/customer/OrganizationService.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- introduced `assignTerraformationContact` function in OrganizationService which handles removing existing contact and assigning new contact
- added some tests
- updated AdminController and Admin UI to show/reassign Terraformation Contact (made some assumptions here as this is an interim solution)
- caveat, super admin needs to be part of the org in order to assign a Terraformation Contact (for now at least)
> SW-4242 Admin UI feature to assign Terraformation Contact (nice to have feature)

- src/main/kotlin/com/terraformation/backend/customer/OrganizationService.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/db/Exceptions.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- BE will handle deletion of last owner and Terraformation Contact when deleting an organization
- This allows the FE client to delete an org which has a Terraformation Contact membership (which cannot be deleted by the organization owner)
> SW-4243 Support deletion of Terraformation Contact when deleting an organization

- .github/renovate.json5
Updates to GitHub Actions plugins tend to come in waves, e.g., when a bunch of
plugins are updated to a newer Node.js version. Make Renovate group the updates
together into single PRs to reduce clutter in git history.
> Group GitHub Actions dependency updates

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- Added API to schedule/reschedule observations
- Added validation checks on the requests, based on requirements in the PRD
- Added tests for scheduling and rescheduling observations
- Also tested the API with real requests
> SW-4253 / SW-4254 API to schedule and reschedule observations

- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/resources/i18n/Messages_en.properties
- src/main/resources/templates/email/head.ftlh.mjml
- src/main/resources/templates/email/observation/rescheduled/body.ftlh.mjml
- src/main/resources/templates/email/observation/rescheduled/body.txt.ftl
- src/main/resources/templates/email/observation/rescheduled/subject.ftl
- src/main/resources/templates/email/observation/scheduled/body.ftlh.mjml
- src/main/resources/templates/email/observation/scheduled/body.txt.ftl
- src/main/resources/templates/email/observation/scheduled/subject.ftl
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- Email notification is sent to the relevant organization's Terraformation Contact *only*, if one exists
- There is no headline or web link in these notifications
- There are no in-app notifications for this use case
> SW-4258 Email notifications when end user schedules/reschedules an observation

- jooq/src/main/kotlin/com/terraformation/backend/jooq/PluralPojoStrategy.kt
If we define an embeddable type to represent a compound key, the generated POJO
class shouldn't have a Row suffix on its name because it doesn't represent a
table row.
Update the naming strategy to exclude embeddable types.
Currently, we don't have any places in the code where we're referring to these
classes by name; everywhere we use them, we use type inference. So no changes
to the application code are needed here. But this will be less confusing in
the future if/when we do need to refer to the type of a compound key.
> Stop adding Row suffix to embeddable POJOs

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- We want admins/owners/TFContact/superadmins alone to be able to schedule/reschedule observations
- The UI handles this gating currently
- ObservationService.scheduleObservation/rescheduleObservation functions were piggy-backing onto create/update observations permissions earlier (update permissions is a bit more relaxed)
- Updated the functions them to use new permissions checks for schedule/reschedule observations
- Updated the tests
> SW-4301 Refine permissions for schedule/reschedule observations

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
Planting site creation via shapefile upload now allows the zip archive to contain
an optional fourth shapefile. If present, the geometries in the fourth shapefile
are excluded from the site's geometry when monitoring plots are generated. In
other words, the fourth shapefile defines areas that aren't allowed to have
monitoring plots.
> SW-4307 Support exclusions in shapefile import

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/EmailService.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- TF Contact receives very specific email notifications as defined in the PRD
- Skip sending routine org email notifications to TF Contact users
- Refactored a couple notifications to use the `sendOrganizationNotification`
- Not sure how this current approach will ensure correctness for future email notifications
- Another option is to initialize this default roles list in the EmailService.sendOrganizationNotification function argument instead, future email notifications will by default skip TF Contacts unless explicitly passed into the roles
> SW-4279 Don't send org email notifications to Terraformation Contact users

- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ReplacementDuration.kt
- src/main/resources/i18n/Messages_en.properties
- src/main/resources/templates/email/observation/plotReplaced/body.ftlh.mjml
- src/main/resources/templates/email/observation/plotReplaced/body.txt.ftl
- src/main/resources/templates/email/observation/plotReplaced/subject.ftl
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Add an email notification that will be sent when the user replaces a monitoring
plot in an observation. Nothing triggers this notification yet.
> SW-4309 Send email on monitoring plot replacement

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ReplacementResult.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
`POST /api/v1/tracking/observations/{observationId}/plots/{plotId}/replace` will
request that a monitoring plot in an observation be replaced.
Currently this triggers an email notification to be sent to the organization's
Terraware contact (or to the support email if there's no contact) but does not
actually cause the plot to be replaced. However, the API definition can be used
for client-side code generation.
> SW-4308 Add API for replacing monitoring plot

- .github/workflows/main.yml
- build.gradle.kts
- docker/Dockerfile
- jooq/build.gradle.kts
Previously, we were targeting Java 19 with the build (because that was the newest
version supported by the Kotlin compiler at one point) and using Java 20 as the
runtime JVM.
Update the runtime to use Java 21, and the build to target Java 20.
No functional change (we aren't using any of Java 21's new features) but it
should give us some minor performance improvements.
> Use Java 21 runtime

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ShapefileFeature.kt
Property (column) names in shapefiles are truncated to 10 characters, and
originally we were creating map data with property names longer than that.
Change the shapefile importer to accept either the original truncated names
or new shorter ones that don't include the "planting" prefix.
> SW-4323 Allow alternate names for feature properties

- src/main/kotlin/com/terraformation/backend/customer/api/SubLocationsController.kt
In preparation for adding sub-locations to nursery facilities, add a new set of
endpoints similar to the ones under `/api/v1/seedbank/storageLocations`. There's
no new functionality here, just a different API that isn't specific to seed banks.
In keeping with our current API structure conventions, the PUT and POST endpoints
expect facility IDs in URL paths instead of in request payloads.
The response payloads have a field for the number of active batches. This will be
populated in a later code change but is there from the start so as to reduce API
churn.
> SW-3992 Add API endpoints for sub-locations

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationResultsModel.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationResultsStoreTest.kt
Currently, when it uploads photos of a permanent monitoring plot's four corners,
the mobile app includes GPS coordinates and an indication of which corner the
photo shows. But this information was write-only and couldn't be retrieved for
later display.
Return it as part of the list of an observed plot's photos.
> SW-4232 Return observation photo GPS information

- src/main/kotlin/com/terraformation/backend/customer/api/SubLocationsController.kt
Left this out of commit bfea4017. It won't be used initially for nursery
sub-locations, but is needed to support deleting seed bank sub-locations.
> SW-3992 Add sub-location delete endpoint

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/resources/templates/admin/index.html
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Allow super-admins to add a user to any organization from the admin UI.
This replaces the previous UI for adding a Terraformation contact, which required
the super-admin to be in the organization.
> SW-4324 Add user to any organization from admin UI

- src/main/resources/db/migration/0200/V216__FacilityNumberInIdentifiers.sql
Update the human-readable identifiers of accessions and batches to use the new
numbering scheme that includes the facility number.
Accessions with custom numbers from CSV uploads aren't updated, just ones whose
accession numbers match the old format.
DEPLOYMENT NOTE:
This should be deployed only after the code change to start generating new-style
identifiers has been deployed, so as to avoid any old identifiers slipping through
the cracks during deployment.
> SW-4329 Add facility numbers to existing identifiers

- src/main/kotlin/com/terraformation/backend/customer/api/FacilitiesController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsV2Controller.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreCreateTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreDatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
The API refers to sub-locations using the older name "storage locations." To
support making our terminology consistent, add sub-location fields to the
existing payloads that have storage location fields.
Both field names are supported for now; once the client code has been updated
to switch to the sub-location fields, the storage location fields will be removed.
> SW-4349 Add sub-location fields to existing payloads

- src/main/kotlin/com/terraformation/backend/customer/model/InternalTagIds.kt
- src/main/resources/db/migration/R__TypeCodes.sql
We're going to be adding system behavior that only applies to participants in
the Terraformation Accelerator. Add an internal tag so super-admins can indicate
which organizations are in the accelerator.
Nothing uses this new tag yet, but it will appear in the admin UI.
> SW-4361 Add internal tag for accelerator participants

- src/main/kotlin/com/terraformation/backend/nursery/BatchService.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchImporter.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/BatchModel.kt
- src/main/kotlin/com/terraformation/backend/seedbank/AccessionService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/api/TransfersController.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreCreateBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreFetchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStorePermissionTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreUpdateDetailsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
In preparation for adding some new attributes to seedling batches that won't map
to single column values, add model classes to replace the internal use of the
jOOQ-generated `BatchesRow` class.
> Add model classes for seedling batches

- src/main/kotlin/com/terraformation/backend/db/IdentifierGenerator.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/db/IdentifierGeneratorTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
For nursery transfers, we want the year and the sequence number of the new batch
to be carried over from the original batch, and we want plants to be added to any
existing batch that already has that batch number.
This replaces the previous logic that combined source batches of the same species
into a single destination batch.
> SW-4363 Derive destination batch number from original

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
If a batch was originally created via a nursery transfer from a seed bank, it will
have an accession ID indicating where it came from. If plants from the batch are
then transferred to a different nursery, the newly-created batch should have the
same accession ID so it can be traced back to its original seeds.
> SW-4365 Carry accession ID across nursery transfers

- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreChangeStatusesTest.kt
Calculating germination and loss rates will require that we distinguish between
the user overwriting the quantities of a batch and the user moving seedlings from
one status to another.
Add a new API endpoint `POST /api/v1/nursery/batches/{id}/changeStatuses` to move
seedlings between statuses. It causes a new type of quantity history entry to be
recorded, which will allow the germination and loss rate calculations to treat
status changes correctly.
> SW-4376 Add API to change batch statuses

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- Upcoming observations can be rescheduled
- Overdue or InProgress observations can be rescheduled only if they have no observed plots
- Completed observations cannot be rescheduled
> SW-4408 Change criteria for observations that can be rescheduled

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
Previously, we only included the withdrawal ID on the batch quantity history
entries for the originating batch, but not for the destination batch; there
was thus no easy way to tell which withdrawal was responsible for a quantity
change.
Update the withdrawal code to include the withdrawal ID in the quantity
history on both sides of nursery transfers.
> Record withdrawal IDs for incoming transfers

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreUpdateQuantitiesTest.kt
The web app has a single UI where both the non-quantity-related details and the
quantities can be edited, and when the user hits the save button, the app
updates both the details and the quantities even if the quantities didn't
actually change.
Currently, this results in a manual edit being recorded in the batch's quantity
history, which will show up as a line item in the history view once that's
implemented. Since the user didn't actually change the quantities, the line item
will be meaningless.
Add logic to detect and ignore no-op quantity edits.
> Ignore no-op batch quantity edits

- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/BatchModel.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreCreateBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreFetchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/AccessionServiceTest.kt
Calculate the total number of seedlings withdrawn from a batch and return it along
with the other batch details so it can be shown in the web app.
> Add totalWithdrawn to batch payload

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- config was used to support a gating flag to 'notify on first planting' for staging purposes
- we won't need this anymore, plan is to release the user scheduled notifications feature to production this week
- there will be a corresponding infra PR to remove the config value setting
> Remove observation config from TerrawareServerConfig

- src/main/kotlin/com/terraformation/backend/nursery/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/NurseryStats.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/SpeciesSummary.kt
- src/main/resources/db/migration/0200/V224__BatchRateTotals.sql
- src/main/resources/db/migration/R__Comments.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreChangeStatusesTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreDeleteBatchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreGetNurseryStatsTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreSpeciesSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreUpdateQuantitiesTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreWithdrawTest.kt
Return the aggregate germination and loss rates in the summary data for species
and for nursery facilities. This replaces the existing aggregate loss rate
calculation, which was less sophisticated than the current one.
To support calculating the aggregate numbers without having to walk through the
quantity history of every batch, the batches table now stores the numerators and
denominators of the batch-level rate calculations, such that the SQL query that
reads the aggregate stats can simply add them up and divide to get the aggregate
rates.
> SW-4418 Aggregate germination and loss rates

- src/test/kotlin/com/terraformation/backend/file/InMemoryFileStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchPhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
Previously, we were using MockK to stub out the file store in unit tests of photo
code. Replace it with a simple in-memory implementation so tests don't have to
configure the test doubles.
> Add in-memory FileStore for unit tests

- build.gradle.kts
- gradle.properties
Let Spring Boot's test starter pull in the version of JUnit it's compatible with.
This will prevent Renovate from attempting to upgrade JUnit to new versions that
aren't supported by Spring yet.
> Remove explicit JUnit dependency

- src/main/kotlin/com/terraformation/backend/nursery/api/NurseryFacilitiesController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/NurseryStats.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreGetActiveSpeciesTest.kt
Commit 5cebebf added calculations of facility-level stats such as loss rate, but
didn't expoise the results in the API. Add an endpoint clients can call to get a
summary of the plants at a nursery.
> Add nursery inventory summary endpoint

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
In preparation for adding planting site deletion to the admin UI, add a permission
for it. Initially, only super-admins will be allowed to delete planting sites.
> Add permission for deleting planting sites

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Implement the logic for deleting planting sites. Planting sites can have photos
(indirectly, by way of observations) which need to be deleted from the file store;
use the same event-listener-ba3ed deletion pattern we use for seedling batches and
withdrawals.
> Add delete function to PlantingSiteStore

- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/event/OrganizationTimeZoneChangedEvent.kt
- src/main/kotlin/com/terraformation/backend/customer/event/PlantingSiteTimeZoneChangedEvent.kt
- src/main/kotlin/com/terraformation/backend/tracking/PlantingSiteService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/customer/FacilityServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlantingSiteServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Add fields to the "time zone changed" events for organizations and planting sites
so listeners can tell what the change was.
Currently, nothing uses this, but it will be needed for planting season
notification scheduling.
> SW-4412 Include old and new time zones in events

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
We are no longer showing the admin-specified planting season start and end months
in the web app, so remove them from the API.
> SW-4469 Remove planting season start/end months from API

- build.gradle.kts
- gradle.properties
Let Spring Boot's web starter pull in the version of Jackson it's compatible with.
This will prevent Renovate from attempting to upgrade Jackson to new versions that
aren't supported by Spring yet.
> Remove explicit Jackson dependency

- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/test/kotlin/com/terraformation/backend/util/ExtensionsTest.kt
For planting season notifications, we'll need to convert the start/end dates to
the correct instants in the planting sites' time zones. Add an extension function
to do the conversion.
> Function to convert LocalDates to Instants

- src/main/kotlin/com/terraformation/backend/search/table/FacilityInventoryTotalsTable.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
Allow clients to query the total inventory by facility, but also get per-species
details for the inventory at each facility.
For example, to get a list of inventory totals with a list of species names, the
search request would look like:
{
"prefix": "facilities.facilityInventoryTotals",
"fields": [
"facility_id",
"facility_name",
"facilityInventories.species_scientificName",
"germinatingQuantity",
"notReadyQuantity",
"readyQuantity",
"totalQuantity",
"totalSpecies"
],
"search": {
"operation": "field",
"field": "organization_id",
"values": [ "123" ]
}
}
> Add per-species sublist to facility inventory totals

- src/main/kotlin/com/terraformation/backend/tracking/PlantingSiteService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlantingSiteServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
When a planting site's time zone changes, the start and end times (which are
`Instant`s) will no longer be correct since they were computed using the old
time zone; recalculate them in the new time zone.
> SW-4410 Update planting seasons on time zone change

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/resources/templates/admin/plantingSite.html
List the planting seasons (including past ones) in the admin UI, and use the
planting season dates to prefill the default dates for the next observation.
Current and future planting seasons can be edited and new ones can be created,
but past ones can't be modified.
This replaces the planting season start/end month fields.
> SW-4469 Show planting seasons in admin UI

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
We no longer expose the planting season start and end months in the API or the
admin UI; remove the code that accesses them in the database so we can drop the
columns.
> SW-4469 Stop accessing planting season months

- src/main/resources/db/migration/0200/V228__DropPlantingSeasonMonths.sql
We no longer access the planting season start and end months, so drop them from
the database.
> SW-4469 Drop planting season start/end months

- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/resources/templates/email/plantingSeason/rescheduled/body.ftlh.mjml
- src/main/resources/templates/email/plantingSeason/rescheduled/body.txt.ftl
- src/main/resources/templates/email/plantingSeason/rescheduled/subject.ftl
- src/main/resources/templates/email/plantingSeason/scheduled/body.ftlh.mjml
- src/main/resources/templates/email/plantingSeason/scheduled/body.txt.ftl
- src/main/resources/templates/email/plantingSeason/scheduled/subject.ftl
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
When a planting season is scheduled or rescheduled, send an email notification to
the organization's Terraformation contact, if any.
Unlike other notifications that go to organization contacts, these do not fall
back on the support mailing list if there is no contact.
> SW-4413 Notify on planting season scheduling

- .github/renovate.json5
Add the driver to the "database dependencies" Renovate group so it's upgraded
together with other database-related libraries if they change at the same time.
> Add PostgreSQL JDBC driver to database dependencies

- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/main/resources/db/migration/R__Indexes.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
- Enhanced SpeciesStore findAllSpecies to return in-use species controlled by an input arg
- Similar enhancement in SpeciesController list all species API
- Added tests
- I had originally separated out this functionality, seemed wasteful to have extra API/functions when we could extend the list all species API
> SW-4515 Add API functionality to return species that are used in the org

- src/test/kotlin/com/terraformation/backend/TestEventPublisher.kt
Add the ability to clear the event list to support asserting that no additional
events were published after a certain point.
Add an assertion method to check that no events were published.
Allow callers to pass custom messages to the assertion methods.
> Improve TestEventPublisher

- src/main/kotlin/com/terraformation/backend/daily/PlantingSeasonScheduler.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/test/kotlin/com/terraformation/backend/TestEventPublisher.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Add a scheduled job that transitions planting seasons into and out of active state
as their start and end times arrive. Each transition generates an application
event which will be used to trigger notifications.
> SW-4412 Mark planting seasons as active/inactive

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/PlantingSubzonePopulationsTable.kt
Commit c9ae259d replaced `plot_populations` with `planting_subzone_populations`.
There was an embedded type defined for `plot_populations` to represent its
compound primary key, but it wasn't replaced with one for the new table.
Update the embedded type and use it in the subzone populations search table;
the incorrect primary key on that table could have resulted in incorrect search
results, though luckily the web app isn't currently doing any searches that
would trigger the problem.
> Use compound primary key for subzone populations

- build.gradle.kts
- buildSrc/src/main/kotlin/com/terraformation/gradle/PostgresDockerConfigTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderGibberishTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderMjmlTask.kt
- buildSrc/src/main/kotlin/com/terraformation/gradle/VersionFileTask.kt
- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- jooq/src/main/kotlin/com/terraformation/backend/jooq/PluralPojoStrategy.kt
- jooq/src/main/kotlin/com/terraformation/backend/jooq/TerrawareGenerator.kt
Previously, the `spotlessApply` and `spotlessCheck` tasks only looked at the
source files in the main module. Configure it to look at all the files in the
project including the ones in `buildSrc` and `jooq`.
> Enable ktfmt for buildSrc and jooq modules

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- jooq/src/main/kotlin/com/terraformation/backend/jooq/EnumTable.kt
In preparation for adding a flag to generated enums to control whether or not
their display names should be localizable, update the enum configuration to
use the primary constructor everywhere. The secondary constructors existed solely
to avoid having to use `listOf()` for single-use enums, but the minor cleanliness
gain will mostly go away once the call sites need a localization-related
parameter.
> SW-4514 Remove EnumTable secondary constructors

- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/NotificationCriteria.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/daily/PlantingSeasonSchedulerTest.kt
For accelerator participants, we want to notify their Terraformation project
contacts if they still haven't set up planting seasons 2 weeks after we send
the second in-app notification about it.
Add logic to publish the required notification events.
This doesn't actually send the notifications; those will be added in a later
change.
> SW-4414 Generate events for accelerator planting seasons

- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/resources/templates/email/plantingSeason/notScheduledSupport/body.ftlh.mjml
- src/main/resources/templates/email/plantingSeason/notScheduledSupport/body.txt.ftl
- src/main/resources/templates/email/plantingSeason/notScheduledSupport/subject.ftl
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Send email (but not in-app) notifications to the organization's Terraformation
project contact, or to the support mailing list, if they haven't set up a planting
season after being reminded to do so in-app.
Since these notifications are internal-only, their English content is included
directly in the email templates rather than looked up in the string table.
> SW-4414 Send accelerator planting season email

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/file/FileService.kt
- src/test/kotlin/com/terraformation/backend/file/FileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchPhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/WithdrawalPhotoServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportFileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/PhotoRepositoryTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
For debugging photo format issues in the mobile app, it'll be helpful to be
able to examine files that failed the format validation check. Add a config
option to skip deleting invalid files.
We'll enable the option in staging but keep the default behavior in prod.
> Add config option to keep invalid photos

- build.gradle.kts
CI docs jobs started timing out because Dokka's memory consumption grew to the
point where it was stuck doing constant full GCs.
Dokka's memory usage, unsurprisingly, goes up the more classes/functions it's
generating docs for.
We were generating HTML docs for all the Kotlin code including jOOQ-generated
classes, but the docs for those classes aren't really useful since they never have
any human-written comments.
Dokka docs include a version identifier, and by default it uses the module version
from the Gradle config. In our Gradle setup, this includes a git commit hash,
meaning that on every code commit, all the Dokka files were being modified. This
caused the revision history on the `gh-pages` branch to be less useful; every
commit touches every Dokka-generated file.
Update the Dokka …
> Reduce Dokka resource consumption

- src/main/kotlin/com/terraformation/backend/report/api/PayloadsV1.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/kotlin/com/terraformation/backend/report/model/Reports.kt
- src/main/resources/db/migration/0200/V231__ReportProjects.sql
- src/main/resources/db/migration/R__Comments.sql
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
Update the database schema to allow project-specific reports.
The logic for writing the reports and for populating them with the correct
information will follow in other changes.
> SW-3937 Add project ID, name to reports

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/test/kotlin/com/terraformation/backend/report/ReportFileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
Reports are created by the system at the start of each quarter. Add logic to
create project-level reports alongside the existing org-level ones.
The logic to only populate the project-level reports with project-level data
will follow in another change.
> SW-3937 Create project-level reports

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/api/PayloadsV1.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/main/kotlin/com/terraformation/backend/seedbank/model/AccessionSummaryStatistics.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
Add server-populated fields to the nursery and seed bank report body models to
hold the number of plants propagated and the number of seeds stored for a
project. The existing fields with the overall totals remain unchanged, and for
org-level reports, the new fields have null values.
> SW-3937 Add project-only total plants and seeds

- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/main/kotlin/com/terraformation/backend/customer/event/ProjectRenamedEvent.kt
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
To support freezing the project names in per-project reports when they are
submitted, but using the latest project names in reports that haven't been
submitted yet, the reports code will need to know when projects are renamed.
Publish an application event when a project is renamed.
> SW-4534 Publish event when project is renamed

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
We want project-level reports to be labeled with the project names as of the time
the reports were submitted, even if the projects are later renamed.
Apply project renames to unsubmitted reports.
> SW-4534 Track project renames in reports

- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/main/kotlin/com/terraformation/backend/customer/event/ProjectDeletionStartedEvent.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
When a project is deleted, it no longer makes sense for people to submit
project-level reports for them, but we want to keep any reports that have already
been submitted.
> SW-3937 Delete reports when project is deleted

- KEYCLOAK.md
- docker/keycloak-docker-compose.yml
Use Keycloak 19 in the example docker-compose configuration (that's the version
we're currently using in production) and update the setup documentation to reflect
the changes in Keycloak's admin UI.
Closes #1568
> Update Keycloak documentation

- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/terraformation/backend/db/TimeZonePopulator.kt
- src/test/kotlin/com/terraformation/backend/device/db/TimeseriesStoreTest.kt
Switch to the latest open-source jOOQ release and to the Gradle plugin that
supports it by default.
3.19.0 includes a breaking API change related to inserting lists of records;
update the code accordingly.
> Upgrade to jOOQ 3.19.0

- src/main/kotlin/com/terraformation/backend/db/GeometryBinding.kt
- src/main/kotlin/com/terraformation/backend/db/GeometryUtil.kt
We use a custom class for PostGIS geometry columns, and we have a converter that
plugs into jOOQ so it uses our class when reading and writing those columns.
When we were constructing a custom jOOQ `Field` object, we were telling jOOQ to
look up the converter for our class in its global list of converters. That pattern
is being deprecated per https://github.com/jOOQ/jOOQ/issues/15286 because it can
cause undefined behavior. The existing code still works, but causes jOOQ to log
warning messages.
Update our custom field construction to explicitly specify the converter it needs.
> Fix jOOQ deprecation warning

- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/OrganizationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/FacilityStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/NotificationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/WithdrawalStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreHistoryTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Allow tests to insert users more succinctly when they need the user IDs
afterwards. Update existing tests to get the user IDs from the insert function
rather than declaring them separately.
`insertUser()` now allows passing in a null user ID to let the database
allocate a new one, but existing tests don't use that feature yet in order to
avoid potential problems with ID collisions. The default is still to use the
user ID from the active security context.
> Return user ID from DatabaseTest.insertUser()

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Add a new `canUpdateGlobalRoles` permission, currently only true for super-admins,
to control the ability to add and remove users' global roles. Global roles will
replace the Super-Admin user type with a more flexible system.
> SW-4599 Add permission for updating global roles

- README.md
- src/main/kotlin/com/terraformation/backend/api/SuperAdminInterceptor.kt
- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationUsersTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/UsersTable.kt
- src/main/resources/db/migration/0200/V233__DropSuperAdminType.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Add the Super-Admin global role to users with the Super-Admin user type, convert
the users to regular individual users, and remove the user type.
Update all the references to the user type in the code to instead check for the
presence of the global role.
> SW-4600 Replace Super-Admin user type with global role

- src/main/resources/db/migration/0200/V233__DropSuperAdminType.sql
Migration 233 assumed that the global roles table was already populated, but that
won't be the case if it is deployed at the same time as migration 232 since the
roles are inserted in `R__TypeCodes.sql` after the numbered migrations.
> Fix global role migration

- src/main/resources/i18n/Messages_en.properties
- src/test/kotlin/com/terraformation/backend/i18n/PropertiesFilesTest.kt
ASCII apostrophe characters are special in properties files and have to be doubled
to escape them. But some text editors "helpfully" detect pairs of apostrophes and
turn the second one into a closing single quote mark. Then Phrase, or other
software, notices the remaining apostrophe and doubles it again, such that we end
up with strings that have an ASCII apostophe and a single quote together.
We also had a couple sentences that should have used the word "its" but instead
used "it’s."
Remove the unnecessary single quote characters and add a test to catch the problem
in the future.
> SW-4595 Fix incorrect apostrophes

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
Our convention is to import JUnit assertion functions individually rather than
importing their containing class.
> Use imported assertion functions in tests

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
`PermissionRequirementsTest.createObservation` was constructing a function to run
the test case when it should directly run the test case.
> Fix malformed test case

- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreCalculationsTest.kt
If all the germinating seedlings in a batch were withdrawn with a withdrawal
purpose other than Dead, the code was trying to divide by zero when calculating
the batch's germination rate.
> SW-4609 Fix germination rate calculation error

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/search/table/InventoriesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/NurserySpeciesProjectsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/SearchTables.kt
- src/main/kotlin/com/terraformation/backend/search/table/SpeciesTable.kt
- src/main/resources/db/migration/0200/V234__NurserySpeciesProjects.sql
- src/main/resources/db/migration/R__Comments.sql
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
Add a new search table so clients can query which projects have active batches of
a particular species. This differs from the existing ability to query the project
for each batch in that a given project is only returned once even if it is
associated with multiple batches. Empty batches are not counted.
Example `POST /api/v1/search` request payload to return the list of project names
and IDs for species 123 along with its inventory totals:
{
"prefix": "inventories",
"fields": [
"germinatingQuantity",
"notReadyQuantity",
"readyQuantity",
"totalQuantity",
"projects.id"
"projects.name"
],
"search": {
"operation": "field",
"field": "species_id",
"values": ["123"]
}
}
> SW-4573 Nursery species projects search table

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/index.html
The admin UI home page has links to the pages for administering device managers.
Device managers can only be administered by super-admins, so these links are
useless for accelerator admins. Add permission checks to hide them.
> Hide device manager links from accelerator admins

- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
If an observation is in progress but no plots are completed yet, we let admins
reschedule it for a future date. Get rid of the initial plot assignments so as
to calculate a fresh set of plots based on the state of the planting site on
the new start date.
> SW-4673 Unassign plots when observation rescheduled

- src/main/kotlin/com/terraformation/backend/report/api/ReportsSettingsController.kt
The response payload for the `GET /api/v1/reports/settings` endpoint wasn't
including the standard `status` field.
> Include status field in report settings response

- src/main/kotlin/com/terraformation/backend/admin/AdminController.kt
AdminController is getting big and it will be easier to maintain if it's split
into smaller classes. It's currently under the "customer" package which is
supposed to be for code related to managing users, organizations, and such, but
most of the admin UI's functionality is related to other things.
Move it to a new "admin" package.
> Move AdminController to its own package

- src/main/kotlin/com/terraformation/backend/admin/AdminController.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminControllerAdvice.kt
- src/main/kotlin/com/terraformation/backend/admin/Extensions.kt
In preparation for splitting AdminController into multiple classes, move some
configuration code and some helper extension properties out of it so they can
be shared across all the controller classes.
> Move common code out of AdminController

- src/main/kotlin/com/terraformation/backend/admin/AdminController.kt
- src/main/resources/templates/admin/appVersions.html
- src/main/resources/templates/admin/deviceManager.html
- src/main/resources/templates/admin/deviceTemplates.html
- src/main/resources/templates/admin/facility.html
- src/main/resources/templates/admin/globalRoles.html
- src/main/resources/templates/admin/index.html
- src/main/resources/templates/admin/internalTag.html
- src/main/resources/templates/admin/listDeviceManagers.html
- src/main/resources/templates/admin/listInternalTags.html
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/admin/plantingSite.html
- src/main/resources/templates/admin/plantingSiteMap.html
- src/main/resources/templates/admin/testClock.html
When the admin UI was first written, we wanted to allow for the possibility that
the frontend web server would do URL rewriting to expose it at a different path.
We thus needed to be able to easily change the path that was included in links
and form actions.
This has turned out not to be needed. Passing the prefix around and using it
everywhere adds noise to the templates and the controller classes.
Update AdminController to stop including the prefix in the models that get passed
to the templates, and update the templates to directly use `/admin` in their URL
paths. In many cases, this means attributes such as `href` can be string literals
instead of Thymeleaf expressions.
> Hardwire admin UI URL prefix

- src/main/kotlin/com/terraformation/backend/customer/db/InternalTagStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/InternalTagStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
To show the list of available projects that can be added to a participant in the
admin UI, accelerator admins need to be able to query the list of organizations
with the "Accelerator" internal tag. Add a separate read permission for internal
tags.
> SW-4603 Accelerator admins can read internal tags

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/daily/PlantingSeasonScheduler.kt
- src/test/kotlin/com/terraformation/backend/daily/PlantingSeasonSchedulerTest.kt
User-editable planting seasons have launched in production, so we want to start
sending notifications to tell people to create them. Remove the config option
that was suppressing the notifications in production.
> SW-4593 Remove planting season notification feature flag

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
A few of the variables that keep track of the internal state of the test had names
that included "Id" (because they are entity IDs) but most didn't. Make them
consistent.
> Use consistent variable names in PermissionTest

- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
In preparation for changing how monitoring plot allocation works, change the
assertions in the monitoring plot allocation test case in ObservationServiceTest
so they check for valid geometric relationships between the plots and the
subzones rather than checking for specific plot IDs.
The setup part of the test will need to change when the plot allocation code
is revamped, but the assertions should be able to remain untouched, such that we
can verify that the same requirements are being met before and after the change.
To make geometry-based tests like this one easier to read and write, add
convenience arguments to the planting site/zone/subzone/monitoring plot insert
functions in DatabaseTest to allow boundaries to be defined in terms of origin
point and width/height.
> SW-4716 Test plot positions in ObservationServiceTest

- src/main/resources/db/migration/0200/V240__BackfillSeedbankWithdrawalsBatchId.sql
- src/main/resources/db/migration/0200/V241__WithdrawalsBatchIdIndex.sql
Migration to backfill the `batch_id` into the accession withdrawals table hinges on the `created_time` check, which I have truncated to seconds and given it a 2 second window since they are not created at the exact same time. 
@sgrimm let me know what you think, I think 2 seconds might be too high but there is a chance that the withdrawal was created at the end of the previous second and the batch at the beginning of the next second. Hopefully the other checks are sufficient to make the chance that an incorrect batch ID is applied impossible.
> SW-4649 Backfill batch ID into seedbank withdrawals

- src/main/kotlin/com/terraformation/backend/db/SRID.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ShapefileGenerator.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
In preparation for changing how monitoring plot allocation works such that plots
are no longer generated all at once at site creation time, add a new test that
checks that a site imported from a given set of shapefiles will result in an
observation whose monitoring plots obey the plot selection rules.
To further verify the existing plot creation behavior, add tests to confirm that
the existing shapefile import code creates the correct number of monitoring plots;
previously there was no test coverage for that part of the import process.
> SW-4716 Improve monitoring plot placement tests

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
In preparation for supporting on-demand creation of monitoring plots, move the
logic for selecting permanent clusters for an observation to `PlantingZoneModel`.
Cluster selection is now done completely in the application code rather than via
a database query.
No change in behavior is introduced here; the plot selection logic is already
covered by `ObservationServiceTest` and `PlotAssignmentTest` which continue to
pass.
> SW-4731 Move permanent plot selection to PlantingZoneModel

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
Return the global roles for the user in the GET /me API call response, the front end will use these roles to determine what things they can / can't see with regard to the accelerator admin area of the site.
> SW-4774 Add user's global roles to the API response for GET /me

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/util/Turtle.kt
- src/test/kotlin/com/terraformation/backend/Turtle.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
In preparation for creating monitoring plots on demand, add logic to randomly
select an available grid-aligned square region in a planting zone.
> SW-4731 Logic for random on-demand plot selection

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
`PlantingSiteStore.ensurePermanentClustersExist()` will, as its name suggests,
ensure that the required number of permanent clusters exist in each of a site's
planting zones, creating new monitoring plots or adding existing temporary plots
to clusters as needed.
For existing planting sites, this is a no-op because a full set of permanent
clusters is created at shapefile import time and this function thus has no work
to do, but future updates will get rid of the import-time plot creation and will
require this logic to be in place.
> SW-4731 Create missing permanent clusters

- src/main/kotlin/com/terraformation/backend/search/field/IdWrapperField.kt
- src/main/kotlin/com/terraformation/backend/search/table/BatchesTable.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
`IdWrapperField` wasn't handling null search values like the other field classes
do; it needs to ad an `IS NULL` condition if the list of exact search values
includes a null. This was causing us to be unable to search for batches that
aren't associated with projects.
> SW-4791 Allow searching for null IDs in sublists

- .github/renovate.json5
The Renovate config file uses the keyword `matchFileNames` for rules that match
based on the name of the package file. We were using `matchPaths` which caused
our Node and Python package updates to be generated individually rather than
grouped together as intended.
> Use correct Renovate keyword for grouping

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/util/Turtle.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
The initial iteration of plot selection used a meter-based coordinate system
to calculate the grid positions of monitoring plots. Depending on the size and
location of a site, this could result in adjacent plots having a tiny amount
of overlap (on the order of 0.1% of their area) or a tiny gap in between them.
This wouldn't have meaningfully affected survey results, but it was visually
obvious when zooming in on the map.
In addition, the initial iteration was using `GeodeticCalculator` to trace the
edges of plots by moving along cardinal compass directions. That caused slight
inconsistencies because `GeodeticCalculator` calculates great-circle paths
rather than rhumb-line paths, meaning that moving "east" could cause both the
longitude and the latitude to change.
Get rid of the …
> SW-4732 Use more precise grid points for plots

- src/main/resources/templates/admin/plantingSiteMap.html
Once monitoring plots are created on demand, there will no longer be a grid of
them covering the entire planting site; instead they will be scattered around an
otherwise empty map. For the kinds of very large planting sites we sometimes
create during testing, this makes them hard to see on a fully zoomed-out map.
Add a "Light/Dark" button to the admin UI's planting site map viewer that toggles
between the default satellite-photo map and a dark one.
In addition, for temporary and permanent plots, put the plot borders in their own
map layers that are rendered as outlines rather than using the "fill" layer's
outline color option. On zoomed-out maps, Mapbox completely hides small polygons
that are rendered as "fill" layers, but renders "line" layers as single pixels;
this makes it possible to …
> Add light/dark toggle to admin UI map viewer

- src/main/kotlin/com/terraformation/backend/search/table/DraftPlantingSitesTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/OrganizationsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/ProjectsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/SearchTables.kt
Allow clients to search for draft planting sites using whatever filter criteria
they need. Only the statically-defined fields are searchable; to fetch the opaque
data for a draft planting site, fetch it using the drafts `GET` endpoint.
Example payload for `POST /api/v1/search` to search for drafts in organization
12345:
{
"prefix": "draftPlantingSites",
"fields": [
"createdBy_id",
"description",
"id",
"name",
"numPlantingSubzones",
"numPlantingZones",
"timeZone"
],
"search": {
"operation": "field",
"field": "organization_id",
"values": [12345]
}
}
> SW-4832 Add draft planting sites to search API

- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
The helper functions that insert planting sites and their child regions can
calculate boundaries based on position and size arguments. Change the functions so
that those arguments are interpreted as multiples of the monitoring plot size
rather than as raw coordinate values.
`ObservationServiceTest` uses a combination of these functions and explicit
construction of a multipolygon, so update it accordingly and, as was done in
`PlantingZoneModelTest`, change the way it asserts that a monitoring plot is
contained in a subzone to allow for floating-point rounding errors.
> Use grid intervals for default boundary polygons

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/UnusedSquareFinder.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
For user-defined planting zone boundaries, we'll want to validate that the
boundaries are large enough to hold monitoring plots before inserting the zone
data into the database.
Ideally, we wanto to do that using the same "find a plot location" algorithm
that's used in real observations. That code is currently in `PlantingZoneModel`
which can only represent planting zones that exist in the database.
Move the zone search logic into a helper class `UnusedSquareFinder`.
This is mostly a straight copy-paste of the existing implementation, with the
following changes:
- The logic for excluding existing monitoring plots now lives in
`findUnusedSquares` since it was only ever used via that function anyway.
This requires changing the unit test for that functionality.
- The various functions that …
> SW-4802 Move findUnusedSquare to helper class

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Shapefile.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/ShapefileTest.kt
Our in-memory representation of shapefile data included a textual "data type"
value but we weren't using it for anything except to test that it was populated
correctly. Remove it.
> Remove unused field from Shapefile class

- src/main/resources/templates/admin/plantingSite.html
Commit c3c49c00 removed the localized display names from a bunch of enums
including observation state, but the admin UI was still trying to resolve
the localized name when showing the table of observations for a planting site.
This caused the page rendering to bomb out and return a partial page.
Show the enum's name instead.
> SW-4910 Fix observation states in admin UI

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- src/test/kotlin/com/terraformation/backend/api/OpenApiAnnotationTest.kt
To allow clients to start coding against the API, define the endpoints for listing
and fetching deliverable data.
Currently, these endpoints all return dummy responses.
> SW-4934 Define read endpoints for deliverables

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
The "list deliverables" endpoint had OpenAPI annotations to document its
parameters, but was missing the annotations to tell Spring to populate them
with values.
> Declare request parameters as request parameters

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- src/main/resources/db/migration/0200/V247__DeliverableTweaks.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
Update the data model based on requirements changes/clarifications:
- Deliverables no longer have subtitles.
- We need to store the original filenames of submission documents.
- The initial list of deliverable categories was a placeholder; use the list
that will be used in the deliverables spreadsheet.
Also add a missing primary key constraint to `deliverable_documents`.
> Minor deliverable data model changes

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Add permissions for managing the list of modules and the list of deliverables.
Both of them require either the Accelerator Admin or the Super-Admin global role.
> SW-4937 Module and deliverable management permissions

- src/main/kotlin/com/terraformation/backend/accelerator/db/DeliverablesImporter.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ModulesImporter.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminController.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminModulesController.kt
- src/main/kotlin/com/terraformation/backend/importer/ProcessCsvFile.kt
- src/main/resources/templates/admin/index.html
- src/main/resources/templates/admin/modules.html
Add a page to the admin UI to allow admins (Accelerator Admin and Super-Admin)
to upload the spreadsheets that define the lists of modules and deliverables.
> SW-4937 Upload modules and deliverables CSVs in admin UI

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- the projectId was defined as a multipart/form-data request part but it's type was ProjectId, led to unsupported MediaType errors
- fix is to either set the schema for projectId to be "int64" and convert to ProjectId inside the function
- instead moved projectId to the path as a PathParam as this is our common practice
> SW-4962 Fix document upload endpoint API to accept projectId as a path param

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- Use String type for payload, IdWrapper supports string arguments in the constructor, here it will get converted into a ProjectId (if valid)
- Revert previous change of sticking projectId in the path
> SW-4962 Redo projectId type in document upload endpoint

- src/main/kotlin/com/terraformation/backend/admin/AdminParticipantsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/resources/db/migration/0200/V248__ProjectDocumentSettings.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/templates/admin/participant.html
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
When documents are uploaded for accelerator projects, they need to be stored in
project-specific locations and have a project-specific element added to their
filenames. Add a table to store those settings, and allow them to be edited from
the list of a participant's projects in the admin UI.
> SW-4958 Add per-project document storage settings

- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- Add a permission check for `canUpdateSpecificGlobalRoles` which takes a set of roles. Since the permissions are based on the roles that are being updated, we check them individually against the current user's authorization.
- I left the `canUpdateGlobalRoles` permission as a "super admin fallback", in the event no roles are passed (for deleting all roles). It is also used in the admin UI for checking whether or not to show the global role UI. I think this will eventually get removed and we can decide if this permission is still needed then.
> SW-4835 Add permissions for ability to set specific global roles

- KEYCLOAK.md
- src/main/kotlin/com/terraformation/backend/search/SearchExceptions.kt
- src/main/kotlin/com/terraformation/backend/search/SearchTable.kt
- src/main/kotlin/com/terraformation/backend/search/api/SearchController.kt
- src/main/kotlin/com/terraformation/backend/search/field/AgeField.kt
- src/main/kotlin/com/terraformation/backend/search/field/AliasField.kt
- src/main/kotlin/com/terraformation/backend/search/field/BigDecimalField.kt
- src/main/kotlin/com/terraformation/backend/search/field/BooleanField.kt
- src/main/kotlin/com/terraformation/backend/search/field/DoubleField.kt
- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
- src/main/kotlin/com/terraformation/backend/search/field/IntegerField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LocalizedTextField.kt
- src/main/kotlin/com/terraformation/backend/search/field/LongField.kt
- src/main/kotlin/com/terraformation/backend/search/field/NumericSearchField.kt
- src/main/kotlin/com/terraformation/backend/search/field/SearchField.kt
- src/main/kotlin/com/terraformation/backend/search/field/WeightField.kt
Added an exportable variable the defaults to `true`. If a search field is converted to its raw form, it will set exportable to `false`.
If a raw search field is requested for a csv export, it will throw an Exception, that results in a 400 Bad Request error.
Due to the CSV text format, it may look like the following instead of a JSON:
```
"status","message"
"error","The search field is not exportable"
```
Tests not added yet. Will set up test suite for the entire Search API in a separate PR.
> SW-4655: Added exportable check to SearchField.

- build.gradle.kts
- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/document/DropboxReceiver.kt
- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/file/DropboxWriter.kt
- src/test/kotlin/com/terraformation/backend/file/DropboxWriterExternalTest.kt
Add support for uploading submitted documents for sensitive deliverables to
Dropbox instead of Google Drive.
Requires valid Dropbox API credentials with the appropriate permissions.
> SW-4876 Implement Dropbox submission document storage

- DROPBOX.md
Add a document that describes how to get Dropbox API credentials for testing
(or deploying) sensitive submission document uploads.
> Document Dropbox API setup

- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/file/DropboxWriter.kt
- src/main/kotlin/com/terraformation/backend/file/GoogleDriveWriter.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/file/DropboxWriterExternalTest.kt
Generate URLs for documents on Google Drive and Dropbox, and redirect to them from
`GET /api/v1/accelerator/deliverables/{deliverableId}/documents/{documentId}`.
This is only available for users with Super-Admin, Accelerator Admin, TF Expert,
or Read Only global roles.
> Implement submission document redirect endpoint

- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/SubmissionStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/SubmissionModel.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/SubmissionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- Add a `fetchOneById` function to the `submissionStore` which fetches the submission and any associated submission documents.
- I had to add `insertSubmission`, `insertDeliverable`, and `insertModule` test database functions in order to test out the `fetchByOneId` function.
- Add `canReadSubmission` permission, available to all global roles and members of the submission's project's organization
> Add fetchOneById method to SubmissionStore

- src/main/kotlin/com/terraformation/backend/accelerator/event/DeliverableStatusUpdatedEvent.kt
- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
When a submission goes from "In Review" to "Needs Translation" or back, the change
isn't visible to end users. Suppress the notifications in that case.
Include the project ID in the application event since there can be multiple
projects in the same organization that submit the same deliverable.
> SW-5000 Don't notify about "Needs Translation" status

- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
Replace a few multi-condition global role checks with calls to the "X or higher"
helper methods, including a new "TF Expert or higher" one.
No behavior change here; it's purely aesthetic.
> Use "or higher" methods in IndividualUser

- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Internal users will need to be able to get an overview of all deliverables for all
projects; add a global permission for it.
> SW-4952 Add permission to read all deliverables

- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/event/DeliverableReadyForReviewEvent.kt
- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/customer/model/ProjectModel.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
When a user uploads a document for a deliverable, notify the appropriate
internal users that the deliverable is ready for review.
Currently, each uploaded document will trigger a notification.
> SW-5007 Notify when deliverable documents are uploaded

- src/test/kotlin/com/terraformation/backend/accelerator/db/CohortStoreTest.kt
The test was checking for a specific ID being created but wasn't resetting the
ID sequence on the table, so if another earlier test inserted into the same table,
this test would fail.
We don't actually care which specific ID is used, so fix the test by ignoring the
ID entirely when asserting that the expected values were inserted into the
database.
> Fix CohortStoreTest

- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionNotifier.kt
- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/event/DeliverableDocumentUploadedEvent.kt
- src/test/kotlin/com/terraformation/backend/accelerator/SubmissionNotifierTest.kt
To avoid flooding accelerator admins with notifications when users upload multiple
documents in rapid succession to satisfy deliverables, defer the "deliverable
ready for review" notification until 5 minutes have passed without a new upload
for the deliverable.
> SW-4991 Wait for more documents before notifying

- src/main/kotlin/com/terraformation/backend/accelerator/db/DeliverableStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/DeliverableStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
The permission checks for reading deliverables and submissions required the user
to be a member of the organization whose projects were being queried, and also
allowed contributor users to read deliverable data.
Add permissions for deliverable reading that allow access by internal users with
the appropriate global roles but not organization users with contributor roles.
> SW-5022 Allow internal users to read deliverables

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectVotesController.kt
- observed candidates for rename when I synced FE with project votes API types
- renamed user to userId for consistency
- set project votes payload in a root property so it can be extracted without cherry picking properties (consistent with existing pattern in other API)
> Rename a few project votes API payload properties

- src/main/resources/application.yaml
We need to allow larger deliverable documents to be uploaded. Increase the request
and multipart file size limits to 200MB to cover the expected files with a
comfortable margin.
> SW-5059 Increase request size limit to 200MB

- src/main/kotlin/com/terraformation/backend/admin/AdminParticipantsController.kt
- src/main/resources/templates/admin/participant.html
When adding a project to a participant in the admin UI, require the admin to
configure the project's document storage settings. This guards against cases
where users upload documents to a project that doesn't have storage settings yet.
The settings might still be wrong, and it's still possible to delete them at the
database level, but requiring them in the admin UI should make it harder to
misconfigure a project by mistake.
> SW-5061 Require document storage settings

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectScoresController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/PhaseChecker.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ProjectScoreStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/VoteStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ProjectScoreModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ProjectScoreStoreTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/VoteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Add real implementations of the `/api/v1/accelerator/projects/*/scores`
endpoints.
This also simplifies the payload definitions, removing response fields that
wouldn't be used by clients.
> SW-5035 Implement project score logic

- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Only send notifications about deliverables being ready for review to users with
the TF Expert global role.
A user with a Super Admin or Accelerator Admin global role can still receive
notifications if they also have the TF Expert global role.
> SW-5069 Only notify TF Experts about deliverables

- src/main/kotlin/com/terraformation/backend/accelerator/VoteService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/CohortStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/PhaseChecker.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/VoteStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/event/CohortParticipantAddedEvent.kt
- src/main/kotlin/com/terraformation/backend/accelerator/event/CohortPhaseUpdatedEvent.kt
- src/test/kotlin/com/terraformation/backend/accelerator/VoteServiceTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/CohortStoreTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
We want the list of voters to automatically be populated for the participant
projects that are eligible for voting in a particular phase.
Add logic to automatically populate the projects' voter rosters with the list
of default voters when:
- A project is added to a participant that is already in a cohort.
- A participant that already has projects is added to a cohort.
- A cohort moves to a new phase.
> SW-5058 Auto-assign default voters

- .github/workflows/main.yml
There are some properties in the OpenAPI schema that always differ between staging
and a local server instance, but they aren't important for purposes of seeing how
a given code change affects the API. Add a filter to remove those values from the
YAML files before diffing.
> Omit irrelevant changes from OpenAPI diff

- src/main/kotlin/com/terraformation/backend/admin/AdminGlobalRolesController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/GlobalRolesController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- Add API `DELETE /api/v1/globalRoles/users` for bulk removing global roles from a given set of user IDs
- Receives a payload of `{"userIds: [$userId1,$userId2]}`
- Update the `UserStore.updateGlobalRoles` function to accept a list of userIds to perform the operation on.
- The operation is considered "all or nothing", IE no users supplied in the list will be updated if there is an error with any of them (for example if some of the users are not `@terraformation.com` users)
> SW-5047 API for bulk removing global roles from users

- src/test/kotlin/com/terraformation/backend/i18n/SearchFieldDescriptionsTest.kt
Similar to commit ab12043c, make SearchFieldDescriptionsTest include a list of
missing properties file lines in its assertion failure message so it's easier
to fill in the missing entries.
> Make SearchFieldDescriptionsTest more useful

- src/main/kotlin/com/terraformation/backend/customer/api/OrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Allow users with the Super-Admin global role to read all organizations and all
projects, and allow users with the other global roles to read organizations with
the Accelerator internal tag and their projects.
Currently, this does not allow read access via the search API, only via the
dedicated GET endpoints for organizations and projects. It also doesn't grant
read access to other entities such as batches or accessions, just the basic
data (name, etc.) of the organizations and projects.
> SW-5089 Global roles grant limited read access

- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Most of the `expect` methods had alphabetically-sorted arguments, but a few of
them had arguments organized by entity type. Change all of them to use
alphabetical order for consistency, and reorder the assertions so they continue
to be in the same order as the arguments.
No changes to the test logic here, just sorting of the argument lists and
assertions.
> Sort PermissionTest arguments consistently

- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ParticipantModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantStoreTest.kt
Previously, ParticipantStore could only update the cohort ID after participant
creation. Change it to allow a participant to be created directly in a cohort.
> Allow participant to be created in a cohort

- src/main/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStore.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStoreTest.kt
- `ProjectAcceleratorDetailsStore.fetchOneById` was selecting multiple rows and causing the query to fail
> Fix `ProjectAcceleratorDetailsStore.fetchOneById`

- src/main/resources/db/migration/R__TypeCodes.sql
- There was an extra space in there
- Nothing is using the data yet so no other migration considerations are needed.
> Fix 'East Asia & Pacific' region name

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/UnusedSquareFinder.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/main/kotlin/com/terraformation/backend/util/Turtle.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
Currently, temporary plots are selected by picking entries from the complete list
of potential plots that gets created during shapefile import.
Switch to a geometry-based selection process instead, where plot locations are
selected on a map and then mapped to existing plot IDs if the plots have already
been inserted into the database.
Currently, we still create all the potential plots during shapefile import, so the
selected plots will always already exist. But this moves us one step closer to
being able to skip creating the plots ahead of time.
> SW-4732 Select temporary plots using site map

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
When an observation starts and temporary plot boundaries are selected on the site
map, create new monitoring plots in the database for any boundaries that aren't
already there.
For existing planting sites, this is a no-op because all possible plot boundaries
are inserted into the database at shapefile import time. But future updates will
get rid of the import-time plot creation to better support editing maps after site
creation.
This is analogous to commit 14d90e78c which added on-demand cration of permanent
clusters.
> SW-4732 Create missing temporary plots

- src/main/kotlin/com/terraformation/backend/accelerator/AcceleratorProjectService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/AcceleratorProjectModel.kt
- src/main/resources/templates/admin/voters.html
- src/test/kotlin/com/terraformation/backend/accelerator/AcceleratorProjectServiceTest.kt
If a project had vote decision records for multiple phases, we were listing the
project multiple times on the voter management page in the admin UI, but only
showing the voters for the current phase.
Change the database query and the model class to be aware that there can be
multiple vote decisions for a project, and make the admin UI only show the current
phase.
> Fix duplicate projects on voters admin page

- src/main/resources/templates/admin/participant.html
The participant page in the admin UI had a block of JavaScript code left over from
an early stab at building a dynamic list of available projects.
> Remove unused code block from admin UI

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
To allow client-side code generation while the server side is still being
developed, add a stub `POST /api/v1/nursery/withdrawals/{withdrawalId}/undo`
implementation. This endpoint will undo a nursery withdrawal.
This change only defines the endpoint; initially it's a no-op. Later changes
will add the implementation.
> SW-5187 Add endpoint to undo nursery withdrawals

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/WithdrawalModel.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreGetNurseryStatsTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreUndoWithdrawalTest.kt
Add an `undoWithdrawal` method to `BatchStore` that reverses the effects of a
previous withdrawal on seedling batches.
Take undo withdrawals into account in the nursery stats calculations.
Currently, there is no way for an end user to use this code; it will be hooked
up to the API in a later change.
> SW-5188 Implement undo of nursery withdrawals

- src/main/kotlin/com/terraformation/backend/tracking/db/DeliveryStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/DeliveryModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/DeliveryStoreTest.kt
When an outplanting withdrawal is undone, we also need to undo the changes to the
plant totals at the destination planting site. Implement the logic for that.
> SW-5188 Implement undo of planting site deliveries

- build.gradle.kts
JobRunr 7 removed the dependency on Spring Boot's starter bundle for
Actuator, which is used for load balancer health checks; we were relying on that
transitive dependency. Add it as an explicit dependency.
> Add Spring Boot Actuator dependency

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
- src/main/kotlin/com/terraformation/backend/nursery/db/BatchStore.kt
- src/main/kotlin/com/terraformation/backend/nursery/model/WithdrawalModel.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/batchStore/BatchStoreFetchTest.kt
To allow the web app to link between original withdrawals and the withdrawals that
undo them, return "undoes" and "undone by" withdrawal IDs in the withdrawal GET
API payload.
> SW-5188 Include undo information in withdrawal payload

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
The "undo withdrawal" endpoint will now actually undo a withdrawal rather than
just returning a success response.
> SW-5188 Make nursery withdrawal undo endpoint functional

- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/OrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- previously was looking up the user's created time
- updated code to fetch the org user's created time (date/time when user was added to the org)
- updated existing tests to capture this scenario
> SW-5215 Fetch organization user's created_time when querying for organization users

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
To avoid the monitoring plot replacement code potentially leaking the planting
site ID for a monitoring plot the user doesn't have permission to read, add a
separate read permission for monitoring plots.
> SW-4796 Add monitoring plot read permission

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
Update the monitoring plot replacement code to work whether or not the full
grid of potential monitoring plots has been created up front. It creates new
monitoring plots as needed.
> SW-4796 Create replacement plots if needed

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
Currently, when a shapefile is imported to create a new planting site, or when a
new planting site is created via the admin UI, we create a grid of all the
possible monitoring plots across the entire site. For large sites, this can be
a bit slow and also fills the monitoring plots table with plots that won't be used
any time soon, if ever.
Now that the application code can create new plots on the fly as needed, there is
no longer a reason to create all the plots up front. Remove that part of the
import process.
> SW-4733 Don't generate all plots on shapefile import

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectModulesController.kt
- FE types expect the response payload to extend `SuccessResponsePayload` (`ServerData` on the FE).
> Add SuccessResponsePayload to GetProjectModulesResponsePayload

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectModulesController.kt
- This allows the enum to be carried to the frontend
- The OpenAPI type generation was ignoring the `EventType` as the key and converting it to `string`
- The property is needed in the context of the session in the frontend, we don't ever display an "event", we display the session instead.
> Put the event type in the ProjectModuleEventSession response object

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Constants.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ShapefileFeature.kt
- src/main/kotlin/com/terraformation/backend/util/Constants.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/ShapefileFeatureTest.kt
In preparation for keeping a history of planting site map updates, change
`PlantingSiteImporter` to create sites via `PlantingSiteStore` rather than by
directly inserting them into the database. The logic to maintain the map
history will then only need to exist in one place.
One difference between the two classes was that only `PlantingSiteImporter`
populated the area and grid origin fields. Move the calculations of those
values into `PlantingSiteStore` as well, which has the added benefit that
they'll be populated for site maps that aren't created via shapefile import.
> SW-5264 Use PlantingSiteStore to create site in importer

- src/main/kotlin/com/terraformation/backend/accelerator/SubmissionService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/SubmissionStore.kt
- src/main/kotlin/com/terraformation/backend/db/Extensions.kt
To make it a tiny bit less cumbersome to move away from DAO classes, add an
extension method to attach a jOOQ context to a `Record` object and return the
object, so it can be called as part of the expression that creates the object.
> Add convenience method for attached records

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/customer/event/PlantingSiteTimeZoneChangedEvent.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
In preparation for adding logic to edit existing planting sites, introduce
"new" and "existing" variants of `PlantingSiteModel` similar to the pattern we
use on other model classes.
The wrinkle here is that the parameterized nullability needs to also apply to
the models for planting zones and planting subzones.
This will allow us to use the model classes to represent a site/zone/subzone
hierarchy where some of the objects haven't been inserted into the database
yet.
This is mostly replacing `PlantingSiteModel` with `ExistingPlantingSiteModel`
in the application code (same with zone and subzone models), but also required
replacing a secondary constructor with a function so as to specify its return
type.
> Parameterize planting site model IDs

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
`PlantingSiteStore.createPlantingSite` now takes a planting site model instead
of a set of parameters for individual fields. (Planting seasons are still a
separate parameter for now.)
This is in preparation for moving the creation of planting zones and subzones
from `PlantingSiteImporter` to `PlantingSiteStore`, which will help support
user-drawn zone and subzone boundaries (where there is no shapefile to import)
as well as giving us a consistent place to create the initial map history
records for zones and subzones.
Aside from a new convenience function for creating `NewPlantingSiteModel`
objects, there is no functional change here, just moving values from function
parameters to model fields.
> SW-5228 Use model to create new planting sites

- src/main/kotlin/com/terraformation/backend/admin/AdminOrganizationsController.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
Early on in the development of the tracking features, all our test shapefiles were
invalid in one way or another, so we needed to be able to disable the various
validation checks in order to test the code.
Now that we have shapefiles whose geometries are valid and whose only "problem" is
that they sometimes lack target planting densities for zones, there's no need to
continue supporting invalid files. Remove the concept of "validation options" from
the importer and start treating target planting density as an optional value with
a default.
> SW-5230 Remove shapefile validation options

- jooq/src/main/kotlin/com/terraformation/backend/jooq/Config.kt
- src/main/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1.kt
- src/main/kotlin/com/terraformation/backend/search/table/SearchTables.kt
- src/main/kotlin/com/terraformation/backend/search/table/SpeciesGrowthFormsTable.kt
- src/main/kotlin/com/terraformation/backend/search/table/SpeciesTable.kt
- src/main/kotlin/com/terraformation/backend/species/api/SpeciesController.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesImporter.kt
- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/species/model/SpeciesModel.kt
- src/main/resources/db/migration/0250/V265__SpeciesGrowthForm.sql
- src/main/resources/db/migration/0250/V266__MigrateSpeciesGrowthForm.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/i18n/Messages_en.properties
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/db/SchemaDocsGenerator.kt
- src/test/kotlin/com/terraformation/backend/nursery/db/BatchImporterTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/model/ReportBodyModelV1Test.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionImporterTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/SpeciesServiceTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesImporterTest.kt
- src/test/kotlin/com/terraformation/backend/species/db/SpeciesStoreTest.kt
- Adds a table `species_growth_forms`, used to create a many-to-many relationship between the `species` table and `growth_forms` enum table.
- Migrate all `species.growth_form` into this new table
- Drop the `species.growth_form` column
- Update all tests to check for the new rows when checking species growth form data
- Update all controllers to return `species.growth_forms` instead of `species.growth_form`.
- Add `growthForms` sublist to `species` search table
TODO:
- FE is done, there seem to be no mobile considerations (this is being verified), so we can deploy them simultaneously with the next release.
> SW-5269 - Add species_growth_forms table

- src/main/kotlin/com/terraformation/backend/species/db/SpeciesStore.kt
In preparation for adding two new species-enum relationship tables (`species_successional_group`, `species_plant_material_sourcing`), refactor the updating of the two pre-existing ones (`species_growth_forms`, `species_ecosystem_types`) to use a function that updates the table
> Refactor species-enum-value updating

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
In preparation for moving planting zone/subzone validation and creation into
PlantingSiteStore, update PlantingSiteImporter to create zone and subzone
models and pass them around internally rather than using shapefile features.
Currently, the validation and database insertion still happen in
PlantingSiteImporter, so there's no caller-visible behavior change here, just
internal refactoring.
> SW-5264 Use model classes in PlantingSiteImporter

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Constants.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModelTest.kt
Currently, `PlantingSiteImporter` does two kinds of validation: checking that the
shapefiles are correctly formed (correct attribute names, etc.) and checking
that the maps in the shapefile obey our constraints on planting sites.
Move the constraint checks to `PlantingSiteModel` and `PlantingZoneModel` so we
can validate planting site maps that aren't in the form of shapefiles. This is
a step toward unifying shapefile-based and API-based detailed planting site
creation and updating, though for now, the validation is still only done during
shapefile import.
> SW-5228 Move planting site validation to model classes

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
`PlantingSiteUploadProblemsException` implies that a site has been uploaded,
but it's the exception we throw for map validation errors no matter where the
map data comes from. Rename it to `PlantingSiteMapInvalidException`.
> Rename exception to be less shapefile-centric

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModelTest.kt
Move the validation that a zone is big enough to fit a permanent cluster and a
temporary plot from `PlantingSiteImporter` to `PlantingZoneModel`.
> SW-5230 Validate zone size in PlantingZoneModel

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
`PlantingSiteStore.createPlantingSite()` now accepts detailed planting site 
models, validates them, and inserts the zones and subzones.
`PlantingSiteImporter` no longer interacts directly with the database; it just
constructs models from shapefiles.
This will allow us to support user-drawn detailed planting sites created via
API calls with the same behavior as shapefile import.
> SW-5264 Move detailed site creation to PlantingSiteStore

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
When a planting site with map data is created, or a simple planting site with a
map is updated, record the map geometries in `planting_site_histories` and
the child tables for zones and subzones.
The server doesn't currently support updates of detailed planting site maps,
so zone and subzone history records are only inserted at creation time; updating
of detailed planting site maps will be added in upcoming changes.
> SW-5264 Populate planting site history

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
The planting sites table has a constraint that requires the site's area in
hectares to be greater than 0, because we divide by the site area when
calculating certain statistics.
Previously, we didn't calculate the areas of simple planting sites at all, so
site maps could be arbitrarily tiny without violating the constraint. Commit
af1e716b started calculating areas for all sites, not just detailed ones, and
this caused creation of tiny simple sites to bomb out because their areas were
rounded down to 0.
Restore the previous behavior if a simple site's boundary is tiny: the area is
not stored at all. For larger simple sites, we continue to store it.
> Support tiny simple planting site maps

- src/main/kotlin/com/terraformation/backend/customer/db/ParentStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- Adds 4 new permissions: 
- `canCreateParticipantProjectSpecies`
- `canDeleteParticipantProjectSpecies`
- `canReadParticipantProjectSpecies`
- `canUpdateParticipantProjectSpecies`
> SW-5318 Participant Project Species permissions

- src/main/resources/db/migration/0250/V274__BackfillPlantingSiteHistories.sql
Insert planting site, zone, and subzone history records for existing sites created
before we started tracking map edit history.
> SW-5264 Backfill map history for existing sites

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- POST `/api/v1/accelerator/projects/species` endpoint for creating a single entry
- POST `/api/v1/accelerator/projects/species/assign` endpoint for bulk assigning species to projects
> SW-5318 Add endpoints for create and assign (create many) for ParticipantProjectSpecies

- src/main/kotlin/com/terraformation/backend/search/SearchResults.kt
- src/test/kotlin/com/terraformation/backend/accelerator/AcceleratorSearchTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/ModuleEventSearchTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/ModuleSearchTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/ProjectDeliverableSearchTest.kt
- src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt
- src/test/kotlin/com/terraformation/backend/search/SearchServiceTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceAgeFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceAliasedFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBasicSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceBooleanTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceCompoundSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceCursorTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceDateFieldSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceEnumTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceFuzzySearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceInitializationTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNestedFieldsTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceNullValueTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServicePermissionTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRangeSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceRawTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceUriFieldTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceUserSearchTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/search/SearchServiceWeightTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/TrackingSearchTest.kt
Having to explicitly set the search results cursor to `null` adds clutter to
tests. Make the field default to null and remove the explicit null values from
all the tests. Tests that pass non-null values (to test that cursors work) are
unchanged here.
> Add default value to SearchResults.cursor

- src/main/kotlin/com/terraformation/backend/accelerator/db/DeliverableStore.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/DeliverableStoreTest.kt
Description is an optional value on a deliverable, but we were treating it as
mandatory when fetching deliverables from the database.
> Fix NPE in DeliverableStore

- src/main/kotlin/com/terraformation/backend/accelerator/ParticipantProjectSpeciesService.kt
- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/SubmissionStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/SpeciesDeliverableSubmissionModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesServiceTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/SubmissionStoreTest.kt
- Adds a function to get the active species deliverable for a project if it exists
- Added service class `ParticipantProjectSpeciesService` which ensures a deliverable submission exists for the project when a species is added to a project with an active species deliverable
> Ensure a species deliverable submission when a species are added to a project

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteBuilder.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModelTest.kt
To support tests that need to construct planting site maps in specific
configurations, add a builder class that acts as a planting site DSL.
This allows site maps to be specified succinctly, which makes the test cases
easier to follow.
This is mainly motivated by the upcoming support for planting site map
editing, the tests for which require constructing lots of site maps. But it
also applies to some existing tests. `PlantingSiteModelTest` is updated to
use it.
> Add DSL for constructing planting sites in tests

- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculator.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSubzoneEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingZoneEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/Problems.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculatorTest.kt
In preparation for allowing editing of planting site maps, add logic to
calculate the differences between an existing planting site and a site map
requested by the user, and to detect edits that are disallowed according to the
product requirements.
The internal representation of a site edit will be used as the basis of both the
confirmation step in the UI ("this edit would do X, Y, and Z") and as input to
an update function that will apply the requested edits.
The code in this change only concerns itself with site geometry, not with any
of the other edit behaviors related to active observations or the presence of
planting data. Upcoming changes will cover those requirements.
> SW-5228 Calculate changes to site maps

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModelTest.kt
We don't allow exclusion areas to completely cover subzones; the user should
delete the subzones from the site in that case. Detect completely-excluded
subzones as part of planting site validation.
> SW-5354 Disallow exclusion of whole subzones

- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculator.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/Problems.kt
- src/test/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculatorTest.kt
The behavior of site editing needs to differ depending on whether or not the edits
affect subzones with plants in them:
- If the site has no plants at all, it can be edited freely with no restrictions
on changes to existing zones and subzones.
- Removing a subzone that has plants isn't allowed.
Add logic for both of those rules to  `PlantingSiteEditCalculator`.
> SW-5228 Make edit calculator aware of planted subzones

- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculator.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSubzoneEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingZoneEdit.kt
- src/test/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculatorTest.kt
Zone and subzone creation and deletion edits always pull all their values from
a single model, and update edits pull many of their values from the "existing"
and "desired" models; include those models directly in the edit classes rather
than copying the relevant values.
> Use zone and subzone models in edits

- src/main/kotlin/com/terraformation/backend/db/GeometryBinding.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Shapefile.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ShapefileFeature.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/UnusedSquareFinder.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
JTS Geometry objects remember which factory created them, so we can reuse that
factory when we're creating derived geometries.
But when we were reading geometry values from the database, we were using a
geometry factory that didn't have the correct SRID to indicate that the
coordinates were longitude and latitude, so reusing those objects' factories
would produce geometries with incorrect SRIDs.
Set the correct SRID when constructing new geometries, and reuse the existing
factory when deriving new geometries from existing ones.
> Set and use correct factory on geometry objects

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculator.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/plantingSiteStore/PlantingSiteStoreCreateSiteTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteBuilder.kt
In the upcoming changes to support planting site editing, we're supposed to update
the site/zone/subzone area in hectares if an exclusion grows or shrinks. But we
were disregarding exclusions in the initial area calculations at site creation
time, which would have been inconsistent with the new behavior.
Internally, areas were being calculated as part of writing the site data to the
database, and the site/zone/subzone models were being intentionally constructed
with dummy values for their areas, meaning that newly-constructed models weren't
representative of the actual site data.
Move the area calculations into the model classes (or rather, the `create`
functions we use to construct new models) and make them take exclusions into
account.
> SW-5230 Ignore exclusions in site/zone/subzone areas

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ParticipantProjectForSpecies.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/SpeciesForParticipantProject.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
Add two new endpoints (in lieu of using the Search API) for:
- Retrieving projects associated to species through the Participant Project Species (PPS)
- An active deliverable ID (according to the cohort module dates) will be included if it exists
- Retrieving species associated to a project through PPS
> Add two new endpoints for Participant Project Species 

- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEdit.kt
- src/main/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculator.kt
- src/test/kotlin/com/terraformation/backend/tracking/edit/PlantingSiteEditCalculatorTest.kt
Commit ce51d3cd introduced "existing" and "desired" models to the planting zone
and subzone edit classes, replacing fields that pulled values from those models.
Do the same for the top-level edit class for the site as a whole.
> Use site models in PlantingSiteEdit

- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/resources/templates/email/plantingSite/mapEdited/body.ftlh.mjml
- src/main/resources/templates/email/plantingSite/mapEdited/body.txt.ftl
- src/main/resources/templates/email/plantingSite/mapEdited/subject.ftl
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteBuilder.kt
Add notification logic to send email to the organization's Terraformation contact
when a detailed planting site is edited.
Currently, nothing publishes the event that triggers the email; it will be added
in a later change.
> SW-5230 Add email notification for site map edit

- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/plantingSiteStore/PlantingSiteStoreApplyEditTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteBuilder.kt
Add logic to apply the output of `PlantingSiteEditCalculator` to a site.
This does not implement any of the behavior related to plot replacement when
observations are active; that will be added in a later change.
> SW-5230 Apply planting site edits

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlotAssignmentTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporterTest.kt
Refactor the shapefile import code so there's a public method to turn a list of
shapefiles into a `NewPlantingSiteModel`. This will be used by the admin UI
when it supports uploading revised shapefiles for an existing planting site.
> SW-5228 Make shapefile importer site models accessible

- src/main/kotlin/com/terraformation/backend/admin/Extensions.kt
- src/main/resources/templates/admin/header.html
The page header template for the admin UI can show a bullet list of failure
details in addition to a failure message. Add the same functionality for
success details. This will be used to show the results of planting site map
edit dry runs.
> Show success details in admin UI

- src/main/kotlin/com/terraformation/backend/admin/AdminPlantingSitesController.kt
- src/main/resources/templates/admin/plantingSite.html
Add an upload form to the planting site details page in the admin UI to allow
admins to upload revised shapefiles for existing detailed planting sites.
By default, it does a dry run and reports the change in plantable area of the
site as a whole and of each zone. The admin can then choose to actually apply
the changes to the site.
> SW-5230 Add shapefile update to admin UI
