- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
`accessions.primary_collector_name` and `accession_secondary_collectors` are no
longer queried anywhere, so stop writing to them.
The fourth and final step in this migration series will drop them, but this step
needs to be deployed first so that dropping them doesn't cause failures while the
code is being deployed and the cluster is running a mix of old and new releases.
> SW-1350 Migrate to accession_collectors table 3/4

- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
The client code no longer calls the old `/api/v1/seedbank/summary/{facilityId}`
endpoint, so remove it from the API.
> Remove unused summary endpoint

- src/main/kotlin/com/terraformation/backend/search/SearchService.kt
To calculate accession stats based on search filters, we will need to construct a
"get the summary stats" query that includes the underlying search query. Rework
the query construction in `SearchService` so that it exposes a method that returns
the `NestedQueryBuilder`.
No change in behavior here (tests continue to pass as-is).
> SW-1388 Refactor SearchService to expose subquery

- src/main/kotlin/com/terraformation/backend/seedbank/api/SummaryController.kt
Add a new `POST /api/v1/seedbank/summary` endpoint that takes a payload with
search criteria in the same format as `/api/v1/search`. It returns a summary of
data about the accessions that match the search. The summary covers the entire
set of search results (no pagination).
> SW-1388 Add accession search summary endpoint

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/AccessionStoreTest.kt
In the v2 accession API, the client passes in a species ID rather than a species
name. But we weren't actually storing that ID in the database.
> Use client-supplied species IDs in v2 accession API

- gradle.properties
- src/test/kotlin/com/terraformation/backend/db/GeometryDeserializerTest.kt
And run `spotlessApply` to apply its updated rules to the code base.
> Upgrade to ktfmt 0.41

- src/main/kotlin/com/terraformation/backend/seedbank/api/AccessionsController.kt
Now that the production web app is switched over to the v2 accessions API, we can
start to get rid of the v1 API and its implementation.
This initial change removes the v1 API endpoints that have been supplanted by v2
equivalents, and removes some code that was only referenced by the endpoints'
controller methods. Specifically, the following endpoints go away:
* `GET /api/v1/seedbank/accessions/{id}` (read accession)
* `POST /api/v1/seedbank/accessions` (create accession)
* `PUT /api/v1/seedbank/accessions/{id}` (update accession)
In addition, `POST /api/v1/seedbank/accessions/{id}/checkIn` now returns a v2
response payload instead of a v1 payload. Previously, you'd get back a v1-style
response even if you were checking in an accession you'd creeated with v2, and
you'd then have to …
> SW-1939 Remove v1 accession endpoints

- src/main/kotlin/com/terraformation/backend/email/WebAppUrls.kt
- mistake in constructing as a local URL
- add the leading webAppUrl in for full URL
> Fix Full Batch URL

- .github/workflows/main.yml
Transition all released Jira issues to the "Released to Production" status
> SW-2068 Use github action to automatically transition Jira issues at release

- src/main/resources/application.yaml
- needed for FE api types generation
> allow generating types for tracking api

- src/main/kotlin/com/terraformation/backend/auth/HttpLocalhostRedirectConfig.kt
- src/main/kotlin/com/terraformation/backend/customer/api/LoginController.kt
Attempt to fix the problem with the login flow that prevented us from pointing
local web app dev environments at the staging or production server instances.
> SW-1054 Support localhost HTTP redirects

- src/main/kotlin/com/terraformation/backend/auth/HttpLocalhostRedirectConfig.kt
The hack in commit 1e987c94 failed to solve the problem in the actual staging
environment; the port number of the original request didn't make it through
the AWS load balancer plus the Nginx proxy. Try a different approach that uses
the redirect URL that's passed in by the client.
> SW-1054 Support localhost HTTP redirects, round two

- README.md
- src/main/resources/templates/email/head.ftlh.mjml
- src/main/resources/templates/email/logo.ftlh.mjml
Made updates to styles in email template, including colors, font sizes,
and border radii. Images did not render during local testing (see below),
but they are correctly positioned and sized, and as such should properly
render once in staging.
> SW-2180 Email Notification Styling Updates

- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Switch to the recipient user's locale before rendering the notification messages.
> SW-2798 Localize in-app notifications

- src/main/kotlin/com/terraformation/backend/search/field/EnumField.kt
Different locales have different rules for sorting text. When an enum field is
used as a sort field in a search API call, we need to sort based on the correct
rules.
We were already mapping enum values to localized display names for sorting
purposes, but that would have ended up sorting based on the database's default
rules. Make this more correct and more efficient by instead mapping enum values
to integers representing the correct sort order of the localized display names.
For gibberish, there's no behavior change here since gibberish uses English
sort ordering. The existing tests that cover this functionality continue to pass.
> SW-2800 Sort enums using locale's ordering rules

- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
When two `PUT /api/v1/users/me/preferences` requests came in at the same time, the
server tried to insert both of them at the same time, which failed because of the
unique indexes on the preferences table.
> SW-2872 Handle concurrent user preference writes

- src/main/kotlin/com/terraformation/backend/seedbank/api/StorageLocationsController.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreSummaryTest.kt
The UI needs to show the number of active accessions in each storage location.
Include it in the GET API responses.
> SW-2912 Return active accessions per storage location

- build.gradle.kts
The Gradle `generateOpenApiDocs` task produced a bunch of warning messages. These
were due to https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/100
but luckily there's a workaround.
Also upgrade to the latest version of that plugin so we can remove Spring Boot
Devtools from  the classpath of the server that gets started by that task; it
spits out log messages at startup which make the build noisier.
> SW-2968 Fix Gradle warnings on generateOpenApiDocs

- src/main/kotlin/com/terraformation/backend/customer/db/OrganizationStore.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
Once a day, check whether or not there are organizations with the `Reporter`
internal tag that don't yet have a report for the previous calendar quarter. If
there are any, create reports for them.
For ad-hoc testing in dev environments, advancing the test clock using the admin
UI will cause daily tasks to run.
This requires a minor change to the permission logic in `OrganizationStore`,
which previously didn't allow the system user to fetch organization details
because the system user doesn't support enumerating its organization and
facility roles.
> SW-2992 Automatically create reports

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/main/kotlin/com/terraformation/backend/report/ReportFileService.kt
- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/report/db/ReportStore.kt
- src/main/kotlin/com/terraformation/backend/report/event/ReportDeletionStartedEvent.kt
- src/main/resources/templates/admin/organization.html
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportFileServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/db/ReportStoreTest.kt
Allow super-admins to delete reports, including all their files and photos.
> SW-3205 Add "delete report" button to admin UI

- src/main/resources/i18n/Enums_en.properties
- src/main/resources/i18n/Enums_es.properties
Exported the most recent locale files from Phrase
> Updated translations from Phrase

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Models.kt
- src/main/resources/templates/admin/plantingSiteMap.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
Implement the selection logic for temporary monitoring plots, and show example
plots on the site map in the admin UI.
> SW-3544 Temporary monitoring plot selection

- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationModel.kt
- src/test/kotlin/com/terraformation/backend/Helpers.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
`POST /api/v1/tracking/observations/{observationId}/plots/{plotId}` records the
results of an observation of a monitoring plot.
> SW-3607 Endpoint to record plot observation

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
Previously, we required each monitoring plot to be completely contained in a
single subzone, but we no longer want to exclude such plots from eligibility
for monitoring.
Update the shapefile importer to assign monitoring plots to the subzones that
they overlap with the most.
> SW-3637 Allow monitoring plots to straddle subzones

- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/ObservationsController.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
Add a GET endpoint to fetch photos of monitoring plots taken during observations.
The file IDs of the photos are already included in the observation results, so
there is no "list photos" endpoint. As with the other photo endpoints in the API,
optional `maxWidth` and `maxHeight` parameters can be included to retrieve
thumbnails.
> SW-3699 API endpoint to fetch observation photos

- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
Refactor two query methods in `ObservationStore` that get a list of observations
that's filtered based on what the current date is in the planting sites' time
zones. No change in behavior here; this is in preparation for adding a third query
that does something similar.
> Refactor date-based observation queries

- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/daily/ObservationScheduler.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/WebAppUrls.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/ObservationStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ObservationModel.kt
- src/main/resources/db/migration/0200/V202__ObservationNotifications.sql
- src/main/resources/db/migration/R__Comments.sql
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- src/main/resources/i18n/Messages_en.properties
- src/main/resources/templates/email/observation/upcoming/body.ftlh.mjml
- src/main/resources/templates/email/observation/upcoming/body.txt.ftl
- src/main/resources/templates/email/observation/upcoming/subject.ftl
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/ObservationStoreTest.kt
Notify all organization members when an observation is due to start the following
month.
> SW-3743 Notify when observation is 1 month away

- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreSummaryTest.kt
- src/test/kotlin/com/terraformation/backend/seedbank/db/accessionStore/AccessionStoreTest.kt
- extracted out the species query separately
- i don't know if this is the best way to accomplish what we want, open to suggestions
- added a test
> SW-3769 Skip deleted species in summary statistics

- src/main/resources/csv/accessions-template_es.csv
- src/main/resources/csv/batches-template_es.csv
- src/main/resources/csv/species-template_es.csv
Add Spanish versions of the accession, seedling batch, and species CSV templates.
> SW-3797 Add Spanish CSV templates

- src/main/kotlin/com/terraformation/backend/customer/AppNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/kotlin/com/terraformation/backend/i18n/Messages.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- src/main/resources/i18n/Messages_en.properties
- src/main/resources/templates/email/observation/started/body.ftlh.mjml
- src/main/resources/templates/email/observation/started/body.txt.ftl
- src/main/resources/templates/email/observation/started/subject.ftl
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
Send email and in-app notifications to the organization when an observation
starts.
> SW-3810 Send notification when observation starts

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
Initially, we were going to include monitoring plot boundaries in uploaded
shapefiles for planting sites. Since there can be many thousands of monitoring
plots at a large site, this caused the shapefiles to be large enough that we
needed to stream their data in the application code rather than letting Spring
and Tomcat load them into memory or store them on disk.
But now we generate monitoring plot boundaries programmatically, and the
shapefiles are far smaller. So we can process them using the built-in file
upload support in Spring MVC. This is not only simpler, but avoids using an
API that's no longer supported in Spring Boot 3.
> Stop supporting huge shapefiles

- src/main/resources/csv/species-template.csv
- src/main/resources/csv/species-template_es.csv
- src/main/resources/csv/species-template_gx.csv
We added new seed storage behaviors and growth forms but didn't list them as
options in the species CSV template.
> SW-3819 Add seed storage behaviors and growth forms to CSV

- src/main/resources/csv/species-template_es.csv
Update the Spanish species CSV template to use revised translations for "Forb"
and "Vine."
> SW-3867 Update growth form translations

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/resources/templates/admin/organization.html
- src/main/resources/templates/admin/plantingSite.html
- src/main/resources/templates/admin/plantingSiteMap.html
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Allow creating and viewing simple planting sites from the admin UI.
> SW-3932 Admin UI support for simple planting sites

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com/terraformation/gradle/RenderMjmlTask.kt
This requires a slight code change to stop using a plugin class that was
removed in 7.0.
> Update dependency com.github.node-gradle:gradle-node-plugin to v7

- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesHistoryController.kt
`GET /api/v1/nursery/batches/{batchId}/history` will return the history of changes
to a seedling batch.
> SW-4368 Add endpoint to fetch batch history

- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/resources/i18n/Messages_en.properties
- src/main/resources/templates/email/observation/plotReplaced/body.ftlh.mjml
- src/main/resources/templates/email/observation/plotReplaced/body.txt.ftl
- disable the opt in flag option
- also added an email title (matching the subject) similar to other observation notification emails (i can remove this if needed, this is mostly for visual appeal)
- wrapped freemarker tags with `<!-- htmlmin:ignore>`
> SW-4428 Force send email notification to TF contact on plot replacement request

- src/main/kotlin/com/terraformation/backend/nursery/api/BatchesHistoryController.kt
The code generator we use to generate TypeScript types from the OpenAPI schema
doesn't make use of discriminator mappings on polymorphic payloads, so it was
failing to generate usable types for the batch history payloads.
Change the payload type hierarchy and annotations to produce a schema that is
still correct but has what the code generator needs:
- `BatchHistoryPayload` no longer has any properties, which allows the code
generator to turn it into a simple union type. The common properties have
been moved to a new `BatchHistoryPayloadCommonProps` class, which each
subclass includes in its "allOf" schema property.
- The `type` field is on each subclass is now a string rather than an enum.
It now has a a `@Schema` annotation on it to specify that it must have a
specific value. This …
> SW-4432 Make batch history payload OpenAPI schema TS-friendly

- src/main/kotlin/com/terraformation/backend/util/ImageUtils.kt
- src/test/kotlin/com/terraformation/backend/util/ImageUtilsTest.kt
Currently, the content type validation in the image upload endpoints just looks at
the client-supplied MIME type and believes it. It's thus possible for a client to
say it's uploading a JPEG image but actually upload some other kind of file, and
the server will store it in the file store.
But when we then try to generate a thumbnail for that image, it will fail because
the Java ImageIO class doesn't know how to load images of unsupported types.
Previously, this resulted in a NullPointerException with no additional detail.
Add logic to try to detect the file type from its content and throw a more useful
exception so we can diagnose why thumbnail generation is failing.
> SW-4439 Throw better error for unsupported image type

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/ShapefileFeature.kt
Detect when someone tries to upload a shapefile that spans a very large area,
rather than attempting to generate a covering grid of monitoring plots; the
grid generation would eventually succeed, but would take long enough for the
shapefile upload to time out.
The size limit here is somewhat arbitrary, but is significantly larger than
any of the planting sites we've already created or any of the large dummy
sites we've used for testing.
> SW-4466 Add shapefile area sanity check

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSeasonModel.kt
- src/test/kotlin/com/terraformation/backend/customer/AppNotificationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/customer/ProjectServiceTest.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/PlantingSiteServiceTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
Implement the write path for planting seasons. They can be included at planting
site creation time and can be updated on existing sites.
> SW-4410 Modify planting seasons

- src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt
- src/main/kotlin/com/terraformation/backend/daily/PlantingSeasonScheduler.kt
- src/main/kotlin/com/terraformation/backend/tracking/ObservationService.kt
- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStore.kt
- src/main/kotlin/com/terraformation/backend/tracking/event/Events.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/NotificationCriteria.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/test/kotlin/com/terraformation/backend/daily/PlantingSeasonSchedulerTest.kt
This is the same as commit ebf2a24d (which was reverted) but this time with a
feature flag that has to be enabled to generate the notification events.
> SW-4411 Detect when no planting season scheduled, try 2

- src/main/kotlin/com/terraformation/backend/customer/api/AdminController.kt
- src/main/resources/templates/admin/globalRoles.html
- src/main/resources/templates/admin/index.html
Add a section to the admin UI to allow super-admins to assign global roles to
internal users.
> SW-4601 Add global roles to admin UI

- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ParticipantModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Add a store class for accessing participant data.
> SW-4602 Add ParticipantStore

- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
To support participant management, add a `ProjectStore` method to allow a
project's participant ID to be changed.
> SW-4602 Add ability to set project's participant ID

- src/main/kotlin/com/terraformation/backend/admin/AdminController.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminParticipantsController.kt
- src/main/resources/templates/admin/index.html
- src/main/resources/templates/admin/listParticipants.html
- src/main/resources/templates/admin/participant.html
Add a new "Participants" section to the admin UI, accessible to both super-admins
and accelerator admins, that allows participants to be managed.
> SW-4603 Participant management in admin UI

- src/main/kotlin/com/terraformation/backend/accelerator/event/ParticipantProjectAddedEvent.kt
- src/main/kotlin/com/terraformation/backend/accelerator/event/ParticipantProjectRemovedEvent.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/main/kotlin/com/terraformation/backend/email/EmailNotificationService.kt
- src/main/kotlin/com/terraformation/backend/email/model/Models.kt
- src/main/resources/templates/email/participant/projectAdded/body.ftlh.mjml
- src/main/resources/templates/email/participant/projectAdded/body.txt.ftl
- src/main/resources/templates/email/participant/projectAdded/subject.ftl
- src/main/resources/templates/email/participant/projectRemoved/body.ftlh.mjml
- src/main/resources/templates/email/participant/projectRemoved/body.txt.ftl
- src/main/resources/templates/email/participant/projectRemoved/subject.ftl
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- src/test/kotlin/com/terraformation/backend/email/EmailNotificationServiceTest.kt
Send notifications to the organization's Terraformation contact or the
support list when projects are added to or removed from participants.
> SW-4605 Notify when participant projects change

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- Add helper methods to make a GeometryFactory with the correct SRID
- Use property syntax rather than calling setter methods (removes some IntelliJ
code style warnings)
- Use "when" instead of multi-branch "if/else"
> Minor code cleanup in PlantingSiteImporter

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/util/Extensions.kt
We need to construct rectangles in several places in the code; add a helper
function as an extension of `GeometryFactory` to do it.
> Add extension method to create rectangles

- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/main/kotlin/com/terraformation/backend/util/Turtle.kt
- src/test/kotlin/com/terraformation/backend/tracking/db/PlantingSiteStoreTest.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
The newly-introduced Turtle class is mostly being used to generate rectangles and
squares. Add a couple convenience methods to make rectangle and square creation
more succinct.
> Add rectangle and square methods to Turtle

- src/main/kotlin/com/terraformation/backend/customer/db/FacilityStore.kt
In end-to-end tests, we were sometimes sending two facility creation requests at
the exact same time from different browsers. This exposed a race in the facility
creation code where the same facility number would be used for both facilities,
causing one of the creations to fail with a unique key violation.
Fix it by serializing facility creation using a row lock on the organization.
> Fix facility creation race condition

- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModelTest.kt
In preparation for adding on-demand creation of temporary plots, update
`PlantingZoneModelTest` to construct boundaries big enough for monitoring
plots.
> Use properly-sized boundaries in PlantingZoneModelTest

- src/main/kotlin/com/terraformation/backend/report/ReportService.kt
- src/main/kotlin/com/terraformation/backend/seedbank/db/AccessionStore.kt
- src/test/kotlin/com/terraformation/backend/report/ReportServiceTest.kt
- Scope the subquery for seedbank project stats to the facility so that `totalSeedsStoredForProject` is scoped to that seedbank
> SW-4770 Fix totalSeedsStoredForProject stat calculation

- src/main/kotlin/com/terraformation/backend/api/OpenApiConfig.kt
- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
Allow clients to supply planting site boundaries as either MultiPolygon or Polygon
geometries. This will save clients the trouble of converting single-polygon site
boundaries to MultiPolygon solely because it's required by the API.
This requires updating our OpenAPI schema customization code to handle properties
that are references to payload classes but have explicit annotations to list which
types are allowed.
> Accept Polygon planting site boundaries

- src/main/resources/application.yaml
- added accelerator api package to yaml
> Add accelerator api to packages that need to be scanned for api docs

- src/main/kotlin/com/terraformation/backend/accelerator/api/CohortsController.kt
> Rename property in cohort list response payload

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
Define the APIs for uploading documents to satisfy deliverables and for updating
the status of a submission.
Currently these endpoints return dummy responses, but they can be used for code
generation on the client side.
> SW-4934 Upload and update endpoints for deliverables

- src/main/kotlin/com/terraformation/backend/accelerator/api/GlobalRolesController.kt
- src/main/kotlin/com/terraformation/backend/customer/api/GlobalRolesController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/db/UserStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- Add GET and POST API for interacting with global roles. 
- Permission check for the POST API is within the `userStore` call
> SW-4835 Create rest api for getting global roles and updating a user's global roles

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/SubmissionStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/SubmissionStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
Replace the stub implementation of the deliverable status update endpoint with a
real one.
> SW-5000 Implement deliverable status update

- src/main/kotlin/com/terraformation/backend/accelerator/api/DeliverablesController.kt
Replace the dummy data in the "list deliverables" and "get deliverable" endpoints
with the real implementation.
> SW-4952 Implement deliverable GET endpoints

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectVotesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/VoteStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/VoteModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/VoteStoreTest.kt
Updated Votes controller to take in final decision. 
Updated store to retrieve user info
> SW-4994 Implemented Vote Controller

- src/main/kotlin/com/terraformation/backend/customer/api/GlobalRolesController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- In order to show the "Date Added" column in the "list people" accelerator view, add `createdTime` to the `IndividualUser` and `UserWithGlobalRolesPayload`.
> SW-5047 Add createdTime to IndividualUser and UserWithGlobalRolesPayload

- src/main/kotlin/com/terraformation/backend/customer/api/UsersController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/UserStore.kt
- src/main/kotlin/com/terraformation/backend/customer/model/DeviceManagerUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/IndividualUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/main/kotlin/com/terraformation/backend/customer/model/SystemUser.kt
- src/main/kotlin/com/terraformation/backend/customer/model/TerrawareUser.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionTest.kt
- Add "get user" API, only supports "ordinary" users for now. 
- Add "search users" API, only supports search by email for now.
> SW-4961 Get User and Search Users API

- src/test/kotlin/com/terraformation/backend/i18n/EnumsTest.kt
When EnumsTest detects that English-name entries are missing from a properties
file, make its assertion failure message include a list of lines that can be
copied into the properties file as a starting point.
The English strings will still require human review, and, if needed, comments
will still need to be written to clarify terminology for translators. But this
should make it slightly less annoying to add missing enums to the strings files.
The assertion failure output will look like
org.opentest4j.AssertionFailedError: Bundle i18n.Enums is missing values ==> expected: <> but was: 
<public.GrowthForm.Graminoid=Graminoid
public.GrowthForm.Liana=Liana
public.GrowthForm.Lichen=Lichen
public.GrowthForm.Moss=Moss>
> Make EnumsTest output more useful

- src/main/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ProjectAcceleratorDetailsModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStoreTest.kt
Add a store class for reading and writing projects' accelerator details.
> SW-5070 Add ProjectAcceleratorDetailsStore

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectAcceleratorDetailsController.kt
Add GET and PUT endpoints `/api/v1/accelerator/projects/{projectId}` for accessing
the accelerator details of individual projects.
> SW-5070 API endpoints for project accelerator details

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantsController.kt
Add CRUD endpoints for participant management.
> SW-5043 Participants CRUD API

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantsController.kt
- we missed passing in the project ids
> Pass project ids to participant create from the controller

- src/main/kotlin/com/terraformation/backend/accelerator/api/ProjectAcceleratorDetailsController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ProjectAcceleratorDetailsModel.kt
- src/main/kotlin/com/terraformation/backend/search/table/ProjectAcceleratorDetailsTable.kt
- src/main/resources/db/migration/0250/V257__ProjectAbbreviatedName.sql
- src/main/resources/i18n/Messages_en.properties
- src/test/kotlin/com/terraformation/backend/accelerator/AcceleratorSearchTest.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ProjectAcceleratorDetailsStoreTest.kt
- src/test/kotlin/com/terraformation/backend/db/DatabaseTest.kt
Add a project accelerator details field for an abbreviated project name that's set
by the accelerator team.
> SW-5070 Add "abbreviated name" project field

- src/main/kotlin/com/terraformation/backend/customer/api/ProjectsController.kt
- src/main/kotlin/com/terraformation/backend/customer/model/ProjectModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/AcceleratorOrganizationStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- Add these fields to Project model and GET response payload:
```
createdBy
createdTime
modifiedBy
modifiedTime
```
> SW-4713 Add fields to Project model and GET response payload

- src/main/kotlin/com/terraformation/backend/accelerator/model/ProjectCohortData.kt
- src/main/kotlin/com/terraformation/backend/customer/api/ProjectsController.kt
- src/main/kotlin/com/terraformation/backend/customer/db/ProjectStore.kt
- src/test/kotlin/com/terraformation/backend/customer/db/ProjectStoreTest.kt
- Add method to fetch cohort details for a project ID
- Insert cohort details into GET project response if the project is associated to a cohort
> Add cohort details to GET project API

- src/test/kotlin/com/terraformation/backend/tracking/ObservationServiceTest.kt
Add a helper method to insert clusters of monitoring plots.
In addition to reducing repetition in the test code, the helper method also places
the plots in the correct geographic positions. This is a step toward updating the
test to continue to pass when the plot replacement logic is updated to support
on-the-fly creation of plots based on the site map.
> SW-4796 Reduce repetition in ObservationServiceTest

- src/main/kotlin/com/terraformation/backend/nursery/api/WithdrawalsController.kt
In preparation for adding a new withdrawal purpose for undoing previous
withdrawals, update the "create withdrawal" endpoint to use its own list of
valid withdrawal purposes.
When the new purpose is added, it will appear in the `WithdrawalPurpose`
enum, but with this change it won't be listed as a valid user-supplied
purpose for withdrawal creation in the OpenAPI schema.
> SW-5187 Add valid user-supplied withdrawal purposes

- .github/scripts/notifications.py
- .github/workflows/docs.yaml
- docs/.gitignore
- docs/index.md
Parse the notifications from the messages file to generate some documentation that can get added to the auto-generated docs.
> SW-5213 Generate some documentation on in-app and email notifications

- src/main/kotlin/com/terraformation/backend/accelerator/db/ModuleEventStore.kt
- src/main/kotlin/com/terraformation/backend/admin/AdminModulesController.kt
- src/main/resources/templates/admin/moduleView.html
- src/main/resources/templates/admin/modules.html
- src/main/resources/templates/admin/voters.html
- src/test/kotlin/com/terraformation/backend/accelerator/db/ModuleEventStoreTest.kt
Table for all modules
Module Preview
Event List 
Module Events multi-select for updating participants
> SW-5201 Module Events Admin UI

- scripts/example_values.py
This script was exiting halfway through because of a duplicate species name
> Fix 'create species' script

- src/main/kotlin/com/terraformation/backend/accelerator/db/ModulesImporter.kt
Changes following to updates to spreadsheet format.
> Updated module importer to also read phase from csv

- src/main/kotlin/com/terraformation/backend/tracking/db/PlantingSiteImporter.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingSubzoneModel.kt
- src/main/kotlin/com/terraformation/backend/tracking/model/PlantingZoneModel.kt
- src/test/kotlin/com/terraformation/backend/tracking/model/PlantingSiteModelTest.kt
Add convenience functions for constructing new `PlantingZoneModel` and
`PlantingSubzoneModel` objects with reasonable defaults.
> Add constructor helpers for zone and subzone models

- src/main/kotlin/com/terraformation/backend/tracking/model/ShapefileFeature.kt
We were setting the SRID on the geometries we got back from GeoTools' shapefile
parser, but we weren't setting it in such a way that `Geometry.getEnvelope()`
would return a geometry with the same SRID.
This was causing the maximum envelope size validation check to bomb out with
actual shapefiles, though it worked with the programmatically-constructed
"shapefiles" in our unit tests since they don't go through the parser.
> Fix site size validation on shapefile upload

- src/main/kotlin/com/terraformation/backend/tracking/api/PlantingSitesController.kt
`POST /api/v1/tracking/sites` now accepts optional planting zone and subzone 
definitions and will create a detailed planting site if they're present.
Detailed planting sites must obey all the same constraints (minimum areas,
unique names, etc.) that already apply to shapefile upload. In this initial
version, the API doesn't have a mechanism for communicating detailed validation
failure messages back to the client; that will be added later.
> SW-4834 Support creating detailed sites via API

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/ParticipantProjectSpeciesModel.kt
- src/main/kotlin/com/terraformation/backend/customer/model/PermissionRequirements.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
- src/test/kotlin/com/terraformation/backend/customer/model/PermissionRequirementsTest.kt
- Adds validation to make sure the given project has a participant
> SW-5318 Add create store functionality for ParticipantProjectSeries

- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
- This will be used so assign a bulk list of species to any number of projects
> SW-5318 Add createMany function to ParticipantProjectSpeciesStore

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
- Add update function to `ParticipantProjectSpeciesStore`
- Add controller endpoint for updating a participant project species
> SW-5318 Add update functionality for ParticipantProjectSpecies

- src/main/kotlin/com/terraformation/backend/accelerator/api/ParticipantProjectSpeciesController.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/Exceptions.kt
- src/main/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStore.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/ParticipantProjectSpeciesStoreTest.kt
- Add `deleteMany` functionality to `ParticipantProjectSpeciesStore`
- Add `DELETE  /api/v1/accelerator/projects/species` endpoint
> SW-5318 Add deleteMany functionality to ParticipantProjectSpecies

- src/main/kotlin/com/terraformation/backend/accelerator/db/DeliverablesImporter.kt
- src/main/resources/db/migration/R__TypeCodes.sql
- src/main/resources/i18n/Enums_en.properties
- Throws a descriptive error if the value is not "document" or "species".
Here's the CSV I used to test with
[DD Phase - Deliverable and Module Data - Deliverables - 240507.csv](https://github.com/terraware/terraware-server/files/15241217/DD.Phase.-.Deliverable.and.Module.Data.-.Deliverables.-.240507.csv)
> Add 'Species List' Deliverable Type to deliverable importer

- src/main/kotlin/com/terraformation/backend/accelerator/db/DeliverableStore.kt
- src/main/kotlin/com/terraformation/backend/accelerator/model/DeliverableSubmissionModel.kt
- src/test/kotlin/com/terraformation/backend/accelerator/db/DeliverableStoreTest.kt
Added due dates to deliverable store and deliverableSubmissionModel
Added test cases
> SW-5368 Added due dates to deliverable store and deliverableSubmissionModel

- src/main/kotlin/com/terraformation/backend/admin/AdminCohortsController.kt
- src/main/resources/templates/admin/cohortDeliverable.html
- src/main/resources/templates/admin/cohortView.html
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/9c0f30b5-f8fd-4a52-8261-f38aa15d8464.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/9c0f30b5-f8fd-4a52-8261-f38aa15d8464.mov">Screen Recording 2024-05-17 at 5.31.50 PM.mov</video>
> SW-5369 Added admin UI for managing due dates
